#!/bin/bash
#
# Generates polkadot-app/Generated/Secrets.generated.swift from secret values.
#
# Values are sourced, in order of precedence:
#   1. polkadot-app/env-vars.sh (local development, gitignored)
#   2. the current process environment (CI injects these from GitHub secrets)
#
# Any value that is not provided becomes an empty string. The generated file is
# gitignored (*.generated.swift) and must never be committed.

set -euo pipefail

SRCROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

ENV_FILE="${SRCROOT}/polkadot-app/env-vars.sh"
if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    source "$ENV_FILE"
fi

OUTPUT_DIR="${SRCROOT}/polkadot-app/Generated"
OUTPUT_FILE="${OUTPUT_DIR}/Secrets.generated.swift"
mkdir -p "$OUTPUT_DIR"

# Escape a value for safe embedding inside a Swift double-quoted string literal:
# backslashes first, then double quotes.
swift_escape() {
    printf '%s' "${1:-}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

cat > "$OUTPUT_FILE" <<EOF
// Generated by Runscripts/generate_secrets.sh — do not edit or commit.
// Values are injected from polkadot-app/env-vars.sh (local) or CI secrets.

enum GeneratedSecrets {
    static let sentryDSN = "$(swift_escape "${SENTRY_DSN:-}")"
}
EOF

echo "Generated ${OUTPUT_FILE}"
