//! Experimental: a product worker compiled to wasm, run in the core.
//!
//! The worker is bound to one product. Each `truapi` import it declares is
//! linked to a typed call on that product's [`TrUApi`] implementation, as
//! generated by `#[wasm_env]` on every service trait, so a worker reaches the
//! core in process with no frames in between. The import names and the guest
//! protocol are in [`crate::wasm_abi`].

use core::task::{Context, Poll};
use std::collections::HashMap;
use std::sync::Arc;

use futures::future::BoxFuture;
use futures::stream::{self, BoxStream};
use futures::{FutureExt, StreamExt};
use parity_scale_codec::{DecodeAll, Encode};
use wasmi::{
    Caller, Config, Engine, Extern, Linker, Memory, Module, Store, StoreLimits, StoreLimitsBuilder,
    TypedFunc,
};

use crate::api::TrUApi;
use crate::frame::downgrade_call_error;
use crate::versioned::{FromLatest, IntoLatest, Versioned};
use crate::wasm_abi::{
    ALLOC_EXPORT, EventKind, FINISH_IMPORT, IMPORT_MODULE, LOG_IMPORT, ON_EVENT_EXPORT,
    RELEASE_IMPORT, START_EXPORT,
};
use crate::{CallContext, CallError, Subscription};

/// Instructions a worker may run per entry from the host before it traps.
const FUEL_PER_ENTRY: u64 = 1_000_000_000;

/// Linear memory a worker may grow to.
const MEMORY_LIMIT: usize = 64 * 1024 * 1024;

/// Linear memory export every worker declares.
const MEMORY_EXPORT: &str = "memory";

/// Why a wasm worker could not load or stopped.
#[derive(Debug, derive_more::Display, derive_more::Error)]
pub enum WasmWorkerError {
    /// The bytes are not a valid module, or instantiating it failed.
    #[display("invalid module: {reason}")]
    InvalidModule {
        /// What the engine rejected.
        reason: String,
    },
    /// The module imports a function the host does not provide.
    #[display("unknown import `{module}.{name}`")]
    UnknownImport {
        /// Import module.
        module: String,
        /// Import name.
        name: String,
    },
    /// The module trapped, ran out of fuel, or broke the guest protocol.
    #[display("worker trapped: {reason}")]
    Trapped {
        /// Engine diagnostic.
        reason: String,
    },
    /// The entry point is waiting on nothing the host will ever answer.
    #[display("worker is waiting with no call in flight")]
    Stalled,
    /// The entry point returned an error.
    #[display("worker failed: {message}")]
    Failed {
        /// Error the guest reported.
        message: String,
    },
}

impl From<wasmi::Error> for WasmWorkerError {
    fn from(error: wasmi::Error) -> Self {
        Self::Trapped {
            reason: error.to_string(),
        }
    }
}

struct Event {
    kind: EventKind,
    payload: Vec<u8>,
}

type Method = Arc<dyn Fn(CallContext, Vec<u8>) -> BoxStream<'static, Event> + Send + Sync>;

/// The `truapi` imports a worker can link against, each bound to `H`.
pub struct WasmEnv<H> {
    host: Arc<H>,
    methods: HashMap<&'static str, Method>,
}

impl<H: Send + Sync + 'static> WasmEnv<H> {
    /// An environment with no methods linked.
    pub fn new(host: Arc<H>) -> Self {
        Self {
            host,
            methods: HashMap::new(),
        }
    }

    /// Names of the linked methods.
    pub fn method_names(&self) -> impl Iterator<Item = &'static str> + '_ {
        self.methods.keys().copied()
    }

    /// Link a request method, answering in the caller's protocol version.
    pub fn request<Request, Response, Error, Handler>(
        &mut self,
        name: &'static str,
        handler: Handler,
    ) where
        Request: DecodeAll + Versioned,
        Response: Encode + FromLatest + IntoLatest + Send + 'static,
        Error: Encode + FromLatest + IntoLatest + Send + 'static,
        Handler: Fn(
                Arc<H>,
                CallContext,
                Request,
            ) -> BoxFuture<'static, Result<Response, CallError<Error>>>
            + Send
            + Sync
            + 'static,
    {
        let host = self.host.clone();
        let method: Method = Arc::new(move |cx, payload| {
            let result: BoxFuture<'static, Result<Response, CallError<Error>>> =
                match decode_request::<Request, Error>(&payload) {
                    Ok(request) => {
                        let target = request.version();
                        handler(host.clone(), cx, request)
                            .map(move |result| {
                                result
                                    .map(|response| {
                                        Response::from_latest(response.into_latest(), target)
                                    })
                                    .map_err(|error| downgrade_call_error(error, target))
                            })
                            .boxed()
                    }
                    Err(error) => futures::future::ready(Err(error)).boxed(),
                };
            stream::once(result.map(|result| Event {
                kind: EventKind::Response,
                payload: result.encode(),
            }))
            .boxed()
        });
        self.methods.insert(name, method);
    }

    /// Link a subscription method, streaming in the caller's protocol version.
    pub fn subscription<Request, Item, Error, Handler>(
        &mut self,
        name: &'static str,
        handler: Handler,
    ) where
        Request: DecodeAll + Versioned,
        Item: Encode + FromLatest + IntoLatest + Send + 'static,
        Error: Encode + FromLatest + IntoLatest + Send + 'static,
        Handler: Fn(
                Arc<H>,
                CallContext,
                Request,
            ) -> BoxFuture<'static, Subscription<Item, CallError<Error>>>
            + Send
            + Sync
            + 'static,
    {
        let host = self.host.clone();
        let method: Method =
            Arc::new(
                move |cx, payload| match decode_request::<Request, Error>(&payload) {
                    Ok(request) => {
                        let target = request.version();
                        stream::once(handler(host.clone(), cx, request))
                            .flat_map(move |subscription| subscription_events(subscription, target))
                            .boxed()
                    }
                    Err(error) => {
                        stream::once(futures::future::ready(end_event(Err(error)))).boxed()
                    }
                },
            );
        self.methods.insert(name, method);
    }
}

impl<H: TrUApi + 'static> WasmEnv<H> {
    /// Every method a product may start, bound to `host`.
    pub fn for_product(host: Arc<H>) -> Self {
        let mut env = Self::new(host);
        env.link_system();
        env.link_account();
        env.link_chain();
        env.link_chat();
        env.link_coin_payment();
        env.link_contacts();
        env.link_entropy();
        env.link_game();
        env.link_local_storage();
        env.link_locale();
        env.link_notifications();
        env.link_payment();
        env.link_permissions();
        env.link_pocket();
        env.link_preimage();
        env.link_renderer();
        env.link_resource_allocation();
        env.link_scanner();
        env.link_signing();
        env.link_statement_store();
        env.link_theme();
        env.link_worker();
        env
    }
}

fn decode_request<Request: DecodeAll, Error>(payload: &[u8]) -> Result<Request, CallError<Error>> {
    Request::decode_all(&mut &payload[..]).map_err(|error| CallError::MalformedFrame {
        reason: error.to_string(),
    })
}

fn end_event<Error: Encode>(end: Result<(), CallError<Error>>) -> Event {
    Event {
        kind: EventKind::End,
        payload: end.encode(),
    }
}

/// Items of `subscription`, then exactly one end event.
fn subscription_events<Item, Error>(
    subscription: Subscription<Item, CallError<Error>>,
    target: u8,
) -> impl futures::Stream<Item = Event>
where
    Item: Encode + FromLatest + IntoLatest,
    Error: Encode + FromLatest + IntoLatest,
{
    stream::unfold(Some(subscription), move |subscription| async move {
        let mut subscription = subscription?;
        let event = match subscription.next().await {
            Some(Ok(item)) => Event {
                kind: EventKind::Item,
                payload: Item::from_latest(item.into_latest(), target).encode(),
            },
            Some(Err(error)) => {
                return Some((end_event(Err(downgrade_call_error(error, target))), None));
            }
            None => return Some((end_event::<Error>(Ok(())), None)),
        };
        Some((event, Some(subscription)))
    })
}

enum Command {
    Start {
        handle: u32,
        method: Method,
        request: Vec<u8>,
    },
    Release {
        handle: u32,
    },
}

struct GuestState {
    limits: StoreLimits,
    next_handle: u32,
    commands: Vec<Command>,
    finished: Option<Result<(), String>>,
}

struct Exports {
    memory: Memory,
    start: TypedFunc<(), ()>,
    alloc: TypedFunc<u32, u32>,
    on_event: TypedFunc<(u32, u32, u32, u32), ()>,
}

/// A loaded wasm worker. [`Self::run`] drives it until its entry point
/// returns.
pub struct WasmWorker {
    store: Store<GuestState>,
    exports: Exports,
    calls: HashMap<u32, BoxStream<'static, Event>>,
}

impl WasmWorker {
    /// Instantiate `wasm` against `env`. Fails before running anything when
    /// the module imports a function `env` does not link.
    pub fn new<H: Send + Sync + 'static>(
        env: WasmEnv<H>,
        wasm: &[u8],
    ) -> Result<Self, WasmWorkerError> {
        let mut config = Config::default();
        config.consume_fuel(true);
        let engine = Engine::new(&config);
        let module = Module::new(&engine, wasm).map_err(invalid_module)?;
        let linker = link(&engine, &module, &env.methods)?;

        let state = GuestState {
            limits: StoreLimitsBuilder::new().memory_size(MEMORY_LIMIT).build(),
            next_handle: 0,
            commands: Vec::new(),
            finished: None,
        };
        let mut store = Store::new(&engine, state);
        store.limiter(|state| &mut state.limits);
        let instance = linker
            .instantiate(&mut store, &module)
            .and_then(|instance| instance.start(&mut store))
            .map_err(invalid_module)?;
        let exports = Exports {
            memory: instance
                .get_memory(&store, MEMORY_EXPORT)
                .ok_or_else(|| missing_export(MEMORY_EXPORT))?,
            start: instance
                .get_typed_func(&store, START_EXPORT)
                .map_err(invalid_module)?,
            alloc: instance
                .get_typed_func(&store, ALLOC_EXPORT)
                .map_err(invalid_module)?,
            on_event: instance
                .get_typed_func(&store, ON_EVENT_EXPORT)
                .map_err(invalid_module)?,
        };
        Ok(Self {
            store,
            exports,
            calls: HashMap::new(),
        })
    }

    /// Run the entry point, answering its calls until it returns.
    pub async fn run(mut self) -> Result<(), WasmWorkerError> {
        self.store.set_fuel(FUEL_PER_ENTRY)?;
        self.exports.start.call(&mut self.store, ())?;
        loop {
            self.apply_commands();
            if let Some(outcome) = self.store.data_mut().finished.take() {
                return outcome.map_err(|message| WasmWorkerError::Failed { message });
            }
            if self.calls.is_empty() {
                return Err(WasmWorkerError::Stalled);
            }
            let (handle, event) =
                futures::future::poll_fn(|context| self.poll_calls(context)).await;
            self.deliver(handle, event)?;
        }
    }

    /// The next event of any call in flight, forgetting the call once its
    /// terminal event is out.
    fn poll_calls(&mut self, context: &mut Context<'_>) -> Poll<(u32, Event)> {
        let ready = self.calls.iter_mut().find_map(|(handle, events)| {
            match events.poll_next_unpin(context) {
                Poll::Ready(event) => Some((*handle, event)),
                Poll::Pending => None,
            }
        });
        let Some((handle, event)) = ready else {
            return Poll::Pending;
        };
        let event =
            event.expect("a call is forgotten at its terminal event, before its stream ends");
        if event.kind != EventKind::Item {
            self.calls.remove(&handle);
        }
        Poll::Ready((handle, event))
    }

    fn apply_commands(&mut self) {
        for command in std::mem::take(&mut self.store.data_mut().commands) {
            match command {
                Command::Start {
                    handle,
                    method,
                    request,
                } => {
                    let cx = CallContext::with_request_id(format!("wasm-{handle}"));
                    self.calls.insert(handle, method(cx, request));
                }
                Command::Release { handle } => {
                    self.calls.remove(&handle);
                }
            }
        }
    }

    fn deliver(&mut self, handle: u32, event: Event) -> Result<(), WasmWorkerError> {
        let length = event.payload.len() as u32;
        self.store.set_fuel(FUEL_PER_ENTRY)?;
        let pointer = self.exports.alloc.call(&mut self.store, length)?;
        self.exports
            .memory
            .write(&mut self.store, pointer as usize, &event.payload)
            .map_err(|error| WasmWorkerError::Trapped {
                reason: error.to_string(),
            })?;
        self.exports.on_event.call(
            &mut self.store,
            (handle, event.kind as u32, pointer, length),
        )?;
        Ok(())
    }
}

fn invalid_module(error: wasmi::Error) -> WasmWorkerError {
    WasmWorkerError::InvalidModule {
        reason: error.to_string(),
    }
}

fn missing_export(name: &str) -> WasmWorkerError {
    WasmWorkerError::InvalidModule {
        reason: format!("missing export `{name}`"),
    }
}

/// Link exactly the imports `module` declares.
fn link(
    engine: &Engine,
    module: &Module,
    methods: &HashMap<&'static str, Method>,
) -> Result<Linker<GuestState>, WasmWorkerError> {
    let mut linker = Linker::new(engine);
    for import in module.imports() {
        let unknown = || WasmWorkerError::UnknownImport {
            module: import.module().to_owned(),
            name: import.name().to_owned(),
        };
        if import.module() != IMPORT_MODULE {
            return Err(unknown());
        }
        let linked = match import.name() {
            RELEASE_IMPORT => linker.func_wrap(IMPORT_MODULE, RELEASE_IMPORT, release),
            LOG_IMPORT => linker.func_wrap(IMPORT_MODULE, LOG_IMPORT, log),
            FINISH_IMPORT => linker.func_wrap(IMPORT_MODULE, FINISH_IMPORT, finish),
            name => {
                let (name, method) = methods.get_key_value(name).ok_or_else(unknown)?;
                let method = method.clone();
                linker.func_wrap(
                    IMPORT_MODULE,
                    name,
                    move |caller: Caller<'_, GuestState>, pointer: u32, length: u32| {
                        start_call(caller, method.clone(), pointer, length)
                    },
                )
            }
        };
        linked.map_err(|error| WasmWorkerError::InvalidModule {
            reason: error.to_string(),
        })?;
    }
    Ok(linker)
}

fn start_call(
    mut caller: Caller<'_, GuestState>,
    method: Method,
    pointer: u32,
    length: u32,
) -> Result<u32, wasmi::Error> {
    let request = read_guest(&caller, pointer, length)?;
    let state = caller.data_mut();
    let handle = state.next_handle;
    state.next_handle = handle
        .checked_add(1)
        .ok_or_else(|| wasmi::Error::new("call handles exhausted"))?;
    state.commands.push(Command::Start {
        handle,
        method,
        request,
    });
    Ok(handle)
}

fn release(mut caller: Caller<'_, GuestState>, handle: u32) {
    caller.data_mut().commands.push(Command::Release { handle });
}

fn log(caller: Caller<'_, GuestState>, pointer: u32, length: u32) -> Result<(), wasmi::Error> {
    let line = read_guest_text(&caller, pointer, length)?;
    tracing::info!(target: "truapi::wasm_worker", "{line}");
    Ok(())
}

fn finish(
    mut caller: Caller<'_, GuestState>,
    succeeded: u32,
    pointer: u32,
    length: u32,
) -> Result<(), wasmi::Error> {
    let outcome = if succeeded == 1 {
        Ok(())
    } else {
        Err(read_guest_text(&caller, pointer, length)?)
    };
    caller.data_mut().finished = Some(outcome);
    Ok(())
}

fn read_guest(
    caller: &Caller<'_, GuestState>,
    pointer: u32,
    length: u32,
) -> Result<Vec<u8>, wasmi::Error> {
    let memory = caller
        .get_export(MEMORY_EXPORT)
        .and_then(Extern::into_memory)
        .ok_or_else(|| wasmi::Error::new("worker exports no memory"))?;
    let mut bytes = vec![0; length as usize];
    memory
        .read(caller, pointer as usize, &mut bytes)
        .map_err(|error| wasmi::Error::new(error.to_string()))?;
    Ok(bytes)
}

fn read_guest_text(
    caller: &Caller<'_, GuestState>,
    pointer: u32,
    length: u32,
) -> Result<String, wasmi::Error> {
    String::from_utf8(read_guest(caller, pointer, length)?)
        .map_err(|error| wasmi::Error::new(error.to_string()))
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::generated::wire_table::WIRE_TABLE;
    use crate::runtime::ProductRuntimeHost;
    use crate::test_support::{runtime_config, stub_platform, test_spawner};

    /// Methods a product never starts: the internal permission authorizations
    /// and the render stream the host opens.
    const NOT_PRODUCT_STARTED: [&str; 3] = [
        "permissions_authorize_remote_permission",
        "permissions_authorize_device_permission",
        "renderer_render",
    ];

    #[test]
    fn a_worker_can_import_every_method_a_product_starts_under_its_wire_name() {
        let host = ProductRuntimeHost::new(
            stub_platform(),
            runtime_config("worker.dot"),
            test_spawner(),
        );

        let linked: BTreeSet<_> = WasmEnv::for_product(Arc::new(host))
            .method_names()
            .collect();

        let product_started: BTreeSet<_> = WIRE_TABLE
            .iter()
            .map(|entry| entry.method)
            .filter(|method| !NOT_PRODUCT_STARTED.contains(method))
            .collect();
        assert_eq!(linked, product_started);
    }
}
