//! Rust code generation from extracted API definitions.
//!
//! Emits the server-side wire dispatcher (`dispatcher.rs`) and the
//! discriminant lookup table (`wire_table.rs`). The generated files are
//! intended to be included in the `truapi` crate.

use std::{fs, path::Path};

use anyhow::Result;

use convert_case::{Case, Casing};

use crate::{platform::PlatformDefinition, rustdoc::*};

mod dispatcher;
mod wasm_bridge;
mod wire_table;

pub use dispatcher::generate_dispatcher;
pub use wasm_bridge::generate_wasm_bridge;
pub use wire_table::generate_wire_table;

/// Generates the `truapi` wire dispatcher, wire table, and the `mod.rs`
/// that declares them, into `output_dir`.
pub fn generate(api: &ApiDefinition, output_dir: &Path, schema_hash: &str) -> Result<()> {
	fs::create_dir_all(output_dir)?;
	fs::write(
		output_dir.join("mod.rs"),
		"//! Generated by truapi-codegen. Do not edit.\n\npub mod dispatcher;\npub mod wire_table;\n",
	)?;
	let dispatcher = generate_dispatcher(api)?;
	fs::write(output_dir.join("dispatcher.rs"), dispatcher)?;
	let wire_table = generate_wire_table(api, schema_hash)?;
	fs::write(output_dir.join("wire_table.rs"), wire_table)?;
	Ok(())
}

/// Generates the Rust wasm-bindgen platform bridge source into `output_dir`.
pub fn generate_wasm_bridge_file(
	definition: &PlatformDefinition,
	api: &ApiDefinition,
	output_dir: &Path,
) -> Result<()> {
	fs::create_dir_all(output_dir)?;
	fs::write(output_dir.join("generated_bridge.rs"), generate_wasm_bridge(definition, api)?)?;
	Ok(())
}

/// Trait -> versioned-module mapping. Trait names are PascalCase
/// (`JsonRpc`, `LocalStorage`); module names are snake_case
/// (`jsonrpc`, `local_storage`). The mapping is irregular enough
/// (e.g. `JsonRpc` -> `jsonrpc`) that it is hardcoded.
const TRAIT_MODULE_MAP: &[(&str, &str)] = &[
	("Account", "account"),
	("Chain", "chain"),
	("Chat", "chat"),
	("Contacts", "contacts"),
	("Entropy", "entropy"),
	("JsonRpc", "jsonrpc"),
	("LocalStorage", "local_storage"),
	("Payment", "payment"),
	("Permissions", "permissions"),
	("Preimage", "preimage"),
	("Renderer", "renderer"),
	("ResourceAllocation", "resource_allocation"),
	("Signing", "signing"),
	("StatementStore", "statement_store"),
	("System", "system"),
	("Theme", "theme"),
];

/// Returns the versioned-module name for a trait, falling back to a
/// snake_case conversion of the trait name when no explicit mapping is
/// declared. New traits should be added to [`TRAIT_MODULE_MAP`] so the
/// emission stays deterministic.
fn module_for_trait(trait_name: &str) -> String {
	for (name, module) in TRAIT_MODULE_MAP {
		if *name == trait_name {
			return (*module).to_string();
		}
	}
	snake_case(trait_name)
}

/// Returns the wire-protocol method name for a trait/method pair, used both
/// as the dispatcher's registration key and as the prefix of the action tag
/// (`{wire_method}_{request|response|...}`). The form is
/// `{trait_snake}_{method}` so collisions between sibling traits (e.g.
/// `StatementStore::submit` and `Preimage::submit`) become distinct keys
/// (`statement_store_submit`, `preimage_submit`).
pub fn wire_method_name(trait_name: &str, method_name: &str) -> String {
	format!("{}_{}", snake_case(trait_name), method_name)
}

/// The `SCREAMING_SNAKE_CASE` const name holding a wire method's ids.
/// Routed through [`convert_case::Case::UpperSnake`] so it follows the same
/// casing rules as the TS wire-table emitter (`ts.rs`).
pub fn const_name(wire_method: &str) -> String {
	wire_method.to_case(Case::UpperSnake)
}

/// Const name for a trait/method pair's wire ids. Both the Rust and TS
/// wire-table emitters apply `Case::UpperSnake`, so for the real
/// (single-capital PascalCase trait, snake_case method) surface the two
/// generated const names agree.
#[cfg(test)]
pub fn wire_const_name(trait_name: &str, method_name: &str) -> String {
	const_name(&wire_method_name(trait_name, method_name))
}

/// Convert a PascalCase identifier into snake_case.
fn snake_case(name: &str) -> String {
	let mut out = String::with_capacity(name.len() + 4);
	for (idx, ch) in name.chars().enumerate() {
		if ch.is_ascii_uppercase() {
			if idx != 0 {
				out.push('_');
			}
			out.push(ch.to_ascii_lowercase());
		} else {
			out.push(ch);
		}
	}
	out
}

#[cfg(test)]
mod tests {
	use super::*;

	/// A `V1`-only enum, which is what marks a type as a versioned wrapper.
	fn versioned_wrapper_def(name: &str) -> TypeDef {
		TypeDef {
			name: name.to_string(),
			module_path: Vec::new(),
			generic_params: Vec::new(),
			kind: TypeDefKind::Enum(vec![VariantDef {
				name: "V1".to_string(),
				fields: VariantFields::Unit,
				codec_index: Some(0),
				docs: None,
			}]),
			docs: None,
		}
	}

	fn make_request_method(name: &str, request_id: u8) -> MethodDef {
		MethodDef {
			name: name.to_string(),
			kind: MethodKind::Request,
			params: vec![ParamDef {
				name: "request".to_string(),
				type_ref: TypeRef::Named { name: "ReqWrapper".to_string(), args: vec![] },
			}],
			return_type: ReturnType::Result {
				ok: TypeRef::Named { name: "RespWrapper".to_string(), args: vec![] },
				err: TypeRef::Named {
					name: "CallError".to_string(),
					args: vec![TypeRef::Named { name: "ErrWrapper".to_string(), args: vec![] }],
				},
			},
			wire: WireAttrs { host_initiated: false, internal: false, id: Some(request_id) },
			docs: None,
		}
	}

	fn make_subscription_method(name: &str, start_id: u8) -> MethodDef {
		MethodDef {
			name: name.to_string(),
			kind: MethodKind::Subscription,
			params: vec![],
			return_type: ReturnType::Subscription {
				item: TypeRef::Named { name: "ItemWrapper".to_string(), args: vec![] },
				interrupt: TypeRef::Named {
					name: "CallError".to_string(),
					args: vec![TypeRef::Named { name: "GenericError".to_string(), args: vec![] }],
				},
			},
			wire: WireAttrs { host_initiated: false, internal: false, id: Some(start_id) },
			docs: None,
		}
	}

	fn versioned_test_type(name: &str) -> TypeDef {
		TypeDef {
			name: name.to_string(),
			module_path: Vec::new(),
			generic_params: Vec::new(),
			kind: TypeDefKind::Enum(vec![VariantDef {
				name: "V1".to_string(),
				fields: VariantFields::Unnamed(vec![TypeRef::Named {
					name: format!("V01{name}"),
					args: vec![],
				}]),
				docs: None,
				codec_index: None,
			}]),
			docs: None,
		}
	}

	fn versioned_request_test_types() -> Vec<TypeDef> {
		["ReqWrapper", "RespWrapper", "ErrWrapper"]
			.into_iter()
			.map(versioned_test_type)
			.collect()
	}

	fn parse_entries(src: &str) -> Vec<(u8, String)> {
		// Each method's id is emitted as a named const, e.g.
		//   pub const PREIMAGE_SUBMIT: MethodIds = MethodIds {
		//       trait_id: 203,
		//       method_id: 68,
		//   };
		// Reconstruct the `(method_id, method_name)` pairs the assertions use.
		let mut out = Vec::new();
		let mut lines = src.lines();
		while let Some(line) = lines.next() {
			let Some(rest) = line.trim().strip_prefix("pub const ") else {
				continue;
			};
			let Some(colon) = rest.find(':') else {
				continue;
			};
			// Skip non-id consts (e.g. `WIRE_TABLE: &[WireEntry]`).
			if !rest.contains("MethodIds") {
				continue;
			}
			let method = rest[..colon].trim().to_ascii_lowercase();

			let mut ids: std::collections::BTreeMap<&str, u8> = std::collections::BTreeMap::new();
			for inner in lines.by_ref() {
				let t = inner.trim();
				if t.starts_with("};") {
					break;
				}
				if let Some((field, val)) = t.split_once(':') {
					let id = val.trim().trim_end_matches(',').parse::<u8>().unwrap();
					ids.insert(field.trim(), id);
				}
			}

			out.push((ids["method_id"], method));
		}
		out
	}

	/// A single subscription method reserves exactly one wire id, same as a
	/// request method: the leg is named by `message_type`, not the address.
	#[test]
	fn wire_table_subscribe_method_reserves_one_id() {
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Account".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(193),
				methods: vec![make_subscription_method("connection_status_subscribe", 18)],
				docs: None,
			}],
			public_trait_order: vec!["Account".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};

		let src = generate_wire_table(&api, "testhash").expect("generate_wire_table");
		let entries = parse_entries(&src);
		assert_eq!(entries, vec![(18, "account_connection_status_subscribe".into())],);
	}

	/// Two traits each declaring a method named `submit` must produce two
	/// distinct, non-colliding wire method keys; the emitter prefixes by
	/// the snake_case trait name (e.g. `statement_store_submit` /
	/// `preimage_submit`).
	#[test]
	fn collision_safe_when_two_traits_share_method_name() {
		let mut statement_store_submit = make_request_method("submit", 62);
		statement_store_submit.params[0].type_ref =
			TypeRef::Named { name: "StatementStoreSubmitRequest".to_string(), args: vec![] };
		let mut preimage_submit = make_request_method("submit", 68);
		preimage_submit.params[0].type_ref =
			TypeRef::Named { name: "PreimageSubmitRequest".to_string(), args: vec![] };
		let api = ApiDefinition {
			traits: vec![
				TraitDef {
					name: "StatementStore".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(193),
					methods: vec![statement_store_submit],
					docs: None,
				},
				TraitDef {
					name: "Preimage".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(194),
					methods: vec![preimage_submit],
					docs: None,
				},
			],
			public_trait_order: vec!["StatementStore".to_string(), "Preimage".to_string()],
			types: {
				let mut types = versioned_request_test_types();
				types.push(versioned_test_type("StatementStoreSubmitRequest"));
				types.push(versioned_test_type("StatementStoreSubmitVersion"));
				types.push(versioned_test_type("PreimageSubmitRequest"));
				types.push(versioned_test_type("PreimageSubmitVersion"));
				types
			},
			framework_types: Vec::new(),
		};

		let dispatcher = generate_dispatcher(&api).expect("dispatcher");
		assert!(
			dispatcher.contains("wire_table::STATEMENT_STORE_SUBMIT"),
			"dispatcher missing prefixed StatementStore const:\n{dispatcher}"
		);
		assert!(
			dispatcher.contains("wire_table::PREIMAGE_SUBMIT"),
			"dispatcher missing prefixed Preimage const:\n{dispatcher}"
		);

		let table = generate_wire_table(&api, "testhash").expect("wire_table");
		let entries = parse_entries(&table);
		assert!(
			entries.iter().any(|(_, tag)| tag == "statement_store_submit"),
			"wire_table missing prefixed StatementStore tag:\n{table}"
		);
		assert!(
			entries.iter().any(|(_, tag)| tag == "preimage_submit"),
			"wire_table missing prefixed Preimage tag:\n{table}"
		);
	}

	/// If a future change ever produces the same wire method key from two
	/// different (trait, method) pairs, both emitters must fail loudly
	/// rather than silently overwrite a handler.
	#[test]
	fn wire_table_rejects_method_name_collision() {
		// `Foo::bar_baz` and `FooBar::baz` both snake-case to
		// `foo_bar_baz`. The emitter must reject the pair.
		let api = ApiDefinition {
			traits: vec![
				TraitDef {
					name: "Foo".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(195),
					methods: vec![make_request_method("bar_baz", 10)],
					docs: None,
				},
				TraitDef {
					name: "FooBar".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(196),
					methods: vec![make_request_method("baz", 12)],
					docs: None,
				},
			],
			public_trait_order: vec!["Foo".to_string(), "FooBar".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};
		let err = generate_wire_table(&api, "testhash")
			.expect_err("duplicate wire method name must error");
		let msg = format!("{err}");
		assert!(
			msg.contains("wire method name `foo_bar_baz` reused"),
			"unexpected error message: {msg}",
		);

		let err = generate_dispatcher(&api).expect_err("duplicate wire method name must error");
		let msg = format!("{err}");
		assert!(
			msg.contains("Wire method name `foo_bar_baz` registered twice"),
			"unexpected dispatcher error message: {msg}",
		);
	}

	/// Emission must be deterministic: running the codegen twice on the
	/// same API produces byte-identical output.
	#[test]
	fn idempotent_emission() {
		let mut method = make_request_method("request_device_permission", 8);
		method.params[0].type_ref =
			TypeRef::Named { name: "RequestDevicePermissionRequest".to_string(), args: vec![] };
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Permissions".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(197),
				methods: vec![method],
				docs: None,
			}],
			public_trait_order: vec!["Permissions".to_string()],
			types: {
				let mut types = versioned_request_test_types();
				types.push(versioned_test_type("RequestDevicePermissionRequest"));
				types.push(versioned_test_type("RequestDevicePermissionVersion"));
				types
			},
			framework_types: Vec::new(),
		};

		let dispatcher_a = generate_dispatcher(&api).expect("dispatcher a");
		let dispatcher_b = generate_dispatcher(&api).expect("dispatcher b");
		assert_eq!(dispatcher_a, dispatcher_b);

		let table_a = generate_wire_table(&api, "testhash").expect("wire_table a");
		let table_b = generate_wire_table(&api, "testhash").expect("wire_table b");
		assert_eq!(table_a, table_b);
	}

	/// Every method, request or subscription, gets exactly one wire id.
	/// The emitter must reject collisions between them.
	#[test]
	fn wire_table_rejects_collisions() {
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Permissions".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(197),
				methods: vec![make_request_method("alpha", 10), make_request_method("beta", 10)],
				docs: None,
			}],
			public_trait_order: vec!["Permissions".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};
		let err = generate_wire_table(&api, "testhash").expect_err("duplicate ids must error");
		let msg = format!("{err}");
		assert!(msg.contains("wire id (197, 10) reused"), "unexpected error message: {msg}",);
	}

	/// Method ids are scoped per trait: two traits may both use method id 0,
	/// and the emitted consts carry each trait's discriminant.
	#[test]
	fn wire_table_allows_same_method_id_in_different_traits() {
		let api = ApiDefinition {
			traits: vec![
				TraitDef {
					name: "StatementStore".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(205),
					methods: vec![make_request_method("submit", 0)],
					docs: None,
				},
				TraitDef {
					name: "Preimage".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(202),
					methods: vec![make_request_method("submit", 0)],
					docs: None,
				},
			],
			public_trait_order: vec!["StatementStore".to_string(), "Preimage".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};

		let table = generate_wire_table(&api, "testhash").expect("wire_table");
		assert!(table.contains("trait_id: 205,"), "missing trait id 13:\n{table}");
		assert!(table.contains("trait_id: 202,"), "missing trait id 10:\n{table}");
	}

	/// Two traits must not share a wire trait id.
	#[test]
	fn wire_table_rejects_duplicate_trait_ids() {
		let api = ApiDefinition {
			traits: vec![
				TraitDef {
					name: "StatementStore".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(196),
					methods: vec![make_request_method("submit", 0)],
					docs: None,
				},
				TraitDef {
					name: "Preimage".to_string(),
					module_path: Vec::new(),
					wire_trait_id: Some(196),
					methods: vec![make_request_method("submit", 0)],
					docs: None,
				},
			],
			public_trait_order: vec!["StatementStore".to_string(), "Preimage".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};

		let err =
			generate_wire_table(&api, "testhash").expect_err("duplicate trait ids must error");
		let msg = format!("{err}");
		assert!(msg.contains("wire trait id 196 reused"), "unexpected error message: {msg}",);
	}

	/// A trait missing `#[wire_trait(id = N)]` must fail emission.
	#[test]
	fn wire_table_missing_trait_id_errors() {
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Permissions".to_string(),
				module_path: Vec::new(),
				wire_trait_id: None,
				methods: vec![make_request_method("request_device_permission", 8)],
				docs: None,
			}],
			public_trait_order: vec!["Permissions".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};

		let err = generate_wire_table(&api, "testhash").expect_err("missing trait id must error");
		let msg = format!("{err}");
		assert!(msg.contains("missing #[wire_trait(id = N)]"), "unexpected error message: {msg}",);
	}

	/// Trait 255 is reserved for protocol errors, so no API trait may declare
	/// it. Codec 2 addresses a frame by `(trait, method)`, which moves the
	/// reservation from a single id to a whole trait: a method id of 255 is now
	/// a perfectly ordinary address, and the only way to reach the reserved
	/// `(255, 255)` is through a trait that owns 255. This replaces main's
	/// method-level test, which asserted the eight method-id positions could
	/// not be 255 - true under one byte, wrong under two.
	#[test]
	fn wire_table_rejects_the_reserved_protocol_error_trait_id() {
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Example".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(crate::RESERVED_PROTOCOL_ERROR_TRAIT_ID),
				methods: vec![make_request_method("submit", 0)],
				docs: None,
			}],
			public_trait_order: vec!["Example".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};

		let err = generate_wire_table(&api, "testhash").expect_err("trait id 255 must be refused");
		let msg = err.to_string();
		assert!(
			msg.contains("wire trait id 255 reused") &&
				msg.contains("reserved for protocol errors"),
			"unexpected error message: {msg}",
		);
	}

	/// The other half of the reservation: it must not have grown. A method id of
	/// 255 inside an ordinary trait is a legal address under a two-byte
	/// envelope, and refusing it would silently cost every trait its last slot.
	#[test]
	fn wire_table_allows_method_id_255_outside_the_reserved_trait() {
		let method = make_request_method("explicit_request", 255);
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Example".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(1),
				methods: vec![method],
				docs: None,
			}],
			public_trait_order: vec!["Example".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};

		generate_wire_table(&api, "testhash").expect("(1, 255) is an ordinary address");
	}

	/// Pin `wire_const_name`'s `convert_case::Case::UpperSnake` behavior:
	/// digits split off (`v2` -> `V_2`) and acronyms split (`HTTPServer`
	/// snake-cases to `h_t_t_p_server`, then upper-snakes to
	/// `H_T_T_P_SERVER`). Real traits/methods avoid both, so the committed
	/// output is unaffected; the pin guards future drift.
	#[test]
	fn wire_const_name_pins_digits_and_acronyms() {
		assert_eq!(wire_const_name("Preimage", "submit"), "PREIMAGE_SUBMIT");
		assert_eq!(wire_const_name("Signing", "sign_v2"), "SIGNING_SIGN_V_2");
		assert_eq!(wire_const_name("HTTPServer", "serve"), "H_T_T_P_SERVER_SERVE");
		assert_eq!(
			wire_const_name("StatementStore", "create_proof"),
			"STATEMENT_STORE_CREATE_PROOF"
		);
	}

	#[test]
	fn module_for_trait_maps_irregular_names() {
		assert_eq!(module_for_trait("JsonRpc"), "jsonrpc");
		assert_eq!(module_for_trait("LocalStorage"), "local_storage");
		assert_eq!(module_for_trait("ResourceAllocation"), "resource_allocation");
		assert_eq!(module_for_trait("Account"), "account");
	}

	/// A method missing the mandatory `#[wire(id = N)]` annotation must fail
	/// emission, not silently default to 0 — true for both request and
	/// subscription kinds, which now share the same single-id path.
	#[test]
	fn wire_table_missing_id_errors() {
		let mut method = make_request_method("alpha", 10);
		method.wire.id = None;
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Permissions".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(197),
				methods: vec![method],
				docs: None,
			}],
			public_trait_order: vec!["Permissions".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};
		let err =
			generate_wire_table(&api, "testhash").expect_err("missing id annotation must error");
		let msg = format!("{err}");
		assert!(msg.contains("missing #[wire(id"), "unexpected error message: {msg}",);
	}

	/// The dispatcher expects each method to take exactly one versioned
	/// wrapper parameter (plus `&self` and `&CallContext`, which are
	/// elided from `params`). A method with two params errors out.
	#[test]
	fn dispatcher_multi_param_method_errors() {
		let mut method = make_request_method("alpha", 10);
		method.params.push(ParamDef {
			name: "extra".to_string(),
			type_ref: TypeRef::Named { name: "ExtraWrapper".to_string(), args: vec![] },
		});
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Permissions".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(197),
				methods: vec![method],
				docs: None,
			}],
			public_trait_order: vec!["Permissions".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};
		let err = generate_dispatcher(&api).expect_err("two-param method must error");
		let msg = format!("{err}");
		assert!(
			msg.contains("expected at most one request parameter"),
			"unexpected error message: {msg}",
		);
	}

	/// The response wrapper extraction expects a `TypeRef::Named` with no
	/// generic args. Anything else (primitives, tuples, generics) errors.
	#[test]
	fn dispatcher_non_named_root_response_errors() {
		let mut method = make_request_method("alpha", 10);
		method.return_type = ReturnType::Result {
			ok: TypeRef::Primitive("u32".to_string()),
			err: TypeRef::Named {
				name: "CallError".to_string(),
				args: vec![TypeRef::Named { name: "ErrWrapper".to_string(), args: vec![] }],
			},
		};
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Permissions".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(197),
				methods: vec![method],
				docs: None,
			}],
			public_trait_order: vec!["Permissions".to_string()],
			// `ReqWrapper` must be a real versioned wrapper here: otherwise the
			// request-parameter check fires first and this stops exercising the
			// response check it is named for.
			types: vec![versioned_wrapper_def("ReqWrapper"), versioned_wrapper_def("ErrWrapper")],
			framework_types: Vec::new(),
		};
		let err = generate_dispatcher(&api).expect_err("primitive response must error");
		let msg = format!("{err}");
		assert!(
			msg.contains("response is not a versioned wrapper"),
			"unexpected error message: {msg}",
		);
	}

	/// A request parameter that is not a versioned wrapper has no wire payload
	/// shape, and must fail codegen rather than emit a call without it.
	#[test]
	fn dispatcher_non_versioned_request_parameter_errors() {
		let api = ApiDefinition {
			traits: vec![TraitDef {
				name: "Permissions".to_string(),
				module_path: Vec::new(),
				wire_trait_id: Some(197),
				methods: vec![make_request_method("alpha", 10)],
				docs: None,
			}],
			public_trait_order: vec!["Permissions".to_string()],
			types: vec![],
			framework_types: Vec::new(),
		};
		let err = generate_dispatcher(&api).expect_err("a raw request parameter must error");
		assert!(
			format!("{err}").contains("request parameter is not a versioned wrapper"),
			"unexpected error message: {err}",
		);
	}
}
