//! Cross-language parity check: the Rust `WIRE_TABLE` and the TS
//! `wire-table.ts` must list the exact same `(method, trait_id, method_id)`
//! tuples in the same order. A drift here means a product built against one
//! side will fail to decode frames produced by the other.
//!
//! Both files are auto-generated text artifacts of `truapi-codegen`; the
//! parser is a small line scanner so the test runs as part of `cargo test`
//! without any node/bun dependency.
//!
//! The TS file lives under `js/packages/truapi/src/generated/wire-table.ts`
//! and is `.gitignore`d (regenerated by `scripts/codegen.sh`). When the
//! generated file is absent, the test logs a skip notice and passes, unless
//! `TRUAPI_REQUIRE_GENERATED_TS=1` is set (CI sets it after running codegen),
//! in which case the missing file is a hard failure.

use std::path::PathBuf;

const RUST_TABLE: &str = include_str!("../src/generated/wire_table.rs");

#[derive(Debug, PartialEq, Eq)]
struct Row {
	method: String,
	trait_id: u8,
	method_id: u8,
}

/// Parse a wire id. A malformed id is a hard failure, never a silent `0`: a
/// defensive fallback here would let a symmetric codegen-format change collapse
/// both tables to `0`s and pass the parity check while real drift slipped by.
fn parse_id(raw: &str, method: &str) -> u8 {
	raw.trim_end_matches(',')
		.trim()
		.parse()
		.unwrap_or_else(|_| panic!("unparseable wire id for `{method}`: {raw:?}"))
}

fn parse_rust(src: &str) -> Vec<Row> {
	// The Rust codegen emits one named `pub const FOO_BAR: MethodIds = { ... }`
	// per method. The const name is `SCREAMING_SNAKE_CASE` of the method name;
	// we lowercase it to match the TS const names. This mirrors `parse_ts`
	// below.
	let mut out = Vec::new();
	let mut iter = src.lines();
	while let Some(line) = iter.next() {
		let trimmed = line.trim();
		let Some(rest) = trimmed.strip_prefix("pub const ") else {
			continue;
		};
		let Some(colon) = rest.find(':') else {
			continue;
		};
		// Skip non-id consts (e.g. `WIRE_TABLE: &[WireEntry]`).
		if !rest.contains("MethodIds") {
			continue;
		}
		let method = rest[..colon].trim().to_ascii_lowercase();
		let mut trait_id = None;
		let mut method_id = None;
		for inner in iter.by_ref() {
			let t = inner.trim();
			if t.starts_with("};") {
				break;
			}
			if let Some(rest) = t.strip_prefix("trait_id: ") {
				trait_id = Some(parse_id(rest, &method));
			}
			if let Some(rest) = t.strip_prefix("method_id: ") {
				method_id = Some(parse_id(rest, &method));
			}
		}
		out.push(Row {
			trait_id: trait_id
				.unwrap_or_else(|| panic!("missing trait_id for `{method}` in Rust table")),
			method_id: method_id
				.unwrap_or_else(|| panic!("missing method_id for `{method}` in Rust table")),
			method,
		});
	}
	out
}

fn parse_ts(src: &str) -> Vec<Row> {
	// The TS codegen emits one named `export const FOO_BAR = { ... }` per
	// method. The const name is `SCREAMING_SNAKE_CASE` of the method name;
	// we lowercase it to match the Rust `method:` strings.
	let mut out = Vec::new();
	let mut iter = src.lines().peekable();
	while let Some(line) = iter.next() {
		let trimmed = line.trim();
		let Some(rest) = trimmed.strip_prefix("export const ") else {
			continue;
		};
		let Some(name_end) = rest.find(|c: char| !(c.is_ascii_alphanumeric() || c == '_')) else {
			continue;
		};
		let method = rest[..name_end].to_ascii_lowercase();
		let mut trait_id = None;
		let mut method_id = None;
		for inner in iter.by_ref() {
			let t = inner.trim();
			if let Some(rest) = t.strip_prefix("trait: ") {
				trait_id = Some(parse_id(rest, &method));
			}
			if let Some(rest) = t.strip_prefix("method: ") {
				method_id = Some(parse_id(rest, &method));
			}
			if t.starts_with("} as const") || t == "}" {
				out.push(Row {
					trait_id: trait_id
						.unwrap_or_else(|| panic!("missing trait id for `{method}` in TS table")),
					method_id: method_id
						.unwrap_or_else(|| panic!("missing method id for `{method}` in TS table")),
					method,
				});
				break;
			}
		}
	}
	out
}

#[test]
fn rust_and_ts_wire_tables_agree() {
	let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
	let ts_path = manifest
		.join("../../../js/packages/truapi/src/generated/wire-table.ts")
		.canonicalize();

	let require_ts = std::env::var("TRUAPI_REQUIRE_GENERATED_TS").as_deref() == Ok("1");

	let ts_path = match ts_path {
		Ok(p) => p,
		Err(_) => {
			assert!(
				!require_ts,
				"TRUAPI_REQUIRE_GENERATED_TS=1 but wire-table.ts is missing; run scripts/codegen.sh"
			);
			eprintln!(
				"skipping wire-table parity check: TS wire-table.ts is not present \
                 (run scripts/codegen.sh to generate it)"
			);
			return;
		},
	};

	let ts_src = match std::fs::read_to_string(&ts_path) {
		Ok(s) => s,
		Err(_) => {
			assert!(
				!require_ts,
				"TRUAPI_REQUIRE_GENERATED_TS=1 but {} is unreadable",
				ts_path.display()
			);
			eprintln!("skipping wire-table parity check: could not read {}", ts_path.display());
			return;
		},
	};

	let rust_rows = parse_rust(RUST_TABLE);
	let ts_rows = parse_ts(&ts_src);
	// Lower bound pinned to the known table size so a parser/codegen regression
	// that quietly shrinks both tables in lockstep cannot pass: `assert_eq!`
	// alone is satisfied by two equal-but-truncated tables.
	const MIN_EXPECTED_ROWS: usize = 60;
	assert!(
		rust_rows.len() >= MIN_EXPECTED_ROWS,
		"rust parser produced {} entries (expected >= {MIN_EXPECTED_ROWS}); \
         wire_table.rs format may have changed",
		rust_rows.len()
	);
	assert!(
		ts_rows.len() >= MIN_EXPECTED_ROWS,
		"ts parser produced {} entries (expected >= {MIN_EXPECTED_ROWS}); \
         wire-table.ts format may have changed",
		ts_rows.len()
	);
	assert_eq!(
		rust_rows, ts_rows,
		"Rust WIRE_TABLE and TS wire-table.ts diverged. Regenerate both via \
         `scripts/codegen.sh` so the codegen pipeline produces them in lockstep.",
	);
}

/// `transport.ts` hand-mirrors the reserved protocol-error address, which the
/// generated table does not carry. It is hand-written on the TS side, so
/// nothing but this test stops it drifting - and a drift means one language
/// answers frames the other refuses.
#[test]
fn transport_ts_mirrors_the_rust_wire_constants() {
	let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
		.join("../../../js/packages/truapi/src/transport.ts");
	let src = std::fs::read_to_string(&path)
		.unwrap_or_else(|err| panic!("read {}: {err}", path.display()));

	for (name, expected) in [("PROTOCOL_ERROR_TRAIT_ID", 255), ("PROTOCOL_ERROR_METHOD_ID", 255)] {
		let needle = format!("export const {name} = ");
		let start = src.find(&needle).unwrap_or_else(|| panic!("transport.ts must export {name}"));
		let rest = &src[start + needle.len()..];
		let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
		let actual: u8 =
			digits.parse().unwrap_or_else(|err| panic!("{name} is not a u8 literal: {err}"));
		assert_eq!(actual, expected, "transport.ts {name} = {actual} but Rust says {expected}",);
	}
}
