// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(truapi_providerFFI)
import truapi_providerFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_truapi_provider_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_truapi_provider_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTruapiProviderInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A live JSON-RPC connection: a raw string pipe to one chain.
 */
public protocol ChainConnectionProtocol: AnyObject, Sendable {
    
    /**
     * Close the connection; the listener's `on_closed` fires once the stream
     * ends.
     *
     * NOT named `close`: uniffi's generated Kotlin object already implements
     * `AutoCloseable.close()` for handle disposal, so an exported `close`
     * produces two methods with the same signature and the module does not
     * compile ("Conflicting overloads").
     */
    func disconnect() 
    
    /**
     * Queue a JSON-RPC request string.
     */
    func send(request: String) 
    
}
/**
 * A live JSON-RPC connection: a raw string pipe to one chain.
 */
open class ChainConnection: ChainConnectionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_truapi_provider_fn_clone_chainconnection(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_truapi_provider_fn_free_chainconnection(handle, $0) }
    }

    

    
    /**
     * Close the connection; the listener's `on_closed` fires once the stream
     * ends.
     *
     * NOT named `close`: uniffi's generated Kotlin object already implements
     * `AutoCloseable.close()` for handle disposal, so an exported `close`
     * produces two methods with the same signature and the module does not
     * compile ("Conflicting overloads").
     */
open func disconnect()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainconnection_disconnect(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
    /**
     * Queue a JSON-RPC request string.
     */
open func send(request: String)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainconnection_send(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(request),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainConnection: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ChainConnection

    public static func lift(_ handle: UInt64) throws -> ChainConnection {
        return ChainConnection(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ChainConnection) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainConnection {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ChainConnection, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainConnection_lift(_ handle: UInt64) throws -> ChainConnection {
    return try FfiConverterTypeChainConnection.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainConnection_lower(_ value: ChainConnection) -> UInt64 {
    return FfiConverterTypeChainConnection.lower(value)
}






/**
 * Sink for a chain's lifecycle, implemented on the foreign side.
 */
public protocol ChainLifecycleListener: AnyObject, Sendable {
    
    /**
     * Called with the current state, then once per change.
     */
    func onLifecycle(state: ChainLifecycle) throws 
    
    /**
     * Called once the watch has ended: stopped, the chain no longer running,
     * or `on_lifecycle` having failed.
     */
    func onEnded() throws 
    
}
/**
 * Sink for a chain's lifecycle, implemented on the foreign side.
 */
open class ChainLifecycleListenerImpl: ChainLifecycleListener, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_truapi_provider_fn_clone_chainlifecyclelistener(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_truapi_provider_fn_free_chainlifecyclelistener(handle, $0) }
    }

    

    
    /**
     * Called with the current state, then once per change.
     */
open func onLifecycle(state: ChainLifecycle)throws   {try rustCallWithError(FfiConverterTypeChainProviderError_lift) {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainlifecyclelistener_on_lifecycle(
            self.uniffiCloneHandle(),
        FfiConverterTypeChainLifecycle_lower(state),uniffiCallStatus
    )
}
}
    
    /**
     * Called once the watch has ended: stopped, the chain no longer running,
     * or `on_lifecycle` having failed.
     */
open func onEnded()throws   {try rustCallWithError(FfiConverterTypeChainProviderError_lift) {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainlifecyclelistener_on_ended(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceChainLifecycleListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceChainLifecycleListener = UniffiVTableCallbackInterfaceChainLifecycleListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeChainLifecycleListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ChainLifecycleListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeChainLifecycleListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ChainLifecycleListener: handle missing in uniffiClone")
            }
        },
        onLifecycle: { (
            uniffiHandle: UInt64,
            state: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeChainLifecycleListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onLifecycle(
                     state: try FfiConverterTypeChainLifecycle_lift(state)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeChainProviderError_lower
            )
        },
        onEnded: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeChainLifecycleListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onEnded(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeChainProviderError_lower
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceChainLifecycleListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceChainLifecycleListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitChainLifecycleListener() {
    uniffi_truapi_provider_fn_init_callback_vtable_chainlifecyclelistener(UniffiCallbackInterfaceChainLifecycleListener.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainLifecycleListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<ChainLifecycleListener>()

    typealias FfiType = UInt64
    typealias SwiftType = ChainLifecycleListener

    public static func lift(_ handle: UInt64) throws -> ChainLifecycleListener {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return ChainLifecycleListenerImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: ChainLifecycleListener) -> UInt64 {
         if let rustImpl = value as? ChainLifecycleListenerImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainLifecycleListener {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ChainLifecycleListener, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainLifecycleListener_lift(_ handle: UInt64) throws -> ChainLifecycleListener {
    return try FfiConverterTypeChainLifecycleListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainLifecycleListener_lower(_ value: ChainLifecycleListener) -> UInt64 {
    return FfiConverterTypeChainLifecycleListener.lower(value)
}






/**
 * Sink for a connection's inbound JSON-RPC responses and notifications,
 * implemented on the foreign (Swift) side.
 */
public protocol ChainMessageListener: AnyObject, Sendable {
    
    /**
     * Called for each JSON-RPC response or notification string.
     */
    func onMessage(message: String) throws 
    
    /**
     * Called once the connection has closed, whichever way it ended.
     */
    func onClosed(reason: ChainCloseReason) throws 
    
}
/**
 * Sink for a connection's inbound JSON-RPC responses and notifications,
 * implemented on the foreign (Swift) side.
 */
open class ChainMessageListenerImpl: ChainMessageListener, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_truapi_provider_fn_clone_chainmessagelistener(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_truapi_provider_fn_free_chainmessagelistener(handle, $0) }
    }

    

    
    /**
     * Called for each JSON-RPC response or notification string.
     */
open func onMessage(message: String)throws   {try rustCallWithError(FfiConverterTypeChainProviderError_lift) {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainmessagelistener_on_message(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(message),uniffiCallStatus
    )
}
}
    
    /**
     * Called once the connection has closed, whichever way it ended.
     */
open func onClosed(reason: ChainCloseReason)throws   {try rustCallWithError(FfiConverterTypeChainProviderError_lift) {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainmessagelistener_on_closed(
            self.uniffiCloneHandle(),
        FfiConverterTypeChainCloseReason_lower(reason),uniffiCallStatus
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceChainMessageListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceChainMessageListener = UniffiVTableCallbackInterfaceChainMessageListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeChainMessageListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ChainMessageListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeChainMessageListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ChainMessageListener: handle missing in uniffiClone")
            }
        },
        onMessage: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeChainMessageListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onMessage(
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeChainProviderError_lower
            )
        },
        onClosed: { (
            uniffiHandle: UInt64,
            reason: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeChainMessageListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onClosed(
                     reason: try FfiConverterTypeChainCloseReason_lift(reason)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeChainProviderError_lower
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceChainMessageListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceChainMessageListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitChainMessageListener() {
    uniffi_truapi_provider_fn_init_callback_vtable_chainmessagelistener(UniffiCallbackInterfaceChainMessageListener.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainMessageListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<ChainMessageListener>()

    typealias FfiType = UInt64
    typealias SwiftType = ChainMessageListener

    public static func lift(_ handle: UInt64) throws -> ChainMessageListener {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return ChainMessageListenerImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: ChainMessageListener) -> UInt64 {
         if let rustImpl = value as? ChainMessageListenerImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainMessageListener {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ChainMessageListener, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainMessageListener_lift(_ handle: UInt64) throws -> ChainMessageListener {
    return try FfiConverterTypeChainMessageListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainMessageListener_lower(_ value: ChainMessageListener) -> UInt64 {
    return FfiConverterTypeChainMessageListener.lower(value)
}






/**
 * Embedded-smoldot chain provider. Construct one per process and share it;
 * every connection runs on the single embedded light client.
 */
public protocol ChainProviderProtocol: AnyObject, Sendable {
    
    /**
     * Open a connection to the chain identified by `genesis_hash` (32 bytes).
     * The network is resolved from the catalog; responses are delivered to
     * `listener` until the connection closes.
     */
    func connect(genesisHash: Data, listener: ChainMessageListener) throws  -> ChainConnection
    
    /**
     * Read the stored blob for `genesis_hash` into this provider, so the next
     * [`connect`](Self::connect) to that chain resumes from finalized state
     * instead of syncing from the chain-spec checkpoint. Answers whether a
     * blob is now in hand.
     *
     * Fails when the provider was built through [`new`](Self::new), which has
     * nowhere to keep blobs. A chain that never warms up looks exactly like
     * one with nothing stored yet, so the missing store is reported rather
     * than swallowed: build with [`with_storage`](Self::with_storage).
     *
     * Call it before `connect`, and never from a listener callback. `connect`
     * blocks its calling thread, so a store awaited underneath it would
     * deadlock. The store is read at most once per chain: smoldot keys a chain
     * by its genesis hash, so only the first connect to a chain can consume a
     * blob.
     */
    func loadDatabase(genesisHash: Data) async throws  -> Bool
    
    /**
     * Snapshot the finalized state for `genesis_hash` and hand it to storage.
     * Answers whether a blob was stored, and fails when the provider was built
     * without one, for the same reason [`load_database`](Self::load_database) does.
     *
     * This is a full round trip against the light client rather than a write,
     * so call it while the app is alive. From a backgrounding callback treat
     * it as best effort: nothing keeps a backgrounded app scheduled long
     * enough to guarantee it finishes. A chain that has finalized nothing yet
     * stores nothing and answers `false`, rather than replacing a good blob
     * with one smoldot would discard.
     */
    func saveDatabase(genesisHash: Data) async throws  -> Bool
    
    /**
     * Watch what the light client is doing on the chain identified by
     * `genesis_hash` (32 bytes). `listener` receives the current state, then
     * every change, until the watch is stopped or the chain stops running.
     *
     * Fails when nothing is connected to the chain, so connect first.
     */
    func watchLifecycle(genesisHash: Data, listener: ChainLifecycleListener) throws  -> LifecycleWatch
    
}
/**
 * Embedded-smoldot chain provider. Construct one per process and share it;
 * every connection runs on the single embedded light client.
 */
open class ChainProvider: ChainProviderProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_truapi_provider_fn_clone_chainprovider(self.handle, $0) }
    }
    /**
     * Create a provider backed by the bundled network catalog, with nowhere
     * to keep finalized state: every chain syncs from the chain-spec
     * checkpoint on every run, and [`load_database`](Self::load_database) and
     * [`save_database`](Self::save_database) fail rather than quietly doing nothing.
     *
     * Use [`with_storage`](Self::with_storage) to resume from state the host
     * keeps for it.
     */
public convenience init() {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_constructor_chainprovider_new(uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_truapi_provider_fn_free_chainprovider(handle, $0) }
    }

    
    /**
     * Create a provider that reads and writes database blobs through `client`.
     *
     * The crate stores nothing itself, so a provider built with
     * [`new`](Self::new) syncs every chain from the chain-spec checkpoint on
     * every run. The host owns where the bytes live and therefore whether they
     * are backed up, encrypted, or excluded from cloud sync.
     */
public static func withStorage(client: StorageClient) -> ChainProvider  {
    return try!  FfiConverterTypeChainProvider_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_constructor_chainprovider_with_storage(
        FfiConverterTypeStorageClient_lower(client),uniffiCallStatus
    )
})
}
    

    
    /**
     * Open a connection to the chain identified by `genesis_hash` (32 bytes).
     * The network is resolved from the catalog; responses are delivered to
     * `listener` until the connection closes.
     */
open func connect(genesisHash: Data, listener: ChainMessageListener)throws  -> ChainConnection  {
    return try  FfiConverterTypeChainConnection_lift(try rustCallWithError(FfiConverterTypeChainProviderError_lift) {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainprovider_connect(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(genesisHash),
        FfiConverterTypeChainMessageListener_lower(listener),uniffiCallStatus
    )
})
}
    
    /**
     * Read the stored blob for `genesis_hash` into this provider, so the next
     * [`connect`](Self::connect) to that chain resumes from finalized state
     * instead of syncing from the chain-spec checkpoint. Answers whether a
     * blob is now in hand.
     *
     * Fails when the provider was built through [`new`](Self::new), which has
     * nowhere to keep blobs. A chain that never warms up looks exactly like
     * one with nothing stored yet, so the missing store is reported rather
     * than swallowed: build with [`with_storage`](Self::with_storage).
     *
     * Call it before `connect`, and never from a listener callback. `connect`
     * blocks its calling thread, so a store awaited underneath it would
     * deadlock. The store is read at most once per chain: smoldot keys a chain
     * by its genesis hash, so only the first connect to a chain can consume a
     * blob.
     */
open func loadDatabase(genesisHash: Data)async throws  -> Bool  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_truapi_provider_fn_method_chainprovider_load_database(
                        self.uniffiCloneHandle(),FfiConverterData.lower(genesisHash)
                )
            },
            pollFunc: ffi_truapi_provider_rust_future_poll_i8,
            completeFunc: ffi_truapi_provider_rust_future_complete_i8,
            freeFunc: ffi_truapi_provider_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: FfiConverterTypeChainProviderError_lift
        )
}
    
    /**
     * Snapshot the finalized state for `genesis_hash` and hand it to storage.
     * Answers whether a blob was stored, and fails when the provider was built
     * without one, for the same reason [`load_database`](Self::load_database) does.
     *
     * This is a full round trip against the light client rather than a write,
     * so call it while the app is alive. From a backgrounding callback treat
     * it as best effort: nothing keeps a backgrounded app scheduled long
     * enough to guarantee it finishes. A chain that has finalized nothing yet
     * stores nothing and answers `false`, rather than replacing a good blob
     * with one smoldot would discard.
     */
open func saveDatabase(genesisHash: Data)async throws  -> Bool  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_truapi_provider_fn_method_chainprovider_save_database(
                        self.uniffiCloneHandle(),FfiConverterData.lower(genesisHash)
                )
            },
            pollFunc: ffi_truapi_provider_rust_future_poll_i8,
            completeFunc: ffi_truapi_provider_rust_future_complete_i8,
            freeFunc: ffi_truapi_provider_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: FfiConverterTypeChainProviderError_lift
        )
}
    
    /**
     * Watch what the light client is doing on the chain identified by
     * `genesis_hash` (32 bytes). `listener` receives the current state, then
     * every change, until the watch is stopped or the chain stops running.
     *
     * Fails when nothing is connected to the chain, so connect first.
     */
open func watchLifecycle(genesisHash: Data, listener: ChainLifecycleListener)throws  -> LifecycleWatch  {
    return try  FfiConverterTypeLifecycleWatch_lift(try rustCallWithError(FfiConverterTypeChainProviderError_lift) {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_chainprovider_watch_lifecycle(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(genesisHash),
        FfiConverterTypeChainLifecycleListener_lower(listener),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainProvider: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ChainProvider

    public static func lift(_ handle: UInt64) throws -> ChainProvider {
        return ChainProvider(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ChainProvider) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainProvider {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ChainProvider, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainProvider_lift(_ handle: UInt64) throws -> ChainProvider {
    return try FfiConverterTypeChainProvider.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainProvider_lower(_ value: ChainProvider) -> UInt64 {
    return FfiConverterTypeChainProvider.lower(value)
}






/**
 * A live watch on one chain's lifecycle. Dropping it stops the watch.
 */
public protocol LifecycleWatchProtocol: AnyObject, Sendable {
    
    /**
     * Stop the watch; the listener's `on_ended` fires once the pump notices.
     *
     * Not named `close`, for the reason [`ChainConnection::disconnect`] gives.
     */
    func stop() 
    
}
/**
 * A live watch on one chain's lifecycle. Dropping it stops the watch.
 */
open class LifecycleWatch: LifecycleWatchProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_truapi_provider_fn_clone_lifecyclewatch(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_truapi_provider_fn_free_lifecyclewatch(handle, $0) }
    }

    

    
    /**
     * Stop the watch; the listener's `on_ended` fires once the pump notices.
     *
     * Not named `close`, for the reason [`ChainConnection::disconnect`] gives.
     */
open func stop()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_truapi_provider_fn_method_lifecyclewatch_stop(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLifecycleWatch: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = LifecycleWatch

    public static func lift(_ handle: UInt64) throws -> LifecycleWatch {
        return LifecycleWatch(unsafeFromHandle: handle)
    }

    public static func lower(_ value: LifecycleWatch) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LifecycleWatch {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: LifecycleWatch, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLifecycleWatch_lift(_ handle: UInt64) throws -> LifecycleWatch {
    return try FfiConverterTypeLifecycleWatch.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLifecycleWatch_lower(_ value: LifecycleWatch) -> UInt64 {
    return FfiConverterTypeLifecycleWatch.lower(value)
}






/**
 * Where warm-start blobs are kept between runs.
 *
 * A client that cannot answer must return `Err`, never `Ok(None)`: an empty
 * read is taken as nothing being stored for that chain yet, and lets a later
 * [`save_database`](crate::EmbeddedChainProvider::save_database) overwrite good state.
 *
 * A loaded blob is trusted input: it goes to the light client as the finalized
 * state to resume from, so whatever can write to the store can steer the
 * view the client has of the chain. Keep storage no more writable than the source
 * the chain specification itself came from.
 */
public protocol StorageClient: AnyObject, Sendable {
    
    /**
     * Read the blob stored for `genesis_hash`, if any.
     */
    func load(genesisHash: GenesisHash) async throws  -> String?
    
    /**
     * Replace the blob stored for `genesis_hash`.
     */
    func save(genesisHash: GenesisHash, blob: String) async throws 
    
}
/**
 * Where warm-start blobs are kept between runs.
 *
 * A client that cannot answer must return `Err`, never `Ok(None)`: an empty
 * read is taken as nothing being stored for that chain yet, and lets a later
 * [`save_database`](crate::EmbeddedChainProvider::save_database) overwrite good state.
 *
 * A loaded blob is trusted input: it goes to the light client as the finalized
 * state to resume from, so whatever can write to the store can steer the
 * view the client has of the chain. Keep storage no more writable than the source
 * the chain specification itself came from.
 */
open class StorageClientImpl: StorageClient, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_truapi_provider_fn_clone_storageclient(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_truapi_provider_fn_free_storageclient(handle, $0) }
    }

    

    
    /**
     * Read the blob stored for `genesis_hash`, if any.
     */
open func load(genesisHash: GenesisHash)async throws  -> String?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_truapi_provider_fn_method_storageclient_load(
                        self.uniffiCloneHandle(),FfiConverterTypeGenesisHash_lower(genesisHash)
                )
            },
            pollFunc: ffi_truapi_provider_rust_future_poll_rust_buffer,
            completeFunc: ffi_truapi_provider_rust_future_complete_rust_buffer,
            freeFunc: ffi_truapi_provider_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionString.lift,
            errorHandler: FfiConverterTypeStorageClientError_lift
        )
}
    
    /**
     * Replace the blob stored for `genesis_hash`.
     */
open func save(genesisHash: GenesisHash, blob: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_truapi_provider_fn_method_storageclient_save(
                        self.uniffiCloneHandle(),FfiConverterTypeGenesisHash_lower(genesisHash),FfiConverterString.lower(blob)
                )
            },
            pollFunc: ffi_truapi_provider_rust_future_poll_void,
            completeFunc: ffi_truapi_provider_rust_future_complete_void,
            freeFunc: ffi_truapi_provider_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeStorageClientError_lift
        )
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceStorageClient {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceStorageClient = UniffiVTableCallbackInterfaceStorageClient(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeStorageClient.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface StorageClient: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeStorageClient.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface StorageClient: handle missing in uniffiClone")
            }
        },
        load: { (
            uniffiHandle: UInt64,
            genesisHash: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteRustBuffer,
            uniffiCallbackData: UInt64,
            uniffiOutDroppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
        ) in
            let makeCall = {
                () async throws -> String? in
                guard let uniffiObj = try? FfiConverterTypeStorageClient.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.load(
                     genesisHash: try FfiConverterTypeGenesisHash_lift(genesisHash)
                )
            }

            let uniffiHandleSuccess = { (returnValue: String?) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: FfiConverterOptionString.lower(returnValue),
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: RustBuffer.empty(),
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeStorageClientError_lower,
                droppedCallback: uniffiOutDroppedCallback
            )
        },
        save: { (
            uniffiHandle: UInt64,
            genesisHash: RustBuffer,
            blob: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteVoid,
            uniffiCallbackData: UInt64,
            uniffiOutDroppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
        ) in
            let makeCall = {
                () async throws -> () in
                guard let uniffiObj = try? FfiConverterTypeStorageClient.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.save(
                     genesisHash: try FfiConverterTypeGenesisHash_lift(genesisHash),
                     blob: try FfiConverterString.lift(blob)
                )
            }

            let uniffiHandleSuccess = { (returnValue: ()) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultVoid(
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultVoid(
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeStorageClientError_lower,
                droppedCallback: uniffiOutDroppedCallback
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceStorageClient> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceStorageClient>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitStorageClient() {
    uniffi_truapi_provider_fn_init_callback_vtable_storageclient(UniffiCallbackInterfaceStorageClient.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStorageClient: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<StorageClient>()

    typealias FfiType = UInt64
    typealias SwiftType = StorageClient

    public static func lift(_ handle: UInt64) throws -> StorageClient {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return StorageClientImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: StorageClient) -> UInt64 {
         if let rustImpl = value as? StorageClientImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StorageClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: StorageClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStorageClient_lift(_ handle: UInt64) throws -> StorageClient {
    return try FfiConverterTypeStorageClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStorageClient_lower(_ value: StorageClient) -> UInt64 {
    return FfiConverterTypeStorageClient.lower(value)
}




/**
 * Lifecycle state of a chain. Every update carries the whole state.
 */
public struct ChainLifecycle: Equatable, Hashable {
    /**
     * How far the chain has bootstrapped.
     */
    public var phase: ChainPhase
    /**
     * Number of peers currently connected on this chain.
     */
    public var peers: UInt32
    /**
     * Whether the chain is making progress.
     */
    public var health: ChainHealth

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * How far the chain has bootstrapped.
         */phase: ChainPhase, 
        /**
         * Number of peers currently connected on this chain.
         */peers: UInt32, 
        /**
         * Whether the chain is making progress.
         */health: ChainHealth) {
        self.phase = phase
        self.peers = peers
        self.health = health
    }

    

    
}

#if compiler(>=6)
extension ChainLifecycle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainLifecycle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainLifecycle {
        return
            try ChainLifecycle(
                phase: FfiConverterTypeChainPhase.read(from: &buf), 
                peers: FfiConverterUInt32.read(from: &buf), 
                health: FfiConverterTypeChainHealth.read(from: &buf)
        )
    }

    public static func write(_ value: ChainLifecycle, into buf: inout [UInt8]) {
        FfiConverterTypeChainPhase.write(value.phase, into: &buf)
        FfiConverterUInt32.write(value.peers, into: &buf)
        FfiConverterTypeChainHealth.write(value.health, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainLifecycle_lift(_ buf: RustBuffer) throws -> ChainLifecycle {
    return try FfiConverterTypeChainLifecycle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainLifecycle_lower(_ value: ChainLifecycle) -> RustBuffer {
    return FfiConverterTypeChainLifecycle.lower(value)
}


/**
 * Why the pump stopped delivering a connection's responses.
 *
 * This says what the core observed, not whether a reconnect is wanted. On the
 * light-client path a response stream ends only when the connection is closed,
 * including by this host's own `disconnect()` or by dropping the handle, so
 * `StreamEnded` is usually the host's own teardown coming back to it. A host
 * that reconnects on it without checking its own intent will reconnect to a
 * connection it deliberately closed.
 *
 * New variants may be added, so a Swift host should carry an `@unknown
 * default` and a Kotlin host an `else` branch.
 *
 * Reconnecting is done from another thread, and a serial one: a listener
 * callback runs on the pump thread, and `ChainProvider::connect` refuses to
 * run there. Hopping to a concurrent queue lets reconnects run in parallel,
 * and each one costs a thread plus a chain-spec parse.
 *
 * Do not re-queue work with `send` from `on_closed`. By then the connection
 * is closed either way: `close()` is what ended the stream on `StreamEnded`,
 * and the pump closes it before reporting `ListenerFailed`. `send` on a
 * closed connection is dropped silently, with no error and no frame for the
 * request's id, so a consumer correlating by id would wait forever. From `on_message`, where the
 * connection is still open, `send` behaves normally. `disconnect` is
 * idempotent and safe to call from either callback.
 */

public enum ChainCloseReason: Equatable, Hashable {
    
    /**
     * The response stream ended.
     *
     * Every connection this crate hands a host runs on the embedded light
     * client, and that stream ends only when the connection is closed, so in
     * practice this is your own teardown arriving back: `disconnect()`, or
     * dropping the handle. It is not a report that the peer went away.
     */
    case streamEnded
    /**
     * This listener returned an error from `on_message`, so the connection was
     * closed under it.
     *
     * A listener that rejects frames while it is shutting down reports this
     * even when the host asked for the teardown: `on_message` blocks in
     * foreign code, so a `disconnect()` can land while a frame is already in
     * flight, and rejecting that frame is a listener failure like any other.
     */
    case listenerFailed(
        /**
         * What the listener reported, bounded to 256 characters. For logs
         * and diagnostics: a
         * host that needs to branch on its own failure modes should track them
         * where it raised them.
         */reason: String
    )





}

#if compiler(>=6)
extension ChainCloseReason: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainCloseReason: FfiConverterRustBuffer {
    typealias SwiftType = ChainCloseReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainCloseReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .streamEnded
        
        case 2: return .listenerFailed(reason: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChainCloseReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case .streamEnded:
            writeInt(&buf, Int32(1))
        
        
        case let .listenerFailed(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainCloseReason_lift(_ buf: RustBuffer) throws -> ChainCloseReason {
    return try FfiConverterTypeChainCloseReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainCloseReason_lower(_ value: ChainCloseReason) -> RustBuffer {
    return FfiConverterTypeChainCloseReason.lower(value)
}



/**
 * Verdict of smoldot's stall watchdog.
 */

public enum ChainHealth: Equatable, Hashable {
    
    /**
     * The chain is progressing, or has not been stuck long enough to say.
     */
    case ok
    /**
     * The chain has stopped progressing.
     */
    case stalled(
        /**
         * Why the chain is considered stalled.
         */reason: StallReason
    )





}

#if compiler(>=6)
extension ChainHealth: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainHealth: FfiConverterRustBuffer {
    typealias SwiftType = ChainHealth

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainHealth {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ok
        
        case 2: return .stalled(reason: try FfiConverterTypeStallReason.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChainHealth, into buf: inout [UInt8]) {
        switch value {
        
        
        case .ok:
            writeInt(&buf, Int32(1))
        
        
        case let .stalled(reason):
            writeInt(&buf, Int32(2))
            FfiConverterTypeStallReason.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainHealth_lift(_ buf: RustBuffer) throws -> ChainHealth {
    return try FfiConverterTypeChainHealth.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainHealth_lower(_ value: ChainHealth) -> RustBuffer {
    return FfiConverterTypeChainHealth.lower(value)
}



/**
 * Bootstrap progress of a chain.
 *
 * A parachain goes from `Connecting` straight to `Ready`: its progress is the
 * progress of its relay, which is the chain to watch for a progress bar.
 */

public enum ChainPhase: Equatable, Hashable {
    
    /**
     * The chain has been added and no block is being streamed yet.
     */
    case connecting
    /**
     * A warp sync is in progress.
     */
    case syncing(
        /**
         * Highest block proven finalized so far.
         */at: UInt64, 
        /**
         * Highest best block a connected peer advertises. Never below `at`.
         */target: UInt64
    )
    /**
     * The chain is synced and following new blocks. Not terminal: a later
     * warp sync moves the chain back to `Syncing`.
     */
    case ready





}

#if compiler(>=6)
extension ChainPhase: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainPhase: FfiConverterRustBuffer {
    typealias SwiftType = ChainPhase

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainPhase {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connecting
        
        case 2: return .syncing(at: try FfiConverterUInt64.read(from: &buf), target: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 3: return .ready
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChainPhase, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connecting:
            writeInt(&buf, Int32(1))
        
        
        case let .syncing(at,target):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(at, into: &buf)
            FfiConverterUInt64.write(target, into: &buf)
            
        
        case .ready:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainPhase_lift(_ buf: RustBuffer) throws -> ChainPhase {
    return try FfiConverterTypeChainPhase.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainPhase_lower(_ value: ChainPhase) -> RustBuffer {
    return FfiConverterTypeChainPhase.lower(value)
}



/**
 * Errors surfaced to the foreign caller.
 */
public 
enum ChainProviderError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The chain could not be connected (unknown genesis, transport failure).
     */
    case Connect(
        /**
         * Human-readable failure reason.
         */reason: String
    )
    /**
     * The genesis hash was not exactly 32 bytes.
     */
    case BadGenesis
    /**
     * The host's listener failed in a way it did not declare.
     */
    case Listener(
        /**
         * Human-readable failure reason.
         */reason: String
    )
    /**
     * The lifecycle of a chain could not be watched: nothing is connected to
     * it, or no thread could be started to deliver it.
     */
    case Lifecycle(
        /**
         * Human-readable failure reason.
         */reason: String
    )
    /**
     * Storage the host owns, or the snapshot taken to feed it, failed.
     */
    case Storage(
        /**
         * Human-readable failure reason.
         */reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ChainProviderError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChainProviderError: FfiConverterRustBuffer {
    typealias SwiftType = ChainProviderError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChainProviderError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Connect(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .BadGenesis
        case 3: return .Listener(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Lifecycle(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Storage(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChainProviderError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Connect(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .BadGenesis:
            writeInt(&buf, Int32(2))
        
        
        case let .Listener(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Lifecycle(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Storage(reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainProviderError_lift(_ buf: RustBuffer) throws -> ChainProviderError {
    return try FfiConverterTypeChainProviderError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChainProviderError_lower(_ value: ChainProviderError) -> RustBuffer {
    return FfiConverterTypeChainProviderError.lower(value)
}


/**
 * Why a chain is considered stalled.
 */

public enum StallReason: Equatable, Hashable {
    
    /**
     * No peer has been connected for 30 seconds.
     */
    case noPeers
    /**
     * A warp sync has not advanced for 45 seconds.
     */
    case noProgress





}

#if compiler(>=6)
extension StallReason: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStallReason: FfiConverterRustBuffer {
    typealias SwiftType = StallReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StallReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .noPeers
        
        case 2: return .noProgress
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StallReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case .noPeers:
            writeInt(&buf, Int32(1))
        
        
        case .noProgress:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStallReason_lift(_ buf: RustBuffer) throws -> StallReason {
    return try FfiConverterTypeStallReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStallReason_lower(_ value: StallReason) -> RustBuffer {
    return FfiConverterTypeStallReason.lower(value)
}



/**
 * Failure reported by a [`StorageClient`] implementation.
 *
 * An enum with one variant rather than a struct because the native bindings
 * export this type, and uniffi errors must be enums.
 */
public 
enum StorageClientError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The store could not read or write the blob.
     */
    case Failed(
        /**
         * What went wrong, for logs and error reports.
         */reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension StorageClientError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStorageClientError: FfiConverterRustBuffer {
    typealias SwiftType = StorageClientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StorageClientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Failed(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StorageClientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Failed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStorageClientError_lift(_ buf: RustBuffer) throws -> StorageClientError {
    return try FfiConverterTypeStorageClientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStorageClientError_lower(_ value: StorageClientError) -> RustBuffer {
    return FfiConverterTypeStorageClientError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}


public typealias GenesisHash = Data

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGenesisHash: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GenesisHash {
        return try FfiConverterData.read(from: &buf)
    }

    public static func write(_ value: GenesisHash, into buf: inout [UInt8]) {
        return FfiConverterData.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> GenesisHash {
        return try FfiConverterData.lift(value)
    }

    public static func lower(_ value: GenesisHash) -> RustBuffer {
        return FfiConverterData.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenesisHash_lift(_ value: RustBuffer) throws -> GenesisHash {
    return try FfiConverterTypeGenesisHash.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenesisHash_lower(_ value: GenesisHash) -> RustBuffer {
    return FfiConverterTypeGenesisHash.lower(value)
}

private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureTruapiProviderInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
private func uniffiTraitInterfaceCallAsync<T>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // Note: it's important we call either `handleSuccess` or `handleError` exactly once.  Each
        // call consumes an Arc reference, which means there should be no possibility of a double
        // call.  The following code is structured so that will will never call both `handleSuccess`
        // and `handleError`, even in the face of weird errors.
        //
        // On platforms that need extra machinery to make C-ABI calls, like JNA or ctypes, it's
        // possible that we fail to make either call.  However, it doesn't seem like this is
        // possible on Swift since swift can just make the C call directly.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

private func uniffiTraitInterfaceCallAsyncWithError<T, E>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    lowerError: @escaping (E) -> RustBuffer,
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // See the note in uniffiTraitInterfaceCallAsync for details on `handleSuccess` and
        // `handleError`.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch let error as E {
            handleError(CALL_ERROR, lowerError(error))
            return
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

// Borrow the callback handle map implementation to store foreign future handles
// TODO: consolidate the handle-map code (https://github.com/mozilla/uniffi-rs/pull/1823)
fileprivate let UNIFFI_FOREIGN_FUTURE_HANDLE_MAP = UniffiHandleMap<UniffiForeignFutureTask>()

// Protocol for tasks that handle foreign futures.
//
// Defining a protocol allows all tasks to be stored in the same handle map.  This can't be done
// with the task object itself, since has generic parameters.
fileprivate protocol UniffiForeignFutureTask {
    func cancel()
}

extension Task: UniffiForeignFutureTask {}

private func uniffiForeignFutureDroppedCallback(handle: UInt64) {
    do {
        let task = try UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.remove(handle: handle)
        // Set the cancellation flag on the task.  If it's still running, the code can check the
        // cancellation flag or call `Task.checkCancellation()`.  If the task has completed, this is
        // a no-op.
        task.cancel()
    } catch {
        print("uniffiForeignFutureDroppedCallback: handle missing from handlemap")
    }
}

// For testing
public func uniffiForeignFutureHandleCountTruapiProvider() -> Int {
    UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.count
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_truapi_provider_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainconnection_disconnect() != 40440) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainconnection_send() != 52883) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainlifecyclelistener_on_lifecycle() != 1999) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainlifecyclelistener_on_ended() != 3211) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainmessagelistener_on_message() != 2156) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainmessagelistener_on_closed() != 45188) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainprovider_connect() != 16550) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainprovider_load_database() != 12237) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainprovider_save_database() != 65214) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_chainprovider_watch_lifecycle() != 37056) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_lifecyclewatch_stop() != 40907) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_storageclient_load() != 51394) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_method_storageclient_save() != 2297) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_constructor_chainprovider_new() != 25928) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_truapi_provider_checksum_constructor_chainprovider_with_storage() != 3989) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitChainLifecycleListener()
    uniffiCallbackInitChainMessageListener()
    uniffiCallbackInitStorageClient()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTruapiProviderInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all