// Auto-generated by truapi-codegen. Do not edit.
//
// Adapts the typed `HostCallbacks` surface onto the byte-oriented
// callback surface the WASM core invokes. Codec-backed wire and
// platform-local types cross as SCALE bytes (`.enc`/`.dec`); strings,
// primitives and byte blobs pass through unchanged.

import {
  HostChatCreateRoomRequest,
  HostChatCreateRoomResponse,
  HostChatListSubscribeItem,
  HostChatPostMessageRequest,
  HostChatPostMessageResponse,
  HostChatRegisterBotRequest,
  HostChatRegisterBotResponse,
  HostDevicePermissionRequest,
  HostFeatureSupportedRequest,
  HostFeatureSupportedResponse,
  HostLocalStorageChangeItem,
  HostLocaleSubscribeItem,
  HostPocketListSubscribeItem,
  HostPocketRemoveCardRequest,
  HostPushNotificationRequest,
  HostPushNotificationResponse,
  HostThemeSubscribeItem,
  HostWorkerBeginOperationResponse,
  RemotePermissionRequest,
} from "@parity/truapi";
import type { GenericError } from "@parity/truapi";
import {
  AuthState,
  CoreStorageKey,
  DevicePermissionStatus,
  HostChainSet,
  HostContactLookup,
  HostContactMatches,
  HostContactPick,
  PermissionDecision,
  ProductContext,
  UserConfirmationReview,
} from "./host-callbacks.js";
import type { RequiredHostCallbacks } from "./host-callbacks.js";

import type { ChainConnect } from "../runtime.js";
import { chainConnectAdapter, driveResultStream } from "../adapter-support.js";

/**
 * Byte-oriented callback surface the WASM core invokes. Members of an
 * optional capability are absent when the host omits the capability;
 * the core then answers the matching product calls with `Unsupported`.
 */
export interface RawCallbacks {
  authStateChanged(state: Uint8Array): void;
  chainConnect: ChainConnect;
  createChatRoom?(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  registerChatBot?(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  postChatMessage?(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  subscribeChatRooms?(
    product: Uint8Array,
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  contacts?(lookup: Uint8Array): Promise<Uint8Array>;
  pickContact?(product: Uint8Array): Promise<Uint8Array>;
  readCoreStorage(key: Uint8Array): Promise<Uint8Array | null | undefined>;
  writeCoreStorage(key: Uint8Array, value: Uint8Array): Promise<void>;
  clearCoreStorage(key: Uint8Array): Promise<void>;
  featureSupported(request: Uint8Array): Promise<Uint8Array>;
  supportedChains(): Promise<Uint8Array>;
  scheduleGameReminder?(product: Uint8Array, startsAt: bigint): Promise<void>;
  cancelGameReminder?(product: Uint8Array): Promise<void>;
  subscribeLocale(
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  navigateTo(url: string): Promise<void>;
  pushNotification(notification: Uint8Array): Promise<Uint8Array>;
  cancelNotification(id: number): Promise<void>;
  devicePermissionStatus?(request: Uint8Array): Promise<Uint8Array>;
  devicePermission(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  remotePermission(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  subscribePocketCards?(
    product: Uint8Array,
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  removePocketCard?(product: Uint8Array, request: Uint8Array): Promise<void>;
  lookupPreimage(
    key: Uint8Array,
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  beginOperation(product: Uint8Array, label: string): Promise<Uint8Array>;
  endOperation(product: Uint8Array, id: number): Promise<void>;
  read(key: string): Promise<Uint8Array | null | undefined>;
  write(key: string, value: Uint8Array): Promise<void>;
  clear(key: string): Promise<void>;
  subscribeStorage(
    key: string,
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  subscribeTheme(
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  confirmPermission(review: Uint8Array): Promise<Uint8Array>;
  confirmUserAction(review: Uint8Array): Promise<boolean>;
}
/** Adapt typed host callbacks into the raw SCALE callback surface the
 *  WASM core invokes. */
export function createWasmRawCallbacks(
  callbacks: RequiredHostCallbacks,
): RawCallbacks {
  const chat = callbacks.chat;
  const contacts = callbacks.contacts;
  const game = callbacks.game;
  const permissionStatus = callbacks.permissionStatus;
  const pocket = callbacks.pocket;
  return {
    authStateChanged: async (state) =>
      await callbacks.auth.authStateChanged(AuthState.dec(state)),
    chainConnect: chainConnectAdapter(callbacks.chain),
    ...(chat
      ? {
          createChatRoom: async (product, request) =>
            HostChatCreateRoomResponse.enc(
              await chat.createChatRoom(
                ProductContext.dec(product),
                HostChatCreateRoomRequest.dec(request),
              ),
            ),
          registerChatBot: async (product, request) =>
            HostChatRegisterBotResponse.enc(
              await chat.registerChatBot(
                ProductContext.dec(product),
                HostChatRegisterBotRequest.dec(request),
              ),
            ),
          postChatMessage: async (product, request) =>
            HostChatPostMessageResponse.enc(
              await chat.postChatMessage(
                ProductContext.dec(product),
                HostChatPostMessageRequest.dec(request),
              ),
            ),
          subscribeChatRooms: (product, sendItem, sendError) =>
            driveResultStream(
              chat.subscribeChatRooms(ProductContext.dec(product)),
              (item) => sendItem(HostChatListSubscribeItem.enc(item)),
              sendError,
            ),
        }
      : {}),
    ...(contacts
      ? {
          contacts: async (lookup) =>
            HostContactMatches.enc(
              await contacts.contacts(HostContactLookup.dec(lookup)),
            ),
          pickContact: async (product) =>
            HostContactPick.enc(
              await contacts.pickContact(ProductContext.dec(product)),
            ),
        }
      : {}),
    readCoreStorage: async (key) =>
      await callbacks.coreStorage.readCoreStorage(CoreStorageKey.dec(key)),
    writeCoreStorage: async (key, value) =>
      await callbacks.coreStorage.writeCoreStorage(
        CoreStorageKey.dec(key),
        value,
      ),
    clearCoreStorage: async (key) =>
      await callbacks.coreStorage.clearCoreStorage(CoreStorageKey.dec(key)),
    featureSupported: async (request) =>
      HostFeatureSupportedResponse.enc(
        await callbacks.features.featureSupported(
          HostFeatureSupportedRequest.dec(request),
        ),
      ),
    supportedChains: async () =>
      HostChainSet.enc(await callbacks.features.supportedChains()),
    ...(game
      ? {
          scheduleGameReminder: async (product, startsAt) =>
            await game.scheduleGameReminder(
              ProductContext.dec(product),
              startsAt,
            ),
          cancelGameReminder: async (product) =>
            await game.cancelGameReminder(ProductContext.dec(product)),
        }
      : {}),
    subscribeLocale: (sendItem, sendError) =>
      driveResultStream(
        callbacks.locale.subscribeLocale(),
        (item) => sendItem(HostLocaleSubscribeItem.enc(item)),
        sendError,
      ),
    navigateTo: async (url) => await callbacks.navigation.navigateTo(url),
    pushNotification: async (notification) =>
      HostPushNotificationResponse.enc(
        await callbacks.notifications.pushNotification(
          HostPushNotificationRequest.dec(notification),
        ),
      ),
    cancelNotification: async (id) =>
      await callbacks.notifications.cancelNotification(id),
    ...(permissionStatus
      ? {
          devicePermissionStatus: async (request) =>
            DevicePermissionStatus.enc(
              await permissionStatus.devicePermissionStatus(
                HostDevicePermissionRequest.dec(request),
              ),
            ),
        }
      : {}),
    devicePermission: async (product, request) =>
      PermissionDecision.enc(
        await callbacks.permissions.devicePermission(
          ProductContext.dec(product),
          HostDevicePermissionRequest.dec(request),
        ),
      ),
    remotePermission: async (product, request) =>
      PermissionDecision.enc(
        await callbacks.permissions.remotePermission(
          ProductContext.dec(product),
          RemotePermissionRequest.dec(request),
        ),
      ),
    ...(pocket
      ? {
          subscribePocketCards: (product, sendItem, sendError) =>
            driveResultStream(
              pocket.subscribePocketCards(ProductContext.dec(product)),
              (item) => sendItem(HostPocketListSubscribeItem.enc(item)),
              sendError,
            ),
          removePocketCard: async (product, request) =>
            await pocket.removePocketCard(
              ProductContext.dec(product),
              HostPocketRemoveCardRequest.dec(request),
            ),
        }
      : {}),
    lookupPreimage: (key, sendItem, sendError) =>
      driveResultStream(
        callbacks.preimage.lookupPreimage(key),
        sendItem,
        sendError,
      ),
    beginOperation: async (product, label) =>
      HostWorkerBeginOperationResponse.enc(
        await callbacks.productOperations.beginOperation(
          ProductContext.dec(product),
          label,
        ),
      ),
    endOperation: async (product, id) =>
      await callbacks.productOperations.endOperation(
        ProductContext.dec(product),
        id,
      ),
    read: async (key) => await callbacks.productStorage.read(key),
    write: async (key, value) =>
      await callbacks.productStorage.write(key, value),
    clear: async (key) => await callbacks.productStorage.clear(key),
    subscribeStorage: (key, sendItem, sendError) =>
      driveResultStream(
        callbacks.productStorage.subscribeStorage(key),
        (item) => sendItem(HostLocalStorageChangeItem.enc(item)),
        sendError,
      ),
    subscribeTheme: (sendItem, sendError) =>
      driveResultStream(
        callbacks.theme.subscribeTheme(),
        (item) => sendItem(HostThemeSubscribeItem.enc(item)),
        sendError,
      ),
    confirmPermission: async (review) =>
      PermissionDecision.enc(
        await callbacks.userConfirmation.confirmPermission(
          UserConfirmationReview.dec(review),
        ),
      ),
    confirmUserAction: async (review) =>
      await callbacks.userConfirmation.confirmUserAction(
        UserConfirmationReview.dec(review),
      ),
  };
}
