// Auto-generated by truapi-codegen. Do not edit.
//
// Typed host-callbacks surface derived from the `platform` modules'
// capability traits. One interface per Rust trait + a composite
// `HostCallbacks` interface that mirrors the `Platform` super-trait.

import * as S from "@parity/truapi/scale";

import {
  AllocatableResource,
  Bytes32,
  ChainIdentifier,
  HostAccountSignVrfRequest,
  HostDevicePermissionRequest,
  HostSignPayloadRequest,
  HostSignPayloadWithLegacyAccountRequest,
  HostSignRawRequest,
  HostSignRawWithLegacyAccountRequest,
  LegacyAccountTxPayload,
  ProductAccountId,
  ProductAccountTxPayload,
  ProductProofContext,
  RemotePermissionRequest,
  RingLocation,
} from "@parity/truapi";

import type {
  GenericError,
  HostChatCreateRoomRequest,
  HostChatCreateRoomResponse,
  HostChatListSubscribeItem,
  HostChatPostMessageRequest,
  HostChatPostMessageResponse,
  HostChatRegisterBotRequest,
  HostChatRegisterBotResponse,
  HostFeatureSupportedRequest,
  HostFeatureSupportedResponse,
  HostLocalStorageChangeItem,
  HostLocaleSubscribeItem,
  HostPocketListSubscribeItem,
  HostPocketRemoveCardRequest,
  HostPushNotificationRequest,
  HostPushNotificationResponse,
  HostThemeSubscribeItem,
  HostWorkerBeginOperationResponse,
  Result,
} from "@parity/truapi";

/**
 * Review shown before a product asks to access another product account.
 */
export interface AccountAccessReview {
  /**
   * Product currently handling the request.
   */
  requestingProductId: string;

  /**
   * Product whose account is being requested.
   */
  targetProductId: string;
}

/**
 * Review shown before a product derives a contextual alias (RFC 0004).
 */
export interface AccountAliasReview {
  /**
   * Product requesting the alias.
   */
  callingProductId: string;

  /**
   * Product-scoped context the alias is bound to.
   */
  context: ProductProofContext;

  /**
   * Ring the alias is derived against.
   */
  ringLocation: RingLocation;
}

/**
 * Auth/session lifecycle state the core projects for host UI. The core owns
 * every transition and emits states in order; hosts render the current state
 * and never derive auth UI from any other signal.
 */
export type AuthState =
  /**
   * No active session and no login in progress.
   */
  | { tag: "Disconnected"; value?: undefined }
  /**
   * A login is in progress: present the pairing deeplink/QR. Leave this
   * state only on a subsequent emission (connected, failed, or
   * disconnected after cancellation).
   */
  | { tag: "Pairing"; value: { deeplink: string } }
  /**
   * A session is active.
   */
  | { tag: "Connected"; value: SessionUiInfo }
  /**
   * The last login attempt failed; show the reason and offer a retry.
   */
  | { tag: "LoginFailed"; value: { kind: LoginFailureKind; reason: string } }
  /**
   * The wallet accepted the pairing request and the core is resolving and
   * persisting the session. Hosts should replace the pairing QR with an
   * in-progress presentation until a terminal state is emitted.
   */
  | { tag: "Authenticating"; value?: undefined };

/**
 * Core-owned host-private storage slots. Products never address these slots;
 * the host chooses the backing store for each slot.
 *
 * Storage is host-local; `storage.md` records the current status quo:
 * <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/storage.md?plain=1#L1-L7>
 */
export type CoreStorageKey =
  /**
   * Opaque SSO/auth session blob.
   */
  | { tag: "AuthSession"; value?: undefined }
  /**
   * Pairing device identity used during SSO flows.
   */
  | { tag: "PairingDeviceIdentity"; value?: undefined }
  /**
   * Persisted authorization for one product-scoped permission request.
   */
  | {
      tag: "PermissionAuthorization";
      value: { productId: string; request: PermissionAuthorizationRequest };
    }
  /**
   * Persisted allowance-slot keys for one paired SSO session.
   */
  | { tag: "AllowanceKeys"; value: { sessionId: string } }
  /**
   * Last processed SSO pairing response statement for the pairing device.
   */
  | { tag: "LastProcessedPairingStatement"; value?: undefined }
  /**
   * Legacy unscoped RFC-0010 AutoSigning secret. Core only addresses this
   * slot to reject and erase pre-scoping entries.
   */
  | { tag: "AutoSigningKey"; value: { productId: string } }
  /**
   * Wallet-bound RFC-0010 AutoSigning capabilities for the active pairing.
   */
  | { tag: "AutoSigningKeys"; value?: undefined }
  /**
   * Wallet-bound RFC-0024 ring-VRF registry snapshot.
   */
  | { tag: "RingVrfRegistry"; value: { rootPublicKey: Uint8Array } }
  /**
   * Statement-store allowance targets the signing host keeps renewed.
   */
  | { tag: "StatementRenewalTargets"; value?: undefined }
  /**
   * This device's long-lived X25519 encryption secret, advertised to peers
   * as the device encryption public key. Random rather than identity-derived
   * so devices restoring one identity stay individually addressable.
   *
   * Hosts must back this slot with storage scoped to the install, outliving
   * logout and any per-user namespacing: once it changes, peers addressing
   * the previous key can no longer reach this device.
   */
  | { tag: "DeviceEncryptionKey"; value?: undefined }
  /**
   * One product's hard-subtree public key, as the Account Holder answered it
   * for this paired session. Product account is a hard derivation, so the
   * answer is fixed for the pair and read back instead of re-asking the
   * wallet on every launch.
   *
   * The value is the 32-byte key with no framing, so a host can derive
   * product account addresses from the slot it already stores. These are
   * public keys: every address derived from them already appears on the
   * reviews the host draws.
   */
  | { tag: "ProductSubtree"; value: { sessionId: string; productId: string } }
  /**
   * Signing-host request replay state for one wallet and pairing peer.
   *
   * The value is a versioned, bounded replay ledger owned by the core.
   */
  | {
      tag: "SsoResponderRequestLedger";
      value: {
        rootPublicKey: Uint8Array;
        peerStatementAccountId: Uint8Array;
        peerEncryptionPublicKey: Uint8Array;
      };
    }
  /**
   * Cached root manifest of one product, as published to dotNS.
   *
   * The value carries the manifest JSON alongside the time it was read. The
   * core honours it for a bounded lifetime, which is what makes a revoked
   * trust grant eventually take effect.
   */
  | { tag: "ProductManifest"; value: { productId: string } };

/**
 * Review shown before a product creates a ring-VRF proof (RFC 0004).
 */
export interface CreateProofReview {
  /**
   * Product requesting the proof.
   */
  callingProductId: string;

  /**
   * Product-scoped context the proof's alias is bound to.
   */
  context: ProductProofContext;

  /**
   * Ring the proof is generated against.
   */
  ringLocation: RingLocation;

  /**
   * Opaque message bound into the proof.
   */
  message: Uint8Array;
}

/**
 * Review shown before a transaction-creation request is sent to the paired wallet.
 */
export type CreateTransactionReview =
  /**
   * Product-account transaction request.
   */
  | {
      tag: "Product";
      value: { callingProductId?: string; payload: ProductAccountTxPayload };
    }
  /**
   * Legacy-account transaction request.
   */
  | { tag: "LegacyAccount"; value: LegacyAccountTxPayload };

/**
 * What the operating system currently says about a device capability.
 *
 * Distinct from `PermissionAuthorizationStatus`, which is the product-scoped
 * decision the user made through TrUAPI. The two answer different questions
 * and are combined rather than substituted: a capability is usable only when
 * the product holds a grant *and* the OS still allows it.
 */
export type DevicePermissionStatus =
  | "Granted"
  | "Denied"
  | "NotDetermined"
  | "NotApplicable";

/**
 * One chain a host serves: a protocol chain role mapped to the concrete
 * chain of the host's configured environment.
 */
export interface HostChainEntry {
  /**
   * Protocol role this entry answers for.
   */
  identifier: ChainIdentifier;

  /**
   * Genesis hash identifying the chain in all chain-scoped calls.
   */
  genesisHash: Bytes32;
}

/**
 * The chain set a host serves: its environment plus one entry per chain role.
 */
export interface HostChainSet {
  /**
   * Ecosystem the host is configured for, e.g. "polkadot", "paseo".
   */
  network: string;

  /**
   * Chains this host serves, keyed by protocol role.
   */
  chains: Array<HostChainEntry>;
}

/**
 * Contact handles the core needs turned back into accounts, and the key they
 * were minted under.
 *
 * A handle is `BLAKE2b-256(key = handle_key, message = account)`, the account
 * being its 32 raw bytes. The host holds the accounts, so it is the one that
 * can match: hash each contact's account under `handle_key`, or keep that hash
 * as an indexed column for the session, and look the handles up.
 */
export interface HostContactLookup {
  /**
   * The key every handle here was minted under. Per session, and never
   * given to a product.
   */
  handleKey: Bytes32;

  /**
   * The handles to resolve, in the order the answer must follow.
   */
  handles: Array<Bytes32>;
}

/**
 * The host's answer to a `HostContactLookup`.
 *
 * A named wrapper because the callback emitter cannot return a bare `Vec`.
 */
export interface HostContactMatches {
  /**
   * One entry per requested handle, in order: the contact's account, or
   * ``undefined`` when no current contact hashes to it.
   */
  accounts: Array<Bytes32 | undefined>;
}

/**
 * How a host's contact picker ended.
 */
export type HostContactPick =
  /**
   * The user chose this account.
   *
   * Consumed by the core to mint the product-facing handle and never
   * forwarded to a product: it is the person's real account, and the handle
   * exists precisely so a product does not receive it.
   */
  | { tag: "Picked"; value: { account: Bytes32 } }
  /**
   * The user closed the picker without choosing.
   */
  | { tag: "Dismissed"; value?: undefined }
  /**
   * The user has no contacts, so the host drew nothing.
   */
  | { tag: "NoContacts"; value?: undefined }
  /**
   * This host resolves contacts but cannot present a picker. The core
   * answers the product `Unsupported`, so it can tell "try again later"
   * apart from "this host will never pick".
   */
  | { tag: "Unsupported"; value?: undefined };

/**
 * Review shown before a product learns the user's primary identity.
 */
export interface IdentityDisclosureReview {
  /**
   * Product currently handling the request.
   */
  productId: string;
}

/**
 * Why a login attempt failed, for hosts that need to act on the cause rather
 * than only display it.
 */
export type LoginFailureKind = "NoFreeAllowanceSlots" | "Other";

/**
 * Permission request whose authorization status can be inspected or updated
 * by host administration UI.
 */
export type PermissionAuthorizationRequest =
  /**
   * Device-level permission such as camera, microphone, or location.
   */
  | { tag: "Device"; value: HostDevicePermissionRequest }
  /**
   * Remote/product-scoped permission such as chain submit or HTTP access.
   */
  | { tag: "Remote"; value: RemotePermissionRequest }
  /**
   * Product-scoped permission to disclose the user's primary identity.
   */
  | { tag: "IdentityDisclosure"; value?: undefined }
  /**
   * Product-scoped permission to access another product's account context.
   */
  | { tag: "AccountAccess"; value: { targetProductId: string } };

/**
 * Authorization status for a permission request.
 *
 * `NotDetermined` means the core has no saved or one-use answer and will prompt the
 * host the next time the product requests this permission.
 */
export type PermissionAuthorizationStatus =
  | "NotDetermined"
  | "Denied"
  | "Authorized";

/**
 * User decision including how long an authorization should last.
 */
export type PermissionDecision = "AllowOnce" | "AllowAlways" | "Deny";

/**
 * Review shown before a preimage is submitted.
 */
export interface PreimageSubmitReview {
  /**
   * Size of the preimage in bytes.
   */
  size: bigint;
}

/**
 * Product identity attached to one product-facing TrUAPI connection.
 *
 * A host may create multiple product runtimes from the same long-lived host
 * runtime, each with its own product context.
 */
export interface ProductContext {
  /**
   * Product identifier used for account derivation and product-scoped
   * storage/permission namespaces.
   *
   * Host-spec C.7 defines accepted product id forms:
   * <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/C-account-derivation.md?plain=1#L109-L128>
   */
  productId: string;

  /**
   * Trusted kind of executable attached to this connection by the host.
   */
  executionKind: ProductExecutionKind;
}

/**
 * Trusted kind of product executable attached to a TrUAPI connection.
 *
 * Mirrors the executable kinds a product manifest declares. The variants are
 * capability classes: a connection reaches an execution-gated service only
 * when its kind matches exactly, so `App` and `Widget` carry the same
 * capability and differ only in how the host presents them, and `Worker` is
 * the only kind that may serve the Chat modality.
 */
export type ProductExecutionKind = "App" | "Widget" | "Worker";

/**
 * Review shown before a product resolves its own account subtree over SSO,
 * when the value is not cached and the core must ask the Account Holder.
 */
export interface ProductSubtreeReview {
  /**
   * Product resolving its own account.
   */
  productId: string;
}

/**
 * Review shown before allocating resources for a product. Names the
 * beneficiary product so the user knows which product receives the
 * (signing-capable) allowance key they are approving.
 */
export interface ResourceAllocationReview {
  /**
   * Product the allocation is requested for.
   */
  callingProductId: string;

  /**
   * Resources to allocate.
   */
  resources: Array<AllocatableResource>;
}

/**
 * Decoded session fields a host shell needs to render account UI without
 * parsing the opaque session blob the core persists through `CoreStorage`.
 */
export interface SessionUiInfo {
  /**
   * 32-byte sr25519 root public key of the active session.
   */
  publicKey: Bytes32;

  /**
   * Wallet identity account id used for the dotNS username lookup on Asset Hub.
   */
  identityAccountId?: Bytes32;

  /**
   * X25519 public key addressing this identity in chat. Public counterpart
   * of the key `CoreAdmin::get_session_chat_identity_key` serves.
   */
  chatPublicKey?: Bytes32;

  /**
   * X25519 public key of the wallet device that answered pairing. Hosts
   * running their own encrypted device-sync channel key it against this.
   */
  deviceEncPublicKey?: Bytes32;

  /**
   * Statement-store account id the paired wallet signs every session-channel
   * statement with. Whether it is scoped to the wallet device or to the
   * wallet identity is the wallet's choice, so hosts must not treat it as a
   * device discriminator; use `Self::device_enc_public_key` for that.
   */
  peerStatementAccountId?: Bytes32;

  /**
   * Statement-store account id this device advertises in the pairing
   * proposal; the paired wallet registers the statement-store allowance for
   * it, and peers address this host on topics derived from it. Rotated per
   * login. Secret at `CoreAdmin::get_device_statement_key`.
   */
  deviceStatementAccountId?: Bytes32;

  /**
   * Short username from the dotNS identity record on Asset Hub.
   */
  liteUsername?: string;

  /**
   * Fully qualified username from the dotNS identity record on Asset Hub.
   */
  fullUsername?: string;
}

/**
 * Review shown before a sign-payload request is sent to the paired wallet.
 */
export type SignPayloadReview =
  /**
   * Product-account signing request.
   */
  | {
      tag: "Product";
      value: { callingProductId?: string; request: HostSignPayloadRequest };
    }
  /**
   * Legacy-account signing request.
   */
  | { tag: "LegacyAccount"; value: HostSignPayloadWithLegacyAccountRequest };

/**
 * Review shown before a sign-raw request is sent to the paired wallet.
 * Hosts must display the payload according to `watermarked` and warn that
 * unwatermarked signatures can authorize transactions.
 */
export type SignRawReview =
  /**
   * Product-account raw signing request.
   */
  | {
      tag: "Product";
      value: {
        callingProductId?: string;
        request: HostSignRawRequest;
        watermarked: boolean;
      };
    }
  /**
   * Legacy-account raw signing request.
   */
  | {
      tag: "LegacyAccount";
      value: {
        request: HostSignRawWithLegacyAccountRequest;
        watermarked: boolean;
      };
    };

/**
 * Review shown before signing an RFC-0023 VRF transcript.
 */
export interface SignVrfReview {
  /**
   * Product making the request.
   */
  callingProductId: string;

  /**
   * Product account and exact ordered transcript.
   */
  request: HostAccountSignVrfRequest;
}

/**
 * Review shown before a product account signs a Statement Store proof
 * payload. Distinct from raw-message signing: the payload is the exact
 * unsigned statement, signed as-is (no `<Bytes>` envelope), so the host must
 * not present it with the raw-signing convention.
 */
export interface StatementStoreProductSignReview {
  /**
   * Product that asked, when the request carries a caller. See
   * `SignPayloadReview::Product`.
   */
  callingProductId?: string;

  /**
   * Product account that will sign the statement payload.
   */
  account: ProductAccountId;

  /**
   * Exact unsigned statement payload to be signed.
   */
  payload: Uint8Array;
}

/**
 * Review shown before a user-confirmed core action continues.
 */
export type UserConfirmationReview =
  /**
   * Sign a SCALE payload with a product or legacy account.
   */
  | { tag: "SignPayload"; value: SignPayloadReview }
  /**
   * Sign raw bytes with a product or legacy account.
   */
  | { tag: "SignRaw"; value: SignRawReview }
  /**
   * Sign a Statement Store proof payload with a product account.
   */
  | { tag: "StatementStoreProductSign"; value: StatementStoreProductSignReview }
  /**
   * Create a transaction with a product or legacy account.
   */
  | { tag: "CreateTransaction"; value: CreateTransactionReview }
  /**
   * Allow a product to derive a contextual alias for a ring.
   */
  | { tag: "AccountAlias"; value: AccountAliasReview }
  /**
   * Allow a product to create a ring-VRF proof for a ring.
   */
  | { tag: "CreateProof"; value: CreateProofReview }
  /**
   * Allow a product to learn the user's primary identity.
   */
  | { tag: "IdentityDisclosure"; value: IdentityDisclosureReview }
  /**
   * Allocate resources for the requesting product.
   */
  | { tag: "ResourceAllocation"; value: ResourceAllocationReview }
  /**
   * Submit a preimage to the host-selected backend.
   */
  | { tag: "PreimageSubmit"; value: PreimageSubmitReview }
  /**
   * Allow a product to access another product account.
   */
  | { tag: "AccountAccess"; value: AccountAccessReview }
  /**
   * Sign an RFC-0023 VRF transcript with a product account.
   */
  | { tag: "SignVrf"; value: SignVrfReview }
  /**
   * Resolve a product's own account subtree over SSO.
   */
  | { tag: "ProductSubtree"; value: ProductSubtreeReview };

/**
 * Review shown before a product asks to access another product account.
 */
export const AccountAccessReview: S.Codec<AccountAccessReview> = S.lazy(
  (): S.Codec<AccountAccessReview> =>
    S.Struct({
      requestingProductId: S.str,
      targetProductId: S.str,
    }) as S.Codec<AccountAccessReview>,
);

/**
 * Review shown before a product derives a contextual alias (RFC 0004).
 */
export const AccountAliasReview: S.Codec<AccountAliasReview> = S.lazy(
  (): S.Codec<AccountAliasReview> =>
    S.Struct({
      callingProductId: S.str,
      context: ProductProofContext,
      ringLocation: RingLocation,
    }) as S.Codec<AccountAliasReview>,
);

/**
 * Auth/session lifecycle state the core projects for host UI. The core owns
 * every transition and emits states in order; hosts render the current state
 * and never derive auth UI from any other signal.
 */
export const AuthState: S.Codec<AuthState> = S.lazy(
  (): S.Codec<AuthState> =>
    S.TaggedUnion({
      Disconnected: S._void,
      Pairing: S.Struct({ deeplink: S.str }) as S.Codec<{ deeplink: string }>,
      Connected: SessionUiInfo,
      LoginFailed: S.Struct({
        kind: LoginFailureKind,
        reason: S.str,
      }) as S.Codec<{ kind: LoginFailureKind; reason: string }>,
      Authenticating: S._void,
    }),
);

/**
 * Core-owned host-private storage slots. Products never address these slots;
 * the host chooses the backing store for each slot.
 *
 * Storage is host-local; `storage.md` records the current status quo:
 * <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/storage.md?plain=1#L1-L7>
 */
export const CoreStorageKey: S.Codec<CoreStorageKey> = S.lazy(
  (): S.Codec<CoreStorageKey> =>
    S.TaggedUnion({
      AuthSession: S._void,
      PairingDeviceIdentity: S._void,
      PermissionAuthorization: S.Struct({
        productId: S.str,
        request: PermissionAuthorizationRequest,
      }) as S.Codec<{
        productId: string;
        request: PermissionAuthorizationRequest;
      }>,
      AllowanceKeys: S.Struct({ sessionId: S.str }) as S.Codec<{
        sessionId: string;
      }>,
      LastProcessedPairingStatement: S._void,
      AutoSigningKey: S.Struct({ productId: S.str }) as S.Codec<{
        productId: string;
      }>,
      AutoSigningKeys: S._void,
      RingVrfRegistry: S.Struct({ rootPublicKey: S.Bytes(32) }) as S.Codec<{
        rootPublicKey: Uint8Array;
      }>,
      StatementRenewalTargets: S._void,
      DeviceEncryptionKey: S._void,
      ProductSubtree: S.Struct({
        sessionId: S.str,
        productId: S.str,
      }) as S.Codec<{ sessionId: string; productId: string }>,
      SsoResponderRequestLedger: S.Struct({
        rootPublicKey: S.Bytes(32),
        peerStatementAccountId: S.Bytes(32),
        peerEncryptionPublicKey: S.Bytes(32),
      }) as S.Codec<{
        rootPublicKey: Uint8Array;
        peerStatementAccountId: Uint8Array;
        peerEncryptionPublicKey: Uint8Array;
      }>,
      ProductManifest: S.Struct({ productId: S.str }) as S.Codec<{
        productId: string;
      }>,
    }),
);

/**
 * Review shown before a product creates a ring-VRF proof (RFC 0004).
 */
export const CreateProofReview: S.Codec<CreateProofReview> = S.lazy(
  (): S.Codec<CreateProofReview> =>
    S.Struct({
      callingProductId: S.str,
      context: ProductProofContext,
      ringLocation: RingLocation,
      message: S.Bytes(),
    }) as S.Codec<CreateProofReview>,
);

/**
 * Review shown before a transaction-creation request is sent to the paired wallet.
 */
export const CreateTransactionReview: S.Codec<CreateTransactionReview> = S.lazy(
  (): S.Codec<CreateTransactionReview> =>
    S.TaggedUnion({
      Product: S.Struct({
        callingProductId: S.Option(S.str),
        payload: ProductAccountTxPayload,
      }) as S.Codec<{
        callingProductId?: string;
        payload: ProductAccountTxPayload;
      }>,
      LegacyAccount: LegacyAccountTxPayload,
    }),
);

/**
 * What the operating system currently says about a device capability.
 *
 * Distinct from `PermissionAuthorizationStatus`, which is the product-scoped
 * decision the user made through TrUAPI. The two answer different questions
 * and are combined rather than substituted: a capability is usable only when
 * the product holds a grant *and* the OS still allows it.
 */
export const DevicePermissionStatus: S.Codec<DevicePermissionStatus> = S.lazy(
  (): S.Codec<DevicePermissionStatus> =>
    S.Status("Granted", "Denied", "NotDetermined", "NotApplicable"),
);

/**
 * One chain a host serves: a protocol chain role mapped to the concrete
 * chain of the host's configured environment.
 */
export const HostChainEntry: S.Codec<HostChainEntry> = S.lazy(
  (): S.Codec<HostChainEntry> =>
    S.Struct({
      identifier: ChainIdentifier,
      genesisHash: Bytes32,
    }) as S.Codec<HostChainEntry>,
);

/**
 * The chain set a host serves: its environment plus one entry per chain role.
 */
export const HostChainSet: S.Codec<HostChainSet> = S.lazy(
  (): S.Codec<HostChainSet> =>
    S.Struct({
      network: S.str,
      chains: S.Vector(HostChainEntry),
    }) as S.Codec<HostChainSet>,
);

/**
 * Contact handles the core needs turned back into accounts, and the key they
 * were minted under.
 *
 * A handle is `BLAKE2b-256(key = handle_key, message = account)`, the account
 * being its 32 raw bytes. The host holds the accounts, so it is the one that
 * can match: hash each contact's account under `handle_key`, or keep that hash
 * as an indexed column for the session, and look the handles up.
 */
export const HostContactLookup: S.Codec<HostContactLookup> = S.lazy(
  (): S.Codec<HostContactLookup> =>
    S.Struct({
      handleKey: Bytes32,
      handles: S.Vector(Bytes32),
    }) as S.Codec<HostContactLookup>,
);

/**
 * The host's answer to a `HostContactLookup`.
 *
 * A named wrapper because the callback emitter cannot return a bare `Vec`.
 */
export const HostContactMatches: S.Codec<HostContactMatches> = S.lazy(
  (): S.Codec<HostContactMatches> =>
    S.Struct({
      accounts: S.Vector(S.Option(Bytes32)),
    }) as S.Codec<HostContactMatches>,
);

/**
 * How a host's contact picker ended.
 */
export const HostContactPick: S.Codec<HostContactPick> = S.lazy(
  (): S.Codec<HostContactPick> =>
    S.TaggedUnion({
      Picked: S.Struct({ account: Bytes32 }) as S.Codec<{ account: Bytes32 }>,
      Dismissed: S._void,
      NoContacts: S._void,
      Unsupported: S._void,
    }),
);

/**
 * Review shown before a product learns the user's primary identity.
 */
export const IdentityDisclosureReview: S.Codec<IdentityDisclosureReview> =
  S.lazy(
    (): S.Codec<IdentityDisclosureReview> =>
      S.Struct({ productId: S.str }) as S.Codec<IdentityDisclosureReview>,
  );

/**
 * Why a login attempt failed, for hosts that need to act on the cause rather
 * than only display it.
 */
export const LoginFailureKind: S.Codec<LoginFailureKind> = S.lazy(
  (): S.Codec<LoginFailureKind> => S.Status("NoFreeAllowanceSlots", "Other"),
);

/**
 * Permission request whose authorization status can be inspected or updated
 * by host administration UI.
 */
export const PermissionAuthorizationRequest: S.Codec<PermissionAuthorizationRequest> =
  S.lazy(
    (): S.Codec<PermissionAuthorizationRequest> =>
      S.TaggedUnion({
        Device: HostDevicePermissionRequest,
        Remote: RemotePermissionRequest,
        IdentityDisclosure: S._void,
        AccountAccess: S.Struct({ targetProductId: S.str }) as S.Codec<{
          targetProductId: string;
        }>,
      }),
  );

/**
 * Authorization status for a permission request.
 *
 * `NotDetermined` means the core has no saved or one-use answer and will prompt the
 * host the next time the product requests this permission.
 */
export const PermissionAuthorizationStatus: S.Codec<PermissionAuthorizationStatus> =
  S.lazy(
    (): S.Codec<PermissionAuthorizationStatus> =>
      S.Status("NotDetermined", "Denied", "Authorized"),
  );

/**
 * User decision including how long an authorization should last.
 */
export const PermissionDecision: S.Codec<PermissionDecision> = S.lazy(
  (): S.Codec<PermissionDecision> =>
    S.Status("AllowOnce", "AllowAlways", "Deny"),
);

/**
 * Review shown before a preimage is submitted.
 */
export const PreimageSubmitReview: S.Codec<PreimageSubmitReview> = S.lazy(
  (): S.Codec<PreimageSubmitReview> =>
    S.Struct({ size: S.u64 }) as S.Codec<PreimageSubmitReview>,
);

/**
 * Product identity attached to one product-facing TrUAPI connection.
 *
 * A host may create multiple product runtimes from the same long-lived host
 * runtime, each with its own product context.
 */
export const ProductContext: S.Codec<ProductContext> = S.lazy(
  (): S.Codec<ProductContext> =>
    S.Struct({
      productId: S.str,
      executionKind: ProductExecutionKind,
    }) as S.Codec<ProductContext>,
);

/**
 * Trusted kind of product executable attached to a TrUAPI connection.
 *
 * Mirrors the executable kinds a product manifest declares. The variants are
 * capability classes: a connection reaches an execution-gated service only
 * when its kind matches exactly, so `App` and `Widget` carry the same
 * capability and differ only in how the host presents them, and `Worker` is
 * the only kind that may serve the Chat modality.
 */
export const ProductExecutionKind: S.Codec<ProductExecutionKind> = S.lazy(
  (): S.Codec<ProductExecutionKind> => S.Status("App", "Widget", "Worker"),
);

/**
 * Review shown before a product resolves its own account subtree over SSO,
 * when the value is not cached and the core must ask the Account Holder.
 */
export const ProductSubtreeReview: S.Codec<ProductSubtreeReview> = S.lazy(
  (): S.Codec<ProductSubtreeReview> =>
    S.Struct({ productId: S.str }) as S.Codec<ProductSubtreeReview>,
);

/**
 * Review shown before allocating resources for a product. Names the
 * beneficiary product so the user knows which product receives the
 * (signing-capable) allowance key they are approving.
 */
export const ResourceAllocationReview: S.Codec<ResourceAllocationReview> =
  S.lazy(
    (): S.Codec<ResourceAllocationReview> =>
      S.Struct({
        callingProductId: S.str,
        resources: S.Vector(AllocatableResource),
      }) as S.Codec<ResourceAllocationReview>,
  );

/**
 * Decoded session fields a host shell needs to render account UI without
 * parsing the opaque session blob the core persists through `CoreStorage`.
 */
export const SessionUiInfo: S.Codec<SessionUiInfo> = S.lazy(
  (): S.Codec<SessionUiInfo> =>
    S.Struct({
      publicKey: Bytes32,
      identityAccountId: S.Option(Bytes32),
      chatPublicKey: S.Option(Bytes32),
      deviceEncPublicKey: S.Option(Bytes32),
      peerStatementAccountId: S.Option(Bytes32),
      deviceStatementAccountId: S.Option(Bytes32),
      liteUsername: S.Option(S.str),
      fullUsername: S.Option(S.str),
    }) as S.Codec<SessionUiInfo>,
);

/**
 * Review shown before a sign-payload request is sent to the paired wallet.
 */
export const SignPayloadReview: S.Codec<SignPayloadReview> = S.lazy(
  (): S.Codec<SignPayloadReview> =>
    S.TaggedUnion({
      Product: S.Struct({
        callingProductId: S.Option(S.str),
        request: HostSignPayloadRequest,
      }) as S.Codec<{
        callingProductId?: string;
        request: HostSignPayloadRequest;
      }>,
      LegacyAccount: HostSignPayloadWithLegacyAccountRequest,
    }),
);

/**
 * Review shown before a sign-raw request is sent to the paired wallet.
 * Hosts must display the payload according to `watermarked` and warn that
 * unwatermarked signatures can authorize transactions.
 */
export const SignRawReview: S.Codec<SignRawReview> = S.lazy(
  (): S.Codec<SignRawReview> =>
    S.TaggedUnion({
      Product: S.Struct({
        callingProductId: S.Option(S.str),
        request: HostSignRawRequest,
        watermarked: S.bool,
      }) as S.Codec<{
        callingProductId?: string;
        request: HostSignRawRequest;
        watermarked: boolean;
      }>,
      LegacyAccount: S.Struct({
        request: HostSignRawWithLegacyAccountRequest,
        watermarked: S.bool,
      }) as S.Codec<{
        request: HostSignRawWithLegacyAccountRequest;
        watermarked: boolean;
      }>,
    }),
);

/**
 * Review shown before signing an RFC-0023 VRF transcript.
 */
export const SignVrfReview: S.Codec<SignVrfReview> = S.lazy(
  (): S.Codec<SignVrfReview> =>
    S.Struct({
      callingProductId: S.str,
      request: HostAccountSignVrfRequest,
    }) as S.Codec<SignVrfReview>,
);

/**
 * Review shown before a product account signs a Statement Store proof
 * payload. Distinct from raw-message signing: the payload is the exact
 * unsigned statement, signed as-is (no `<Bytes>` envelope), so the host must
 * not present it with the raw-signing convention.
 */
export const StatementStoreProductSignReview: S.Codec<StatementStoreProductSignReview> =
  S.lazy(
    (): S.Codec<StatementStoreProductSignReview> =>
      S.Struct({
        callingProductId: S.Option(S.str),
        account: ProductAccountId,
        payload: S.Bytes(),
      }) as S.Codec<StatementStoreProductSignReview>,
  );

/**
 * Review shown before a user-confirmed core action continues.
 */
export const UserConfirmationReview: S.Codec<UserConfirmationReview> = S.lazy(
  (): S.Codec<UserConfirmationReview> =>
    S.TaggedUnion({
      SignPayload: SignPayloadReview,
      SignRaw: SignRawReview,
      StatementStoreProductSign: StatementStoreProductSignReview,
      CreateTransaction: CreateTransactionReview,
      AccountAlias: AccountAliasReview,
      CreateProof: CreateProofReview,
      IdentityDisclosure: IdentityDisclosureReview,
      ResourceAllocation: ResourceAllocationReview,
      PreimageSubmit: PreimageSubmitReview,
      AccountAccess: AccountAccessReview,
      SignVrf: SignVrfReview,
      ProductSubtree: ProductSubtreeReview,
    }),
);

/**
 * Host auth UI driven by core-owned `AuthState` transitions.
 */
export interface AuthPresenter {
  /**
   * Observe an auth state change, in transition order. A pairing host
   * always receives an opening state once the core has restored the
   * persisted session, `Disconnected` included; later emissions happen
   * only when the state changes. Default is a no-op for hosts that render
   * no auth UI.
   */
  authStateChanged?(state: AuthState): void;
}

/**
 * JSON-RPC provider factory for chain access.
 *
 * The platform provides a way to get a JSON-RPC connection for a given chain.
 * The server runtime manages the chainHead v1 state machine on top of this.
 * Host-spec N.6 requires products to access chains through host-mediated
 * providers:
 * <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/N-shared-infrastructure.md?plain=1#L91-L102>
 */
export interface ChainProvider {
  /**
   * Open a JSON-RPC connection for the chain identified by `genesis_hash`.
   * Drop the returned connection to disconnect.
   */
  connect(genesisHash: Uint8Array): Promise<JsonRpcConnection>;
}

/**
 * Host-implemented adapter through which product Chat calls reach host
 * storage and UI. Optional: a host that omits it leaves Chat requests
 * answered `Unsupported`. See `OptionalPlatform`.
 *
 * The core bounds and screens the product-supplied fields it forwards. Ids,
 * names and icons on `create_chat_room`, `register_chat_bot` and
 * `post_chat_message` are NFC-normalized and rejected for control and bidi
 * characters. Message bodies are bounded and screened but pass through
 * byte-for-byte, keeping line breaks and tabs, so a product reads back the
 * bytes it sent. Counts and byte budgets are enforced, and any URL a host may
 * fetch or open is restricted to `https` or an inline raster image and
 * delivered as the parser resolved it.
 *
 * The core screens a URL's shape, not its reachability. `https://127.0.0.1`,
 * `https://[::1]`, a private range and `https://169.254.169.254` (the cloud
 * metadata endpoint) all pass: which networks a host is willing to fetch from
 * depends on where that host runs, and a core that guessed would break a host
 * serving its own media from localhost. A host that fetches these URLs owns
 * that decision. Credentials are the exception and are refused, because
 * `user:pass@` survives resolution into whatever the host fetches and logs.
 *
 * `ChatFile::size_bytes` is a product assertion and is not verified against
 * the resource it names. Contextual output escaping, storage limits, and
 * anything a host derives from product-supplied values remain host-owned.
 */
export interface ChatPlatform {
  /**
   * Create or resolve a product-scoped native chat room.
   */
  createChatRoom(
    product: ProductContext,
    request: HostChatCreateRoomRequest,
  ): Promise<HostChatCreateRoomResponse>;

  /**
   * Register or resolve a product-scoped native chat bot. Host-owned in the
   * same way rooms are.
   */
  registerChatBot(
    product: ProductContext,
    request: HostChatRegisterBotRequest,
  ): Promise<HostChatRegisterBotResponse>;

  /**
   * Persist a product-authored message in a native chat room. A host that
   * cannot store a given content variant reports a domain error for it.
   */
  postChatMessage(
    product: ProductContext,
    request: HostChatPostMessageRequest,
  ): Promise<HostChatPostMessageResponse>;

  /**
   * Emit the current product-scoped room list and later replacements.
   */
  subscribeChatRooms(
    product: ProductContext,
  ): AsyncIterable<Result<HostChatListSubscribeItem, GenericError>>;
}

/**
 * Host-owned contact picker, drawn from the chat lists the host's chat
 * extensions hold.
 *
 * Optional, and listed on `OptionalPlatform` as `ChatPlatform` is.
 *
 * The host owns the UI and the list. It draws the names, so nothing it renders
 * reaches the product, and the list never crosses to the core either: the core
 * asks only about the handles a transaction names. A host omits contacts the
 * user has blocked, from the picker and from lookups alike.
 */
export interface ContactsPlatform {
  /**
   * Resolve `lookup.handles` to the contacts they name.
   *
   * The one method a host has to write. Answer one entry per handle, in
   * order, with ``undefined`` for a handle no current contact hashes to — a
   * removed or blocked contact, or a handle a product made up. The core
   * re-hashes every account returned and refuses one that does not match
   * its handle, so a wrong answer is caught rather than trusted.
   */
  contacts(lookup: HostContactLookup): Promise<HostContactMatches>;

  /**
   * Present the contact picker on behalf of `product` and return the user's
   * choice.
   *
   * Defaults to `HostContactPick::Unsupported`, so a Rust host that
   * implements `Self::contacts` alone still compiles and its products get
   * a truthful answer rather than a dismissal they would retry forever.
   *
   * A JS host reaches the same answer by another route: the generated
   * surface types this method optional, but a capability group counts as
   * served only when every callback in it is present, so omitting this one
   * makes the whole group absent and `contacts.pick` answers `Unsupported`
   * before any of it is reached.
   *
   * The core cannot draw UI, so a selection has to come from the host; the
   * whole point is that the host renders the names rather than shipping
   * them to the product. `product` is passed so the host can say who is
   * asking; it is not a filter. A host with no contacts answers
   * `HostContactPick::NoContacts` instead of drawing an empty overlay.
   */
  pickContact?(product: ProductContext): Promise<HostContactPick>;
}

/**
 * Core-owned administration API exposed to host UI.
 *
 * Hosts call this surface to drive global runtime actions or inspect/update
 * core-owned state without going through a product-scoped TrUAPI request.
 */
export interface CoreAdmin {
  /**
   * Best-effort logout/disconnect. Clears the active session and emits the
   * resulting auth state transition.
   */
  disconnectSession(): Promise<void>;

  /**
   * Read a stored permission authorization status without prompting.
   *
   * A device capability also resolves the host application's OS gate, so an
   * OS refusal reads as `Denied` whatever is stored. Remote,
   * identity-disclosure and account-access decisions have no OS gate.
   */
  getPermissionAuthorizationStatus(
    request: PermissionAuthorizationRequest,
  ): Promise<PermissionAuthorizationStatus>;

  /**
   * Read stored permission authorization statuses without prompting.
   *
   * A device capability also resolves the host application's OS gate, so an
   * OS refusal reads as `Denied` whatever is stored. Remote,
   * identity-disclosure and account-access decisions have no OS gate.
   *
   * Results are returned in the same order as `requests`.
   */
  getPermissionAuthorizationStatuses(
    requests: Array<PermissionAuthorizationRequest>,
  ): Promise<Array<PermissionAuthorizationStatus>>;

  /**
   * Update a stored permission authorization status. `NotDetermined` clears
   * the stored value so the next product request prompts again.
   */
  setPermissionAuthorizationStatus(
    request: PermissionAuthorizationRequest,
    status: PermissionAuthorizationStatus,
  ): Promise<void>;

  /**
   * Read the active session's X25519 chat identity private key, for hosts
   * that run their own P2P chat channel for the paired identity.
   *
   * The wallet derives this key from the identity root and shares it during
   * pairing; the core retains it verbatim, because a value derived
   * host-side would address an identity no existing peer can reach. ``undefined``
   * when no session is active.
   *
   * Deliberately not on `SessionUiInfo`: that projection rides every
   * `AuthState` broadcast to all registered `AuthPresenter`s, so a
   * secret placed there would reach hosts that never asked for it.
   */
  getSessionChatIdentityKey(): Promise<Bytes32 | undefined>;

  /**
   * Read the active session's expanded sr25519 statement-store secret, for
   * hosts that run their own statement-store traffic. 64 bytes.
   *
   * The key behind `SessionUiInfo::device_statement_account_id`: signing
   * with anything else produces statements no allowance covers. ``undefined``
   * without an active pairing-host session; a signing host has no pairing
   * proposal of its own.
   *
   * Deliberately not on `SessionUiInfo`, for the reason given on
   * `Self::get_session_chat_identity_key`.
   */
  getDeviceStatementKey(): Promise<Uint8Array | undefined>;

  /**
   * Read this device's X25519 encryption secret, for hosts that run device
   * sync against the peer's `SessionUiInfo::device_enc_public_key`.
   *
   * Generated and persisted on first read, so the returned key is stable for
   * the install and matches the public key peers were told to address.
   */
  getDeviceEncryptionKey(): Promise<Bytes32>;

  /**
   * Read `product_id`'s hard-subtree public key, so a host can name the
   * account a review will sign with instead of showing a bare derivation
   * path.
   *
   * Resolves from the memory cache, then the persisted slot, then the
   * Account Holder. A pairing host reaching the wallet sends an SSO request,
   * which answers without prompting the user, though it can wake the phone.
   * A signing host derives locally and never waits.
   *
   * `timeout_ms` bounds that wait, and exceeding it is an error rather than
   * ``undefined``. The underlying wait has no deadline of its own, so a host
   * calling this while drawing a review should pass a timeout it is willing
   * to block for. ``undefined`` uses a default sized for a product awaiting a
   * signature, which is far too long to hold a render.
   *
   * ``undefined`` means no active session. Derive account public keys from the
   * answer with `deriveProductAccountPublicKey`.
   */
  getProductSubtreePublicKey(
    productId: string,
    timeoutMs: number | undefined,
  ): Promise<Bytes32 | undefined>;
}

/**
 * Host-private persistence for core-owned state.
 *
 * Clearing product-indexed slots is the host's job. The core drops the ones
 * it is holding when a session ends, but a product it never opened this run
 * has no entry to drop, so those slots outlive the disconnect. A host that
 * removes a product must clear them with the rest of that product's state, or
 * they accumulate for the life of the install.
 *
 * `describe_core_storage_key` names the product owning a slot:
 * `CoreStorageKeyDescription::product_id` is `Some` exactly for the
 * product-indexed variants, which are `PermissionAuthorization`,
 * `AutoSigningKey`, and `ProductSubtree`. Keying host storage by that value
 * makes the sweep a prefix delete rather than a scan.
 */
export interface CoreStorage {
  /**
   * Read a core-owned value by typed slot.
   */
  readCoreStorage(key: CoreStorageKey): Promise<Uint8Array | undefined>;

  /**
   * Write a core-owned value by typed slot.
   */
  writeCoreStorage(key: CoreStorageKey, value: Uint8Array): Promise<void>;

  /**
   * Clear a core-owned value by typed slot.
   */
  clearCoreStorage(key: CoreStorageKey): Promise<void>;
}

/**
 * Feature-support probing. The host answers whether it can service a given
 * capability (currently scoped to per-chain support).
 */
export interface Features {
  /**
   * Report whether the requested feature is supported.
   */
  featureSupported(
    request: HostFeatureSupportedRequest,
  ): Promise<HostFeatureSupportedResponse>;

  /**
   * Enumerate the chains this host serves (RFC 0026). The core resolves
   * `get_chain_info` requests against the returned set.
   */
  supportedChains(): Promise<HostChainSet>;
}

/**
 * A live JSON-RPC connection to a chain.
 */
export interface JsonRpcConnection {
  /**
   * Send a JSON-RPC request string.
   */
  send(request: string): void;

  /**
   * Stream of JSON-RPC response strings.
   */
  responses(): AsyncIterable<string>;

  /**
   * Close the connection lease.
   *
   * Hosts may keep a shared underlying transport alive, but this handle
   * must stop receiving responses and release any per-caller resources.
   */
  close(): void;
}

/**
 * Host locale source.
 */
export interface LocaleHost {
  /**
   * Emits the currently selected locale immediately, then future changes.
   */
  subscribeLocale(): AsyncIterable<
    Result<HostLocaleSubscribeItem, GenericError>
  >;
}

/**
 * Open URLs in the system browser. Input is already trimmed, categorized,
 * and (where needed) normalized by the core; the host implementation only
 * needs to hand the URL to the OS URL handler.
 */
export interface Navigation {
  /**
   * Open the given URL in the system browser.
   */
  navigateTo(url: string): Promise<void>;
}

/**
 * Deliver push notifications.
 */
export interface Notifications {
  /**
   * Schedule or immediately display the given notification and return the
   * host-assigned id.
   */
  pushNotification(
    notification: HostPushNotificationRequest,
  ): Promise<HostPushNotificationResponse>;

  /**
   * Cancel a notification by id. Idempotent: cancelling an already-fired or
   * unknown id still returns `success`.
   */
  cancelNotification?(id: number): Promise<void>;
}

/**
 * Pairing-host-only administration API exposed to host UI.
 */
export interface PairingHostAdmin {
  /**
   * Cancel any in-flight pairing request.
   */
  cancelPairing(): void;

  /**
   * Notify the core that the persisted auth-session blob may have changed.
   *
   * The host owns persistence and change detection. The pairing core owns
   * decoding that blob into live `SessionState` / `AuthState`.
   */
  notifySessionStoreChanged(): void;
}

/**
 * Live OS permission state, read without prompting.
 *
 * A product-scoped grant is persisted once and never expires, but the OS
 * grant behind it can be revoked in system settings, suspended by device
 * policy, or reset by the platform — Android auto-resets runtime permissions
 * for apps that go unused. Without this capability the core keeps answering
 * from the stored grant alone and tells a product `granted` for a capability
 * the OS has since taken away.
 *
 * This is deliberately separate from `Permissions::device_permission`: that
 * call may show UI, so it cannot be used to re-check a decision the user has
 * already made without prompting them again on every request.
 */
export interface PermissionStatusHost {
  /**
   * Current OS status of a device capability. Must not prompt.
   */
  devicePermissionStatus(
    request: HostDevicePermissionRequest,
  ): Promise<DevicePermissionStatus>;
}

/**
 * Permission prompts. Device permissions (camera, mic, NFC, ...) are separate
 * from remote permissions (domain access, chain submit, ...), so the platform
 * surface mirrors that split.
 */
export interface Permissions {
  /**
   * Prompt the user for a device-level permission `product` requested.
   */
  devicePermission(
    product: ProductContext,
    request: HostDevicePermissionRequest,
  ): Promise<PermissionDecision>;

  /**
   * Prompt the user for a remote permission bundle `product` requested.
   */
  remotePermission(
    product: ProductContext,
    request: RemotePermissionRequest,
  ): Promise<PermissionDecision>;
}

/**
 * Host-implemented adapter through which product Pocket calls reach the
 * host's card collection. Optional: a host that omits it leaves Pocket
 * requests answered `Unsupported`. See `OptionalPlatform`.
 *
 * The host owns the collection: it decides which cards are privileged and
 * keeps each card's newest face. A face does not cross this boundary.
 */
export interface PocketPlatform {
  /**
   * Emit the calling product's current cards and every later replacement.
   */
  subscribePocketCards(
    product: ProductContext,
  ): AsyncIterable<Result<HostPocketListSubscribeItem, GenericError>>;

  /**
   * Remove one of the calling product's cards. Removing an absent card
   * succeeds; a privileged card is refused with `Privileged`.
   */
  removePocketCard(
    product: ProductContext,
    request: HostPocketRemoveCardRequest,
  ): Promise<void>;
}

/**
 * Host preimage backend. The core builds, signs, and submits the Bulletin
 * `TransactionStorage.store` transaction itself; the host only owns preimage
 * content retrieval (P2P/IPFS lookup).
 */
export interface PreimageHost {
  /**
   * Emits current value/miss immediately, then future updates.
   */
  lookupPreimage(
    key: Uint8Array,
  ): AsyncIterable<Result<Uint8Array | undefined, GenericError>>;
}

/**
 * Host store for a product's pending operations, which the host uses to keep
 * the product's worker runtime alive. Reached only through the `Worker`
 * protocol trait, so non-worker products never call these.
 */
export interface ProductOperations {
  /**
   * Record a pending operation. `label` is a host log and UI hint, empty
   * when the product gave none.
   *
   * The returned id must be unique among this product's open operations.
   * The core keys the worker reference an operation holds by that id, so an
   * id already open for the product records nothing the second time, and
   * ending it once drops the demand both were holding. Ids may repeat
   * across products, and may be reused once an operation has ended.
   */
  beginOperation(
    product: ProductContext,
    label: string,
  ): Promise<HostWorkerBeginOperationResponse>;

  /**
   * Remove a pending operation. Idempotent: an unknown or already-ended id
   * returns `Ok`, so a retry after an ambiguous failure is safe.
   */
  endOperation(product: ProductContext, id: number): Promise<void>;
}

/**
 * Product-scoped key-value storage.
 *
 * The core namespaces product keys before calling this trait, and the key
 * names the product that owns the value. Host implementations may treat
 * `key` as opaque in one shared store. A host that separates physical storage
 * by product must decode the owner with `ProductStorageKey` on read, since
 * that owner is another product on a granted foreign read.
 * Storage errors are pinned to `v01` rather than taken from `truapi::latest`.
 * The read error gained a cross-product refusal in v0.2 that the core decides
 * before it ever calls a host, so a host has no way to produce it and should
 * not have to match on it.
 */
export interface ProductStorage {
  /**
   * Read a value by key.
   *
   * `key` belongs to the calling product, or to another product the core
   * has already found granting the caller read access in its manifest. The
   * core refuses every other foreign read itself, so a host is never asked
   * to enforce a grant and has no variant for one. Writes and clears always
   * carry the calling product's own keys.
   */
  read(key: string): Promise<Uint8Array | undefined>;

  /**
   * Write a value to a key.
   */
  write(key: string, value: Uint8Array): Promise<void>;

  /**
   * Clear a value at a key.
   */
  clear(key: string): Promise<void>;

  /**
   * Emit `key`'s current value, then each later change from any of the
   * product's runtimes. `key` is namespaced exactly as `Self::read` takes
   * it.
   *
   * Reporting a write that left the bytes unchanged is allowed: the core
   * drops an item repeating the value it last delivered, so the product
   * sees only real changes whether or not a host filters them itself.
   */
  subscribeStorage(
    key: string,
  ): AsyncIterable<Result<HostLocalStorageChangeItem, GenericError>>;
}

/**
 * Host theme source.
 */
export interface ThemeHost {
  /**
   * Emits current theme immediately, then future changes. Hosts with no
   * named themes report `ThemeName::Default`.
   */
  subscribeTheme(): AsyncIterable<Result<HostThemeSubscribeItem, GenericError>>;
}

/**
 * Local user confirmation UI for sensitive core-owned operations.
 */
export interface UserConfirmation {
  /**
   * Preserve the lifetime of consent for identity and account disclosures.
   */
  confirmPermission?(
    review: UserConfirmationReview,
  ): Promise<PermissionDecision>;

  /**
   * Confirm a reviewed action before the core continues.
   *
   * The core drops this future when the request behind the review is
   * withdrawn, and an answer given afterwards reaches nobody. A host should
   * dismiss its prompt when that happens.
   */
  confirmUserAction(review: UserConfirmationReview): Promise<boolean>;
}

/**
 * Combined platform interface. A host must provide every capability trait
 * listed here. Members marked optional may be omitted; the core answers their
 * product calls with `Unsupported`. See `OptionalPlatform`.
 */
export interface HostCallbacks {
  navigation: Navigation;
  notifications: Notifications;
  permissions: Permissions;
  features: Features;
  productStorage: ProductStorage;
  coreStorage: CoreStorage;
  chain: ChainProvider;
  auth: AuthPresenter;
  userConfirmation: UserConfirmation;
  theme: ThemeHost;
  locale: LocaleHost;
  preimage: PreimageHost;
  productOperations: ProductOperations;
  chat?: ChatPlatform;
  contacts?: ContactsPlatform;
  permissionStatus?: PermissionStatusHost;
  pocket?: PocketPlatform;
}

export interface RequiredHostCallbacks {
  navigation: Required<Navigation>;
  notifications: Required<Notifications>;
  permissions: Required<Permissions>;
  features: Required<Features>;
  productStorage: Required<ProductStorage>;
  coreStorage: Required<CoreStorage>;
  chain: Required<ChainProvider>;
  auth: Required<AuthPresenter>;
  userConfirmation: Required<UserConfirmation>;
  theme: Required<ThemeHost>;
  locale: Required<LocaleHost>;
  preimage: Required<PreimageHost>;
  productOperations: Required<ProductOperations>;
  chat?: Required<ChatPlatform>;
  contacts?: Required<ContactsPlatform>;
  permissionStatus?: Required<PermissionStatusHost>;
  pocket?: Required<PocketPlatform>;
}
