//! Auto-generated by truapi-codegen. Do not edit.
//!
//! Mechanical wasm-bindgen callback bridge derived from the `platform`
//! modules. Raw callback names and payload shapes match the generated
//! TypeScript host-callback adapter.

use futures::stream::BoxStream;
use js_sys::{Function, Uint8Array};
use parity_scale_codec::Encode;
use truapi::latest;
use wasm_bindgen::JsValue;

use super::{
    WasmPlatform, call_js_function, decode_bytes, decode_js_item, generic, get_function,
    get_optional_function, invoke_bool, invoke_bytes_return, invoke_js_subscription,
    invoke_optional_bytes_return, invoke_unit, missing_callback, parse_optional_bytes_item,
};

/// JS-side callbacks invoked by the wasm platform bridge. Methods with
/// Rust default bodies are still required here because the generated TS
/// adapter resolves optional host callbacks before constructing this
/// raw callback object.
///
/// Callbacks of an optional capability trait are replaced by a throwing
/// stub when the host omits the group. The core never reaches them: it
/// only holds an adapter for a capability whose `has_*` accessor is
/// true, and answers the rest with `Unsupported`.
pub struct JsBridge {
    pub auth_state_changed: Function,
    pub chain_connect: Function,
    pub create_chat_room: Function,
    pub register_chat_bot: Function,
    pub post_chat_message: Function,
    pub subscribe_chat_rooms: Function,
    pub contacts: Function,
    pub pick_contact: Function,
    pub read_core_storage: Function,
    pub write_core_storage: Function,
    pub clear_core_storage: Function,
    pub feature_supported: Function,
    pub supported_chains: Function,
    pub schedule_game_reminder: Function,
    pub cancel_game_reminder: Function,
    pub subscribe_locale: Function,
    pub navigate_to: Function,
    pub push_notification: Function,
    pub cancel_notification: Function,
    pub device_permission_status: Function,
    pub device_permission: Function,
    pub remote_permission: Function,
    pub subscribe_pocket_cards: Function,
    pub remove_pocket_card: Function,
    pub lookup_preimage: Function,
    pub begin_operation: Function,
    pub end_operation: Function,
    pub read: Function,
    pub write: Function,
    pub clear: Function,
    pub subscribe_storage: Function,
    pub subscribe_theme: Function,
    pub confirm_permission: Function,
    pub confirm_user_action: Function,
    pub chat_present: bool,
    pub contacts_present: bool,
    pub game_present: bool,
    pub permission_status_present: bool,
    pub pocket_present: bool,
}

impl JsBridge {
    pub fn from_js(callbacks: &JsValue) -> Result<Self, JsValue> {
        Ok(Self {
            auth_state_changed: get_function(callbacks, "authStateChanged")?,
            chain_connect: get_function(callbacks, "chainConnect")?,
            create_chat_room: get_optional_function(callbacks, "createChatRoom")?
                .unwrap_or_else(|| missing_callback("createChatRoom")),
            register_chat_bot: get_optional_function(callbacks, "registerChatBot")?
                .unwrap_or_else(|| missing_callback("registerChatBot")),
            post_chat_message: get_optional_function(callbacks, "postChatMessage")?
                .unwrap_or_else(|| missing_callback("postChatMessage")),
            subscribe_chat_rooms: get_optional_function(callbacks, "subscribeChatRooms")?
                .unwrap_or_else(|| missing_callback("subscribeChatRooms")),
            contacts: get_optional_function(callbacks, "contacts")?
                .unwrap_or_else(|| missing_callback("contacts")),
            pick_contact: get_optional_function(callbacks, "pickContact")?
                .unwrap_or_else(|| missing_callback("pickContact")),
            read_core_storage: get_function(callbacks, "readCoreStorage")?,
            write_core_storage: get_function(callbacks, "writeCoreStorage")?,
            clear_core_storage: get_function(callbacks, "clearCoreStorage")?,
            feature_supported: get_function(callbacks, "featureSupported")?,
            supported_chains: get_function(callbacks, "supportedChains")?,
            schedule_game_reminder: get_optional_function(callbacks, "scheduleGameReminder")?
                .unwrap_or_else(|| missing_callback("scheduleGameReminder")),
            cancel_game_reminder: get_optional_function(callbacks, "cancelGameReminder")?
                .unwrap_or_else(|| missing_callback("cancelGameReminder")),
            subscribe_locale: get_function(callbacks, "subscribeLocale")?,
            navigate_to: get_function(callbacks, "navigateTo")?,
            push_notification: get_function(callbacks, "pushNotification")?,
            cancel_notification: get_function(callbacks, "cancelNotification")?,
            device_permission_status: get_optional_function(callbacks, "devicePermissionStatus")?
                .unwrap_or_else(|| missing_callback("devicePermissionStatus")),
            device_permission: get_function(callbacks, "devicePermission")?,
            remote_permission: get_function(callbacks, "remotePermission")?,
            subscribe_pocket_cards: get_optional_function(callbacks, "subscribePocketCards")?
                .unwrap_or_else(|| missing_callback("subscribePocketCards")),
            remove_pocket_card: get_optional_function(callbacks, "removePocketCard")?
                .unwrap_or_else(|| missing_callback("removePocketCard")),
            lookup_preimage: get_function(callbacks, "lookupPreimage")?,
            begin_operation: get_function(callbacks, "beginOperation")?,
            end_operation: get_function(callbacks, "endOperation")?,
            read: get_function(callbacks, "read")?,
            write: get_function(callbacks, "write")?,
            clear: get_function(callbacks, "clear")?,
            subscribe_storage: get_function(callbacks, "subscribeStorage")?,
            subscribe_theme: get_function(callbacks, "subscribeTheme")?,
            confirm_permission: get_function(callbacks, "confirmPermission")?,
            confirm_user_action: get_function(callbacks, "confirmUserAction")?,
            chat_present: get_optional_function(callbacks, "createChatRoom")?.is_some()
                && get_optional_function(callbacks, "registerChatBot")?.is_some()
                && get_optional_function(callbacks, "postChatMessage")?.is_some()
                && get_optional_function(callbacks, "subscribeChatRooms")?.is_some(),
            contacts_present: get_optional_function(callbacks, "contacts")?.is_some()
                && get_optional_function(callbacks, "pickContact")?.is_some(),
            game_present: get_optional_function(callbacks, "scheduleGameReminder")?.is_some()
                && get_optional_function(callbacks, "cancelGameReminder")?.is_some(),
            permission_status_present: get_optional_function(callbacks, "devicePermissionStatus")?
                .is_some(),
            pocket_present: get_optional_function(callbacks, "subscribePocketCards")?.is_some()
                && get_optional_function(callbacks, "removePocketCard")?.is_some(),
        })
    }

    /// Whether the host supplied every `chat` callback.
    pub fn has_chat(&self) -> bool {
        self.chat_present
    }

    /// Whether the host supplied every `contacts` callback.
    pub fn has_contacts(&self) -> bool {
        self.contacts_present
    }

    /// Whether the host supplied every `game` callback.
    pub fn has_game(&self) -> bool {
        self.game_present
    }

    /// Whether the host supplied every `permission_status` callback.
    pub fn has_permission_status(&self) -> bool {
        self.permission_status_present
    }

    /// Whether the host supplied every `pocket` callback.
    pub fn has_pocket(&self) -> bool {
        self.pocket_present
    }
}

impl crate::platform::AuthPresenter for WasmPlatform {
    fn auth_state_changed(&self, state: crate::platform::AuthState) {
        if let Err(reason) = call_js_function(
            &self.bridge.auth_state_changed,
            &[Uint8Array::from(state.encode().as_slice()).into()],
        ) {
            web_sys::console::error_1(&JsValue::from_str(&reason));
        }
    }
}

#[crate::platform::async_trait]
impl crate::platform::ChatPlatform for WasmPlatform {
    async fn create_chat_room(
        &self,
        product: &crate::platform::ProductContext,
        request: latest::HostChatCreateRoomRequest,
    ) -> Result<latest::HostChatCreateRoomResponse, latest::HostChatCreateRoomError> {
        let bytes = invoke_bytes_return(
            &self.bridge.create_chat_room,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| latest::HostChatCreateRoomError::Unknown { reason })?;
        decode_bytes::<latest::HostChatCreateRoomResponse>(
            bytes,
            "createChatRoom response did not decode",
        )
        .map_err(|reason| latest::HostChatCreateRoomError::Unknown { reason })
    }

    async fn register_chat_bot(
        &self,
        product: &crate::platform::ProductContext,
        request: latest::HostChatRegisterBotRequest,
    ) -> Result<latest::HostChatRegisterBotResponse, latest::HostChatRegisterBotError> {
        let bytes = invoke_bytes_return(
            &self.bridge.register_chat_bot,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| latest::HostChatRegisterBotError::Unknown { reason })?;
        decode_bytes::<latest::HostChatRegisterBotResponse>(
            bytes,
            "registerChatBot response did not decode",
        )
        .map_err(|reason| latest::HostChatRegisterBotError::Unknown { reason })
    }

    async fn post_chat_message(
        &self,
        product: &crate::platform::ProductContext,
        request: latest::HostChatPostMessageRequest,
    ) -> Result<latest::HostChatPostMessageResponse, latest::HostChatPostMessageError> {
        let bytes = invoke_bytes_return(
            &self.bridge.post_chat_message,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| latest::HostChatPostMessageError::Unknown { reason })?;
        decode_bytes::<latest::HostChatPostMessageResponse>(
            bytes,
            "postChatMessage response did not decode",
        )
        .map_err(|reason| latest::HostChatPostMessageError::Unknown { reason })
    }

    fn subscribe_chat_rooms(
        &self,
        product: &crate::platform::ProductContext,
    ) -> BoxStream<'static, Result<latest::HostChatListSubscribeItem, latest::GenericError>> {
        invoke_js_subscription(
            &self.bridge.subscribe_chat_rooms,
            Some(Uint8Array::from(product.encode().as_slice()).into()),
            parse_host_chat_list_subscribe_item_item,
        )
    }
}

#[crate::platform::async_trait]
impl crate::platform::ContactsPlatform for WasmPlatform {
    async fn contacts(
        &self,
        lookup: &crate::platform::HostContactLookup,
    ) -> Result<crate::platform::HostContactMatches, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.contacts,
            vec![Uint8Array::from(lookup.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<crate::platform::HostContactMatches>(
            bytes,
            "contacts response did not decode",
        )
        .map_err(generic)
    }

    async fn pick_contact(
        &self,
        _product: &crate::platform::ProductContext,
    ) -> Result<crate::platform::HostContactPick, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.pick_contact,
            vec![Uint8Array::from(_product.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<crate::platform::HostContactPick>(
            bytes,
            "pickContact response did not decode",
        )
        .map_err(generic)
    }
}

#[crate::platform::async_trait]
impl crate::platform::CoreStorage for WasmPlatform {
    async fn read_core_storage(
        &self,
        key: crate::platform::CoreStorageKey,
    ) -> Result<Option<Vec<u8>>, latest::GenericError> {
        invoke_optional_bytes_return(
            &self.bridge.read_core_storage,
            vec![Uint8Array::from(key.encode().as_slice()).into()],
            "readCoreStorage must resolve to Uint8Array, null or undefined",
        )
        .await
        .map_err(generic)
    }

    async fn write_core_storage(
        &self,
        key: crate::platform::CoreStorageKey,
        value: Vec<u8>,
    ) -> Result<(), latest::GenericError> {
        invoke_unit(
            &self.bridge.write_core_storage,
            vec![
                Uint8Array::from(key.encode().as_slice()).into(),
                Uint8Array::from(value.as_slice()).into(),
            ],
        )
        .await
        .map_err(generic)
    }

    async fn clear_core_storage(
        &self,
        key: crate::platform::CoreStorageKey,
    ) -> Result<(), latest::GenericError> {
        invoke_unit(
            &self.bridge.clear_core_storage,
            vec![Uint8Array::from(key.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)
    }
}

#[crate::platform::async_trait]
impl crate::platform::Features for WasmPlatform {
    async fn feature_supported(
        &self,
        request: latest::HostFeatureSupportedRequest,
    ) -> Result<latest::HostFeatureSupportedResponse, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.feature_supported,
            vec![Uint8Array::from(request.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<latest::HostFeatureSupportedResponse>(
            bytes,
            "featureSupported response did not decode",
        )
        .map_err(generic)
    }

    async fn supported_chains(
        &self,
    ) -> Result<crate::platform::HostChainSet, latest::GenericError> {
        let bytes = invoke_bytes_return(&self.bridge.supported_chains, Vec::new())
            .await
            .map_err(generic)?;
        decode_bytes::<crate::platform::HostChainSet>(
            bytes,
            "supportedChains response did not decode",
        )
        .map_err(generic)
    }
}

#[crate::platform::async_trait]
impl crate::platform::GamePlatform for WasmPlatform {
    async fn schedule_game_reminder(
        &self,
        product: &crate::platform::ProductContext,
        starts_at: u64,
    ) -> Result<(), latest::GenericError> {
        invoke_unit(
            &self.bridge.schedule_game_reminder,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                js_sys::BigInt::from(starts_at).into(),
            ],
        )
        .await
        .map_err(generic)
    }

    async fn cancel_game_reminder(
        &self,
        product: &crate::platform::ProductContext,
    ) -> Result<(), latest::GenericError> {
        invoke_unit(
            &self.bridge.cancel_game_reminder,
            vec![Uint8Array::from(product.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)
    }
}

impl crate::platform::LocaleHost for WasmPlatform {
    fn subscribe_locale(
        &self,
    ) -> BoxStream<'static, Result<latest::HostLocaleSubscribeItem, latest::GenericError>> {
        invoke_js_subscription(
            &self.bridge.subscribe_locale,
            None,
            parse_host_locale_subscribe_item_item,
        )
    }
}

#[crate::platform::async_trait]
impl crate::platform::Navigation for WasmPlatform {
    async fn navigate_to(&self, url: String) -> Result<(), latest::HostNavigateToError> {
        invoke_unit(&self.bridge.navigate_to, vec![JsValue::from_str(&url)])
            .await
            .map_err(|reason| latest::HostNavigateToError::Unknown { reason })
    }
}

#[crate::platform::async_trait]
impl crate::platform::Notifications for WasmPlatform {
    async fn push_notification(
        &self,
        notification: latest::HostPushNotificationRequest,
    ) -> Result<latest::HostPushNotificationResponse, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.push_notification,
            vec![Uint8Array::from(notification.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<latest::HostPushNotificationResponse>(
            bytes,
            "pushNotification response did not decode",
        )
        .map_err(generic)
    }

    async fn cancel_notification(&self, id: u32) -> Result<(), latest::GenericError> {
        invoke_unit(
            &self.bridge.cancel_notification,
            vec![JsValue::from_f64(f64::from(id))],
        )
        .await
        .map_err(generic)
    }
}

#[crate::platform::async_trait]
impl crate::platform::PermissionStatusHost for WasmPlatform {
    async fn device_permission_status(
        &self,
        request: latest::HostDevicePermissionRequest,
    ) -> Result<crate::platform::DevicePermissionStatus, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.device_permission_status,
            vec![Uint8Array::from(request.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<crate::platform::DevicePermissionStatus>(
            bytes,
            "devicePermissionStatus response did not decode",
        )
        .map_err(generic)
    }
}

#[crate::platform::async_trait]
impl crate::platform::Permissions for WasmPlatform {
    async fn device_permission(
        &self,
        product: &crate::platform::ProductContext,
        request: latest::HostDevicePermissionRequest,
    ) -> Result<crate::platform::PermissionDecision, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.device_permission,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<crate::platform::PermissionDecision>(
            bytes,
            "devicePermission response did not decode",
        )
        .map_err(generic)
    }

    async fn remote_permission(
        &self,
        product: &crate::platform::ProductContext,
        request: latest::RemotePermissionRequest,
    ) -> Result<crate::platform::PermissionDecision, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.remote_permission,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<crate::platform::PermissionDecision>(
            bytes,
            "remotePermission response did not decode",
        )
        .map_err(generic)
    }
}

#[crate::platform::async_trait]
impl crate::platform::PocketPlatform for WasmPlatform {
    fn subscribe_pocket_cards(
        &self,
        product: &crate::platform::ProductContext,
    ) -> BoxStream<'static, Result<latest::HostPocketListSubscribeItem, latest::GenericError>> {
        invoke_js_subscription(
            &self.bridge.subscribe_pocket_cards,
            Some(Uint8Array::from(product.encode().as_slice()).into()),
            parse_host_pocket_list_subscribe_item_item,
        )
    }

    async fn remove_pocket_card(
        &self,
        product: &crate::platform::ProductContext,
        request: latest::HostPocketRemoveCardRequest,
    ) -> Result<(), latest::HostPocketRemoveCardError> {
        invoke_unit(
            &self.bridge.remove_pocket_card,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| latest::HostPocketRemoveCardError::Unknown { reason })
    }
}

impl crate::platform::PreimageHost for WasmPlatform {
    fn lookup_preimage(
        &self,
        key: Vec<u8>,
    ) -> BoxStream<'static, Result<Option<Vec<u8>>, latest::GenericError>> {
        invoke_js_subscription(
            &self.bridge.lookup_preimage,
            Some(Uint8Array::from(key.as_slice()).into()),
            parse_optional_bytes_item,
        )
    }
}

#[crate::platform::async_trait]
impl crate::platform::ProductOperations for WasmPlatform {
    async fn begin_operation(
        &self,
        product: &crate::platform::ProductContext,
        label: String,
    ) -> Result<latest::HostWorkerBeginOperationResponse, latest::HostWorkerOperationError> {
        let bytes = invoke_bytes_return(
            &self.bridge.begin_operation,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                JsValue::from_str(&label),
            ],
        )
        .await
        .map_err(|reason| latest::HostWorkerOperationError::Unknown { reason })?;
        decode_bytes::<latest::HostWorkerBeginOperationResponse>(
            bytes,
            "beginOperation response did not decode",
        )
        .map_err(|reason| latest::HostWorkerOperationError::Unknown { reason })
    }

    async fn end_operation(
        &self,
        product: &crate::platform::ProductContext,
        id: u32,
    ) -> Result<(), latest::HostWorkerOperationError> {
        invoke_unit(
            &self.bridge.end_operation,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                JsValue::from_f64(f64::from(id)),
            ],
        )
        .await
        .map_err(|reason| latest::HostWorkerOperationError::Unknown { reason })
    }
}

#[crate::platform::async_trait]
impl crate::platform::ProductStorage for WasmPlatform {
    async fn read(
        &self,
        key: String,
    ) -> Result<Option<Vec<u8>>, truapi::v01::HostLocalStorageReadError> {
        invoke_optional_bytes_return(
            &self.bridge.read,
            vec![JsValue::from_str(&key)],
            "read must resolve to Uint8Array, null or undefined",
        )
        .await
        .map_err(|reason| truapi::v01::HostLocalStorageReadError::Unknown { reason })
    }

    async fn write(
        &self,
        key: String,
        value: Vec<u8>,
    ) -> Result<(), truapi::v01::HostLocalStorageReadError> {
        invoke_unit(
            &self.bridge.write,
            vec![
                JsValue::from_str(&key),
                Uint8Array::from(value.as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| truapi::v01::HostLocalStorageReadError::Unknown { reason })
    }

    async fn clear(&self, key: String) -> Result<(), truapi::v01::HostLocalStorageReadError> {
        invoke_unit(&self.bridge.clear, vec![JsValue::from_str(&key)])
            .await
            .map_err(|reason| truapi::v01::HostLocalStorageReadError::Unknown { reason })
    }

    fn subscribe_storage(
        &self,
        key: String,
    ) -> BoxStream<'static, Result<latest::HostLocalStorageChangeItem, latest::GenericError>> {
        invoke_js_subscription(
            &self.bridge.subscribe_storage,
            Some(JsValue::from_str(&key)),
            parse_host_local_storage_change_item_item,
        )
    }
}

impl crate::platform::ThemeHost for WasmPlatform {
    fn subscribe_theme(
        &self,
    ) -> BoxStream<'static, Result<latest::HostThemeSubscribeItem, latest::GenericError>> {
        invoke_js_subscription(
            &self.bridge.subscribe_theme,
            None,
            parse_host_theme_subscribe_item_item,
        )
    }
}

#[crate::platform::async_trait]
impl crate::platform::UserConfirmation for WasmPlatform {
    async fn confirm_permission(
        &self,
        review: crate::platform::UserConfirmationReview,
    ) -> Result<crate::platform::PermissionDecision, latest::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.confirm_permission,
            vec![Uint8Array::from(review.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<crate::platform::PermissionDecision>(
            bytes,
            "confirmPermission response did not decode",
        )
        .map_err(generic)
    }

    async fn confirm_user_action(
        &self,
        review: crate::platform::UserConfirmationReview,
    ) -> Result<bool, latest::GenericError> {
        invoke_bool(
            &self.bridge.confirm_user_action,
            vec![Uint8Array::from(review.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)
    }
}

fn parse_host_chat_list_subscribe_item_item(
    value: JsValue,
) -> Result<latest::HostChatListSubscribeItem, String> {
    decode_js_item::<latest::HostChatListSubscribeItem>(value, "HostChatListSubscribeItem")
}

fn parse_host_local_storage_change_item_item(
    value: JsValue,
) -> Result<latest::HostLocalStorageChangeItem, String> {
    decode_js_item::<latest::HostLocalStorageChangeItem>(value, "HostLocalStorageChangeItem")
}

fn parse_host_locale_subscribe_item_item(
    value: JsValue,
) -> Result<latest::HostLocaleSubscribeItem, String> {
    decode_js_item::<latest::HostLocaleSubscribeItem>(value, "HostLocaleSubscribeItem")
}

fn parse_host_pocket_list_subscribe_item_item(
    value: JsValue,
) -> Result<latest::HostPocketListSubscribeItem, String> {
    decode_js_item::<latest::HostPocketListSubscribeItem>(value, "HostPocketListSubscribeItem")
}

fn parse_host_theme_subscribe_item_item(
    value: JsValue,
) -> Result<latest::HostThemeSubscribeItem, String> {
    decode_js_item::<latest::HostThemeSubscribeItem>(value, "HostThemeSubscribeItem")
}
