//! Wire-protocol discriminant table.
//!
//! Auto-generated by truapi-codegen. Do not edit.
//!
//! Every frame carries a `(trait, method)` discriminant pair; one
//! method id addresses every frame a method ever sends or receives,
//! regardless of shape. Which leg a frame carries (request/response,
//! or a subscription's start/stop/interrupt/receive) is named by its
//! `message_type` byte, and the payload carries its own version. The
//! ids for each method are exposed as a named const
//! (`PREIMAGE_SUBMIT`, ...); [`WIRE_TABLE`] and the generated
//! dispatcher both reference those consts so the numbers live in
//! exactly one place. The table is sorted by (trait id, method id).

/// Wire discriminants for one method.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MethodIds {
    /// Trait discriminant carried by every frame of this method.
    pub trait_id: u8,
    /// Method discriminant carried by every frame of this method.
    pub method_id: u8,
}

/// A single wire-table row.
pub struct WireEntry {
    /// Method name from the Rust trait.
    pub method: &'static str,
    /// What kind of slot this entry describes.
    pub kind: WireKind,
}

/// Wire-slot shape: request/response or a subscription's
/// start/stop/interrupt/receive quartet.
pub enum WireKind {
    /// Request/response method.
    Request(MethodIds),
    /// Subscription method.
    Subscription(MethodIds),
}
/// Fingerprint of this build's wire contract: frame ids, method legs,
/// sensitivity, and codec version, identical to the TS client's
/// `TRUAPI_WIRE_SCHEMA_HASH`. A host stamps it on each debug envelope so
/// the debugger refuses to decode a frame whose contract differs from
/// its own, even when the coarse handshake codec version is unchanged.
pub const TRUAPI_WIRE_SCHEMA_HASH: &str = "f1965fda63b2fdb4";

/// Wire discriminants for `system_handshake`.
pub const SYSTEM_HANDSHAKE: MethodIds = MethodIds {
    trait_id: 1,
    method_id: 0,
};

/// Wire discriminants for `system_feature_supported`.
pub const SYSTEM_FEATURE_SUPPORTED: MethodIds = MethodIds {
    trait_id: 1,
    method_id: 1,
};

/// Wire discriminants for `system_navigate_to`.
pub const SYSTEM_NAVIGATE_TO: MethodIds = MethodIds {
    trait_id: 1,
    method_id: 2,
};

/// Wire discriminants for `system_host_info`.
pub const SYSTEM_HOST_INFO: MethodIds = MethodIds {
    trait_id: 1,
    method_id: 3,
};

/// Wire discriminants for `system_get_product_context`.
pub const SYSTEM_GET_PRODUCT_CONTEXT: MethodIds = MethodIds {
    trait_id: 1,
    method_id: 4,
};

/// Wire discriminants for `account_connection_status_subscribe`.
pub const ACCOUNT_CONNECTION_STATUS_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 0,
};

/// Wire discriminants for `account_get_account`.
pub const ACCOUNT_GET_ACCOUNT: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 1,
};

/// Wire discriminants for `account_get_account_alias`.
pub const ACCOUNT_GET_ACCOUNT_ALIAS: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 2,
};

/// Wire discriminants for `account_create_account_proof`.
pub const ACCOUNT_CREATE_ACCOUNT_PROOF: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 3,
};

/// Wire discriminants for `account_get_legacy_accounts`.
pub const ACCOUNT_GET_LEGACY_ACCOUNTS: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 4,
};

/// Wire discriminants for `account_get_user_id`.
pub const ACCOUNT_GET_USER_ID: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 5,
};

/// Wire discriminants for `account_request_login`.
pub const ACCOUNT_REQUEST_LOGIN: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 6,
};

/// Wire discriminants for `account_sign_vrf`.
pub const ACCOUNT_SIGN_VRF: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 7,
};

/// Wire discriminants for `account_register_ring_vrf_key`.
pub const ACCOUNT_REGISTER_RING_VRF_KEY: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 8,
};

/// Wire discriminants for `account_list_ring_vrf_keys`.
pub const ACCOUNT_LIST_RING_VRF_KEYS: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 9,
};

/// Wire discriminants for `account_ring_vrf_sign`.
pub const ACCOUNT_RING_VRF_SIGN: MethodIds = MethodIds {
    trait_id: 2,
    method_id: 10,
};

/// Wire discriminants for `chain_follow_head_subscribe`.
pub const CHAIN_FOLLOW_HEAD_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 0,
};

/// Wire discriminants for `chain_get_head_header`.
pub const CHAIN_GET_HEAD_HEADER: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 1,
};

/// Wire discriminants for `chain_get_head_body`.
pub const CHAIN_GET_HEAD_BODY: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 2,
};

/// Wire discriminants for `chain_get_head_storage`.
pub const CHAIN_GET_HEAD_STORAGE: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 3,
};

/// Wire discriminants for `chain_call_head`.
pub const CHAIN_CALL_HEAD: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 4,
};

/// Wire discriminants for `chain_unpin_head`.
pub const CHAIN_UNPIN_HEAD: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 5,
};

/// Wire discriminants for `chain_continue_head`.
pub const CHAIN_CONTINUE_HEAD: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 6,
};

/// Wire discriminants for `chain_stop_head_operation`.
pub const CHAIN_STOP_HEAD_OPERATION: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 7,
};

/// Wire discriminants for `chain_get_spec_genesis_hash`.
pub const CHAIN_GET_SPEC_GENESIS_HASH: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 8,
};

/// Wire discriminants for `chain_get_spec_chain_name`.
pub const CHAIN_GET_SPEC_CHAIN_NAME: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 9,
};

/// Wire discriminants for `chain_get_spec_properties`.
pub const CHAIN_GET_SPEC_PROPERTIES: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 10,
};

/// Wire discriminants for `chain_broadcast_transaction`.
pub const CHAIN_BROADCAST_TRANSACTION: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 11,
};

/// Wire discriminants for `chain_stop_transaction`.
pub const CHAIN_STOP_TRANSACTION: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 12,
};

/// Wire discriminants for `chain_get_chain_info`.
pub const CHAIN_GET_CHAIN_INFO: MethodIds = MethodIds {
    trait_id: 3,
    method_id: 13,
};

/// Wire discriminants for `chat_create_room`.
pub const CHAT_CREATE_ROOM: MethodIds = MethodIds {
    trait_id: 4,
    method_id: 0,
};

/// Wire discriminants for `chat_register_bot`.
pub const CHAT_REGISTER_BOT: MethodIds = MethodIds {
    trait_id: 4,
    method_id: 1,
};

/// Wire discriminants for `chat_list_subscribe`.
pub const CHAT_LIST_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 4,
    method_id: 2,
};

/// Wire discriminants for `chat_post_message`.
pub const CHAT_POST_MESSAGE: MethodIds = MethodIds {
    trait_id: 4,
    method_id: 3,
};

/// Wire discriminants for `chat_action_subscribe`.
pub const CHAT_ACTION_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 4,
    method_id: 4,
};

/// Wire discriminants for `coin_payment_create_purse`.
pub const COIN_PAYMENT_CREATE_PURSE: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 0,
};

/// Wire discriminants for `coin_payment_query_purse`.
pub const COIN_PAYMENT_QUERY_PURSE: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 1,
};

/// Wire discriminants for `coin_payment_rebalance_purse`.
pub const COIN_PAYMENT_REBALANCE_PURSE: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 2,
};

/// Wire discriminants for `coin_payment_delete_purse`.
pub const COIN_PAYMENT_DELETE_PURSE: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 3,
};

/// Wire discriminants for `coin_payment_create_receivable`.
pub const COIN_PAYMENT_CREATE_RECEIVABLE: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 4,
};

/// Wire discriminants for `coin_payment_create_cheque`.
pub const COIN_PAYMENT_CREATE_CHEQUE: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 5,
};

/// Wire discriminants for `coin_payment_deposit`.
pub const COIN_PAYMENT_DEPOSIT: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 6,
};

/// Wire discriminants for `coin_payment_refund`.
pub const COIN_PAYMENT_REFUND: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 7,
};

/// Wire discriminants for `coin_payment_listen_for_payment`.
pub const COIN_PAYMENT_LISTEN_FOR_PAYMENT: MethodIds = MethodIds {
    trait_id: 5,
    method_id: 8,
};

/// Wire discriminants for `entropy_derive`.
pub const ENTROPY_DERIVE: MethodIds = MethodIds {
    trait_id: 6,
    method_id: 0,
};

/// Wire discriminants for `local_storage_read`.
pub const LOCAL_STORAGE_READ: MethodIds = MethodIds {
    trait_id: 7,
    method_id: 0,
};

/// Wire discriminants for `local_storage_write`.
pub const LOCAL_STORAGE_WRITE: MethodIds = MethodIds {
    trait_id: 7,
    method_id: 1,
};

/// Wire discriminants for `local_storage_clear`.
pub const LOCAL_STORAGE_CLEAR: MethodIds = MethodIds {
    trait_id: 7,
    method_id: 2,
};

/// Wire discriminants for `local_storage_subscribe`.
pub const LOCAL_STORAGE_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 7,
    method_id: 3,
};

/// Wire discriminants for `notifications_send_push_notification`.
pub const NOTIFICATIONS_SEND_PUSH_NOTIFICATION: MethodIds = MethodIds {
    trait_id: 8,
    method_id: 0,
};

/// Wire discriminants for `notifications_cancel_push_notification`.
pub const NOTIFICATIONS_CANCEL_PUSH_NOTIFICATION: MethodIds = MethodIds {
    trait_id: 8,
    method_id: 1,
};

/// Wire discriminants for `payment_balance_subscribe`.
pub const PAYMENT_BALANCE_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 9,
    method_id: 0,
};

/// Wire discriminants for `payment_top_up`.
pub const PAYMENT_TOP_UP: MethodIds = MethodIds {
    trait_id: 9,
    method_id: 1,
};

/// Wire discriminants for `payment_request`.
pub const PAYMENT_REQUEST: MethodIds = MethodIds {
    trait_id: 9,
    method_id: 2,
};

/// Wire discriminants for `payment_status_subscribe`.
pub const PAYMENT_STATUS_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 9,
    method_id: 3,
};

/// Wire discriminants for `permissions_request_device_permission`.
pub const PERMISSIONS_REQUEST_DEVICE_PERMISSION: MethodIds = MethodIds {
    trait_id: 10,
    method_id: 0,
};

/// Wire discriminants for `permissions_request_remote_permission`.
pub const PERMISSIONS_REQUEST_REMOTE_PERMISSION: MethodIds = MethodIds {
    trait_id: 10,
    method_id: 1,
};

/// Wire discriminants for `permissions_authorize_remote_permission`.
pub const PERMISSIONS_AUTHORIZE_REMOTE_PERMISSION: MethodIds = MethodIds {
    trait_id: 10,
    method_id: 2,
};

/// Wire discriminants for `permissions_authorize_device_permission`.
pub const PERMISSIONS_AUTHORIZE_DEVICE_PERMISSION: MethodIds = MethodIds {
    trait_id: 10,
    method_id: 3,
};

/// Wire discriminants for `preimage_lookup_subscribe`.
pub const PREIMAGE_LOOKUP_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 11,
    method_id: 0,
};

/// Wire discriminants for `preimage_submit`.
pub const PREIMAGE_SUBMIT: MethodIds = MethodIds {
    trait_id: 11,
    method_id: 1,
};

/// Wire discriminants for `resource_allocation_request`.
pub const RESOURCE_ALLOCATION_REQUEST: MethodIds = MethodIds {
    trait_id: 12,
    method_id: 0,
};

/// Wire discriminants for `signing_create_transaction`.
pub const SIGNING_CREATE_TRANSACTION: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 0,
};

/// Wire discriminants for `signing_create_transaction_with_legacy_account`.
pub const SIGNING_CREATE_TRANSACTION_WITH_LEGACY_ACCOUNT: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 1,
};

/// Wire discriminants for `signing_sign_raw_with_legacy_account`.
pub const SIGNING_SIGN_RAW_WITH_LEGACY_ACCOUNT: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 2,
};

/// Wire discriminants for `signing_sign_payload_with_legacy_account`.
pub const SIGNING_SIGN_PAYLOAD_WITH_LEGACY_ACCOUNT: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 3,
};

/// Wire discriminants for `signing_sign_raw`.
pub const SIGNING_SIGN_RAW: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 4,
};

/// Wire discriminants for `signing_sign_payload`.
pub const SIGNING_SIGN_PAYLOAD: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 5,
};

/// Wire discriminants for `signing_sign_raw_unwatermarked_deprecated`.
pub const SIGNING_SIGN_RAW_UNWATERMARKED_DEPRECATED: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 6,
};

/// Wire discriminants for `signing_sign_raw_unwatermarked_deprecated_with_legacy_account`.
pub const SIGNING_SIGN_RAW_UNWATERMARKED_DEPRECATED_WITH_LEGACY_ACCOUNT: MethodIds = MethodIds {
    trait_id: 13,
    method_id: 7,
};

/// Wire discriminants for `statement_store_subscribe`.
pub const STATEMENT_STORE_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 14,
    method_id: 0,
};

/// Wire discriminants for `statement_store_create_proof`.
pub const STATEMENT_STORE_CREATE_PROOF: MethodIds = MethodIds {
    trait_id: 14,
    method_id: 1,
};

/// Wire discriminants for `statement_store_submit`.
pub const STATEMENT_STORE_SUBMIT: MethodIds = MethodIds {
    trait_id: 14,
    method_id: 2,
};

/// Wire discriminants for `statement_store_create_proof_authorized`.
pub const STATEMENT_STORE_CREATE_PROOF_AUTHORIZED: MethodIds = MethodIds {
    trait_id: 14,
    method_id: 3,
};

/// Wire discriminants for `theme_subscribe`.
pub const THEME_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 15,
    method_id: 0,
};

/// Wire discriminants for `locale_subscribe`.
pub const LOCALE_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 16,
    method_id: 0,
};

/// Wire discriminants for `renderer_render`.
pub const RENDERER_RENDER: MethodIds = MethodIds {
    trait_id: 17,
    method_id: 0,
};

/// Wire discriminants for `renderer_action_subscribe`.
pub const RENDERER_ACTION_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 17,
    method_id: 1,
};

/// Wire discriminants for `pocket_list_subscribe`.
pub const POCKET_LIST_SUBSCRIBE: MethodIds = MethodIds {
    trait_id: 18,
    method_id: 0,
};

/// Wire discriminants for `pocket_remove_card`.
pub const POCKET_REMOVE_CARD: MethodIds = MethodIds {
    trait_id: 18,
    method_id: 1,
};

/// Wire discriminants for `worker_begin_operation`.
pub const WORKER_BEGIN_OPERATION: MethodIds = MethodIds {
    trait_id: 19,
    method_id: 0,
};

/// Wire discriminants for `worker_end_operation`.
pub const WORKER_END_OPERATION: MethodIds = MethodIds {
    trait_id: 19,
    method_id: 1,
};

/// Wire discriminants for `contacts_pick`.
pub const CONTACTS_PICK: MethodIds = MethodIds {
    trait_id: 20,
    method_id: 0,
};

/// Wire discriminants for `game_remind_next_game`.
pub const GAME_REMIND_NEXT_GAME: MethodIds = MethodIds {
    trait_id: 21,
    method_id: 0,
};

/// Wire discriminants for `game_cancel_next_game`.
pub const GAME_CANCEL_NEXT_GAME: MethodIds = MethodIds {
    trait_id: 21,
    method_id: 1,
};

/// The full wire table. Trait ids and per-trait method ordering are
/// part of the wire protocol; only ever append within a trait.
/// Removed methods leave their slot empty.
pub const WIRE_TABLE: &[WireEntry] = &[
    WireEntry {
        method: "system_handshake",
        kind: WireKind::Request(SYSTEM_HANDSHAKE),
    },
    WireEntry {
        method: "system_feature_supported",
        kind: WireKind::Request(SYSTEM_FEATURE_SUPPORTED),
    },
    WireEntry {
        method: "system_navigate_to",
        kind: WireKind::Request(SYSTEM_NAVIGATE_TO),
    },
    WireEntry {
        method: "system_host_info",
        kind: WireKind::Request(SYSTEM_HOST_INFO),
    },
    WireEntry {
        method: "system_get_product_context",
        kind: WireKind::Request(SYSTEM_GET_PRODUCT_CONTEXT),
    },
    WireEntry {
        method: "account_connection_status_subscribe",
        kind: WireKind::Subscription(ACCOUNT_CONNECTION_STATUS_SUBSCRIBE),
    },
    WireEntry {
        method: "account_get_account",
        kind: WireKind::Request(ACCOUNT_GET_ACCOUNT),
    },
    WireEntry {
        method: "account_get_account_alias",
        kind: WireKind::Request(ACCOUNT_GET_ACCOUNT_ALIAS),
    },
    WireEntry {
        method: "account_create_account_proof",
        kind: WireKind::Request(ACCOUNT_CREATE_ACCOUNT_PROOF),
    },
    WireEntry {
        method: "account_get_legacy_accounts",
        kind: WireKind::Request(ACCOUNT_GET_LEGACY_ACCOUNTS),
    },
    WireEntry {
        method: "account_get_user_id",
        kind: WireKind::Request(ACCOUNT_GET_USER_ID),
    },
    WireEntry {
        method: "account_request_login",
        kind: WireKind::Request(ACCOUNT_REQUEST_LOGIN),
    },
    WireEntry {
        method: "account_sign_vrf",
        kind: WireKind::Request(ACCOUNT_SIGN_VRF),
    },
    WireEntry {
        method: "account_register_ring_vrf_key",
        kind: WireKind::Request(ACCOUNT_REGISTER_RING_VRF_KEY),
    },
    WireEntry {
        method: "account_list_ring_vrf_keys",
        kind: WireKind::Request(ACCOUNT_LIST_RING_VRF_KEYS),
    },
    WireEntry {
        method: "account_ring_vrf_sign",
        kind: WireKind::Request(ACCOUNT_RING_VRF_SIGN),
    },
    WireEntry {
        method: "chain_follow_head_subscribe",
        kind: WireKind::Subscription(CHAIN_FOLLOW_HEAD_SUBSCRIBE),
    },
    WireEntry {
        method: "chain_get_head_header",
        kind: WireKind::Request(CHAIN_GET_HEAD_HEADER),
    },
    WireEntry {
        method: "chain_get_head_body",
        kind: WireKind::Request(CHAIN_GET_HEAD_BODY),
    },
    WireEntry {
        method: "chain_get_head_storage",
        kind: WireKind::Request(CHAIN_GET_HEAD_STORAGE),
    },
    WireEntry {
        method: "chain_call_head",
        kind: WireKind::Request(CHAIN_CALL_HEAD),
    },
    WireEntry {
        method: "chain_unpin_head",
        kind: WireKind::Request(CHAIN_UNPIN_HEAD),
    },
    WireEntry {
        method: "chain_continue_head",
        kind: WireKind::Request(CHAIN_CONTINUE_HEAD),
    },
    WireEntry {
        method: "chain_stop_head_operation",
        kind: WireKind::Request(CHAIN_STOP_HEAD_OPERATION),
    },
    WireEntry {
        method: "chain_get_spec_genesis_hash",
        kind: WireKind::Request(CHAIN_GET_SPEC_GENESIS_HASH),
    },
    WireEntry {
        method: "chain_get_spec_chain_name",
        kind: WireKind::Request(CHAIN_GET_SPEC_CHAIN_NAME),
    },
    WireEntry {
        method: "chain_get_spec_properties",
        kind: WireKind::Request(CHAIN_GET_SPEC_PROPERTIES),
    },
    WireEntry {
        method: "chain_broadcast_transaction",
        kind: WireKind::Request(CHAIN_BROADCAST_TRANSACTION),
    },
    WireEntry {
        method: "chain_stop_transaction",
        kind: WireKind::Request(CHAIN_STOP_TRANSACTION),
    },
    WireEntry {
        method: "chain_get_chain_info",
        kind: WireKind::Request(CHAIN_GET_CHAIN_INFO),
    },
    WireEntry {
        method: "chat_create_room",
        kind: WireKind::Request(CHAT_CREATE_ROOM),
    },
    WireEntry {
        method: "chat_register_bot",
        kind: WireKind::Request(CHAT_REGISTER_BOT),
    },
    WireEntry {
        method: "chat_list_subscribe",
        kind: WireKind::Subscription(CHAT_LIST_SUBSCRIBE),
    },
    WireEntry {
        method: "chat_post_message",
        kind: WireKind::Request(CHAT_POST_MESSAGE),
    },
    WireEntry {
        method: "chat_action_subscribe",
        kind: WireKind::Subscription(CHAT_ACTION_SUBSCRIBE),
    },
    WireEntry {
        method: "coin_payment_create_purse",
        kind: WireKind::Request(COIN_PAYMENT_CREATE_PURSE),
    },
    WireEntry {
        method: "coin_payment_query_purse",
        kind: WireKind::Request(COIN_PAYMENT_QUERY_PURSE),
    },
    WireEntry {
        method: "coin_payment_rebalance_purse",
        kind: WireKind::Subscription(COIN_PAYMENT_REBALANCE_PURSE),
    },
    WireEntry {
        method: "coin_payment_delete_purse",
        kind: WireKind::Subscription(COIN_PAYMENT_DELETE_PURSE),
    },
    WireEntry {
        method: "coin_payment_create_receivable",
        kind: WireKind::Request(COIN_PAYMENT_CREATE_RECEIVABLE),
    },
    WireEntry {
        method: "coin_payment_create_cheque",
        kind: WireKind::Request(COIN_PAYMENT_CREATE_CHEQUE),
    },
    WireEntry {
        method: "coin_payment_deposit",
        kind: WireKind::Subscription(COIN_PAYMENT_DEPOSIT),
    },
    WireEntry {
        method: "coin_payment_refund",
        kind: WireKind::Subscription(COIN_PAYMENT_REFUND),
    },
    WireEntry {
        method: "coin_payment_listen_for_payment",
        kind: WireKind::Subscription(COIN_PAYMENT_LISTEN_FOR_PAYMENT),
    },
    WireEntry {
        method: "entropy_derive",
        kind: WireKind::Request(ENTROPY_DERIVE),
    },
    WireEntry {
        method: "local_storage_read",
        kind: WireKind::Request(LOCAL_STORAGE_READ),
    },
    WireEntry {
        method: "local_storage_write",
        kind: WireKind::Request(LOCAL_STORAGE_WRITE),
    },
    WireEntry {
        method: "local_storage_clear",
        kind: WireKind::Request(LOCAL_STORAGE_CLEAR),
    },
    WireEntry {
        method: "local_storage_subscribe",
        kind: WireKind::Subscription(LOCAL_STORAGE_SUBSCRIBE),
    },
    WireEntry {
        method: "notifications_send_push_notification",
        kind: WireKind::Request(NOTIFICATIONS_SEND_PUSH_NOTIFICATION),
    },
    WireEntry {
        method: "notifications_cancel_push_notification",
        kind: WireKind::Request(NOTIFICATIONS_CANCEL_PUSH_NOTIFICATION),
    },
    WireEntry {
        method: "payment_balance_subscribe",
        kind: WireKind::Subscription(PAYMENT_BALANCE_SUBSCRIBE),
    },
    WireEntry {
        method: "payment_top_up",
        kind: WireKind::Request(PAYMENT_TOP_UP),
    },
    WireEntry {
        method: "payment_request",
        kind: WireKind::Request(PAYMENT_REQUEST),
    },
    WireEntry {
        method: "payment_status_subscribe",
        kind: WireKind::Subscription(PAYMENT_STATUS_SUBSCRIBE),
    },
    WireEntry {
        method: "permissions_request_device_permission",
        kind: WireKind::Request(PERMISSIONS_REQUEST_DEVICE_PERMISSION),
    },
    WireEntry {
        method: "permissions_request_remote_permission",
        kind: WireKind::Request(PERMISSIONS_REQUEST_REMOTE_PERMISSION),
    },
    WireEntry {
        method: "permissions_authorize_remote_permission",
        kind: WireKind::Request(PERMISSIONS_AUTHORIZE_REMOTE_PERMISSION),
    },
    WireEntry {
        method: "permissions_authorize_device_permission",
        kind: WireKind::Request(PERMISSIONS_AUTHORIZE_DEVICE_PERMISSION),
    },
    WireEntry {
        method: "preimage_lookup_subscribe",
        kind: WireKind::Subscription(PREIMAGE_LOOKUP_SUBSCRIBE),
    },
    WireEntry {
        method: "preimage_submit",
        kind: WireKind::Request(PREIMAGE_SUBMIT),
    },
    WireEntry {
        method: "resource_allocation_request",
        kind: WireKind::Request(RESOURCE_ALLOCATION_REQUEST),
    },
    WireEntry {
        method: "signing_create_transaction",
        kind: WireKind::Request(SIGNING_CREATE_TRANSACTION),
    },
    WireEntry {
        method: "signing_create_transaction_with_legacy_account",
        kind: WireKind::Request(SIGNING_CREATE_TRANSACTION_WITH_LEGACY_ACCOUNT),
    },
    WireEntry {
        method: "signing_sign_raw_with_legacy_account",
        kind: WireKind::Request(SIGNING_SIGN_RAW_WITH_LEGACY_ACCOUNT),
    },
    WireEntry {
        method: "signing_sign_payload_with_legacy_account",
        kind: WireKind::Request(SIGNING_SIGN_PAYLOAD_WITH_LEGACY_ACCOUNT),
    },
    WireEntry {
        method: "signing_sign_raw",
        kind: WireKind::Request(SIGNING_SIGN_RAW),
    },
    WireEntry {
        method: "signing_sign_payload",
        kind: WireKind::Request(SIGNING_SIGN_PAYLOAD),
    },
    WireEntry {
        method: "signing_sign_raw_unwatermarked_deprecated",
        kind: WireKind::Request(SIGNING_SIGN_RAW_UNWATERMARKED_DEPRECATED),
    },
    WireEntry {
        method: "signing_sign_raw_unwatermarked_deprecated_with_legacy_account",
        kind: WireKind::Request(SIGNING_SIGN_RAW_UNWATERMARKED_DEPRECATED_WITH_LEGACY_ACCOUNT),
    },
    WireEntry {
        method: "statement_store_subscribe",
        kind: WireKind::Subscription(STATEMENT_STORE_SUBSCRIBE),
    },
    WireEntry {
        method: "statement_store_create_proof",
        kind: WireKind::Request(STATEMENT_STORE_CREATE_PROOF),
    },
    WireEntry {
        method: "statement_store_submit",
        kind: WireKind::Request(STATEMENT_STORE_SUBMIT),
    },
    WireEntry {
        method: "statement_store_create_proof_authorized",
        kind: WireKind::Request(STATEMENT_STORE_CREATE_PROOF_AUTHORIZED),
    },
    WireEntry {
        method: "theme_subscribe",
        kind: WireKind::Subscription(THEME_SUBSCRIBE),
    },
    WireEntry {
        method: "locale_subscribe",
        kind: WireKind::Subscription(LOCALE_SUBSCRIBE),
    },
    WireEntry {
        method: "renderer_render",
        kind: WireKind::Subscription(RENDERER_RENDER),
    },
    WireEntry {
        method: "renderer_action_subscribe",
        kind: WireKind::Subscription(RENDERER_ACTION_SUBSCRIBE),
    },
    WireEntry {
        method: "pocket_list_subscribe",
        kind: WireKind::Subscription(POCKET_LIST_SUBSCRIBE),
    },
    WireEntry {
        method: "pocket_remove_card",
        kind: WireKind::Request(POCKET_REMOVE_CARD),
    },
    WireEntry {
        method: "worker_begin_operation",
        kind: WireKind::Request(WORKER_BEGIN_OPERATION),
    },
    WireEntry {
        method: "worker_end_operation",
        kind: WireKind::Request(WORKER_END_OPERATION),
    },
    WireEntry {
        method: "contacts_pick",
        kind: WireKind::Request(CONTACTS_PICK),
    },
    WireEntry {
        method: "game_remind_next_game",
        kind: WireKind::Request(GAME_REMIND_NEXT_GAME),
    },
    WireEntry {
        method: "game_cancel_next_game",
        kind: WireKind::Request(GAME_CANCEL_NEXT_GAME),
    },
];
