// Auto-generated by truapi-codegen. Do not edit.
//
// Worker-side metadata and proxy functions for the raw WASM callback
// surface. The worker transport/lifecycle remains hand-written; this
// file owns the callback names, host-hook arity, and
// subscription payload shape derived from the `platform` modules.

import type { RawCallbacks } from "./host-callbacks-adapter.js";
import type { GenericError } from "@parity/truapi";

import type { ChainConnect } from "../runtime.js";

export const CALLBACK_NAMES = [
  "authStateChanged",
  "createChatRoom",
  "registerChatBot",
  "postChatMessage",
  "contacts",
  "pickContact",
  "readCoreStorage",
  "writeCoreStorage",
  "clearCoreStorage",
  "featureSupported",
  "supportedChains",
  "scheduleGameReminder",
  "cancelGameReminder",
  "navigateTo",
  "pushNotification",
  "cancelNotification",
  "devicePermissionStatus",
  "devicePermission",
  "remotePermission",
  "removePocketCard",
  "beginOperation",
  "endOperation",
  "read",
  "write",
  "clear",
  "confirmPermission",
  "confirmUserAction",
] as const;
export type CallbackName = (typeof CALLBACK_NAMES)[number];

export const SUBSCRIPTION_NAMES = [
  "subscribeChatRooms",
  "subscribeLocale",
  "subscribePocketCards",
  "lookupPreimage",
  "subscribeStorage",
  "subscribeTheme",
] as const;
export type SubscriptionName = (typeof SUBSCRIPTION_NAMES)[number];

export interface WorkerCallbackBridge {
  callbackRequest(
    name: CallbackName,
    args: readonly unknown[],
  ): Promise<unknown>;
  startSubscription<T>(
    name: SubscriptionName,
    payload: Uint8Array | string | null,
    sendItem: (value: T) => void,
    sendError: (error: GenericError) => void,
  ): () => void;
  chainConnect: ChainConnect;
}

function rawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<
  Pick<
    RawCallbacks,
    | "authStateChanged"
    | "readCoreStorage"
    | "writeCoreStorage"
    | "clearCoreStorage"
    | "featureSupported"
    | "supportedChains"
    | "navigateTo"
    | "pushNotification"
    | "cancelNotification"
    | "devicePermission"
    | "remotePermission"
    | "beginOperation"
    | "endOperation"
    | "read"
    | "write"
    | "clear"
    | "confirmPermission"
    | "confirmUserAction"
  >
> {
  return {
    authStateChanged: (state) =>
      void bridge.callbackRequest("authStateChanged", [state]).catch(() => {}),
    readCoreStorage: (key) =>
      bridge.callbackRequest("readCoreStorage", [key]) as ReturnType<
        Required<RawCallbacks>["readCoreStorage"]
      >,
    writeCoreStorage: (key, value) =>
      bridge.callbackRequest("writeCoreStorage", [key, value]) as ReturnType<
        Required<RawCallbacks>["writeCoreStorage"]
      >,
    clearCoreStorage: (key) =>
      bridge.callbackRequest("clearCoreStorage", [key]) as ReturnType<
        Required<RawCallbacks>["clearCoreStorage"]
      >,
    featureSupported: (request) =>
      bridge.callbackRequest("featureSupported", [request]) as ReturnType<
        Required<RawCallbacks>["featureSupported"]
      >,
    supportedChains: () =>
      bridge.callbackRequest("supportedChains", []) as ReturnType<
        Required<RawCallbacks>["supportedChains"]
      >,
    navigateTo: (url) =>
      bridge.callbackRequest("navigateTo", [url]) as ReturnType<
        Required<RawCallbacks>["navigateTo"]
      >,
    pushNotification: (notification) =>
      bridge.callbackRequest("pushNotification", [notification]) as ReturnType<
        Required<RawCallbacks>["pushNotification"]
      >,
    cancelNotification: (id) =>
      bridge.callbackRequest("cancelNotification", [id]) as ReturnType<
        Required<RawCallbacks>["cancelNotification"]
      >,
    devicePermission: (product, request) =>
      bridge.callbackRequest("devicePermission", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["devicePermission"]>,
    remotePermission: (product, request) =>
      bridge.callbackRequest("remotePermission", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["remotePermission"]>,
    beginOperation: (product, label) =>
      bridge.callbackRequest("beginOperation", [product, label]) as ReturnType<
        Required<RawCallbacks>["beginOperation"]
      >,
    endOperation: (product, id) =>
      bridge.callbackRequest("endOperation", [product, id]) as ReturnType<
        Required<RawCallbacks>["endOperation"]
      >,
    read: (key) =>
      bridge.callbackRequest("read", [key]) as ReturnType<
        Required<RawCallbacks>["read"]
      >,
    write: (key, value) =>
      bridge.callbackRequest("write", [key, value]) as ReturnType<
        Required<RawCallbacks>["write"]
      >,
    clear: (key) =>
      bridge.callbackRequest("clear", [key]) as ReturnType<
        Required<RawCallbacks>["clear"]
      >,
    confirmPermission: (review) =>
      bridge.callbackRequest("confirmPermission", [review]) as ReturnType<
        Required<RawCallbacks>["confirmPermission"]
      >,
    confirmUserAction: (review) =>
      bridge.callbackRequest("confirmUserAction", [review]) as ReturnType<
        Required<RawCallbacks>["confirmUserAction"]
      >,
  };
}

function subscriptionRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<
  Pick<
    RawCallbacks,
    "subscribeLocale" | "lookupPreimage" | "subscribeStorage" | "subscribeTheme"
  >
> {
  return {
    subscribeLocale: (sendItem, sendError) =>
      bridge.startSubscription("subscribeLocale", null, sendItem, sendError),
    lookupPreimage: (key, sendItem, sendError) =>
      bridge.startSubscription("lookupPreimage", key, sendItem, sendError),
    subscribeStorage: (key, sendItem, sendError) =>
      bridge.startSubscription("subscribeStorage", key, sendItem, sendError),
    subscribeTheme: (sendItem, sendError) =>
      bridge.startSubscription("subscribeTheme", null, sendItem, sendError),
  };
}

function chatRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<
  Pick<
    RawCallbacks,
    | "createChatRoom"
    | "registerChatBot"
    | "postChatMessage"
    | "subscribeChatRooms"
  >
> {
  return {
    createChatRoom: (product, request) =>
      bridge.callbackRequest("createChatRoom", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["createChatRoom"]>,
    registerChatBot: (product, request) =>
      bridge.callbackRequest("registerChatBot", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["registerChatBot"]>,
    postChatMessage: (product, request) =>
      bridge.callbackRequest("postChatMessage", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["postChatMessage"]>,
    subscribeChatRooms: (product, sendItem, sendError) =>
      bridge.startSubscription(
        "subscribeChatRooms",
        product,
        sendItem,
        sendError,
      ),
  };
}

function contactsRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<Pick<RawCallbacks, "contacts" | "pickContact">> {
  return {
    contacts: (lookup) =>
      bridge.callbackRequest("contacts", [lookup]) as ReturnType<
        Required<RawCallbacks>["contacts"]
      >,
    pickContact: (product) =>
      bridge.callbackRequest("pickContact", [product]) as ReturnType<
        Required<RawCallbacks>["pickContact"]
      >,
  };
}

function gameRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<Pick<RawCallbacks, "scheduleGameReminder" | "cancelGameReminder">> {
  return {
    scheduleGameReminder: (product, startsAt) =>
      bridge.callbackRequest("scheduleGameReminder", [
        product,
        startsAt,
      ]) as ReturnType<Required<RawCallbacks>["scheduleGameReminder"]>,
    cancelGameReminder: (product) =>
      bridge.callbackRequest("cancelGameReminder", [product]) as ReturnType<
        Required<RawCallbacks>["cancelGameReminder"]
      >,
  };
}

function permissionStatusRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<Pick<RawCallbacks, "devicePermissionStatus">> {
  return {
    devicePermissionStatus: (request) =>
      bridge.callbackRequest("devicePermissionStatus", [request]) as ReturnType<
        Required<RawCallbacks>["devicePermissionStatus"]
      >,
  };
}

function pocketRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<Pick<RawCallbacks, "subscribePocketCards" | "removePocketCard">> {
  return {
    subscribePocketCards: (product, sendItem, sendError) =>
      bridge.startSubscription(
        "subscribePocketCards",
        product,
        sendItem,
        sendError,
      ),
    removePocketCard: (product, request) =>
      bridge.callbackRequest("removePocketCard", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["removePocketCard"]>,
  };
}

/**
 * Optional capabilities the main-thread host actually serves. A
 * capability left out here is not proxied into the worker, so the
 * core answers its product calls with `Unsupported`.
 */
export interface OptionalCapabilities {
  /** Whether the host serves this capability. */
  chat?: boolean;
  /** Whether the host serves this capability. */
  contacts?: boolean;
  /** Whether the host serves this capability. */
  game?: boolean;
  /** Whether the host serves this capability. */
  permissionStatus?: boolean;
  /** Whether the host serves this capability. */
  pocket?: boolean;
}

export function createWorkerRawCallbacks(
  bridge: WorkerCallbackBridge,
  capabilities: OptionalCapabilities = {},
): Record<string, unknown> {
  const callbacks: Record<string, unknown> = {
    ...rawCallbacks(bridge),
    ...subscriptionRawCallbacks(bridge),
    chainConnect: bridge.chainConnect,
  };
  if (capabilities.chat) Object.assign(callbacks, chatRawCallbacks(bridge));
  if (capabilities.contacts)
    Object.assign(callbacks, contactsRawCallbacks(bridge));
  if (capabilities.game) Object.assign(callbacks, gameRawCallbacks(bridge));
  if (capabilities.permissionStatus)
    Object.assign(callbacks, permissionStatusRawCallbacks(bridge));
  if (capabilities.pocket) Object.assign(callbacks, pocketRawCallbacks(bridge));
  return callbacks;
}

export function startRawSubscription(
  callbacks: RawCallbacks,
  name: SubscriptionName,
  payload: Uint8Array | string | null,
  sendItem: (value?: unknown) => void,
  sendError: (error: GenericError) => void,
): (() => void) | void {
  switch (name) {
    case "subscribeChatRooms":
      if (!(payload instanceof Uint8Array)) {
        console.warn(`[truapi worker] ${name} requires payload`);
        return undefined;
      }
      return callbacks.subscribeChatRooms?.(payload, sendItem, sendError);
    case "subscribeLocale":
      return callbacks.subscribeLocale(sendItem, sendError);
    case "subscribePocketCards":
      if (!(payload instanceof Uint8Array)) {
        console.warn(`[truapi worker] ${name} requires payload`);
        return undefined;
      }
      return callbacks.subscribePocketCards?.(payload, sendItem, sendError);
    case "lookupPreimage":
      if (!(payload instanceof Uint8Array)) {
        console.warn(`[truapi worker] ${name} requires payload`);
        return undefined;
      }
      return callbacks.lookupPreimage(payload, sendItem, sendError);
    case "subscribeStorage":
      if (typeof payload !== "string") {
        console.warn(`[truapi worker] ${name} requires payload`);
        return undefined;
      }
      return callbacks.subscribeStorage(payload, sendItem, sendError);
    case "subscribeTheme":
      return callbacks.subscribeTheme(sendItem, sendError);
  }
}
